# (노트) 판다스조인 사용하기

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- categories: [파이썬]

### 예제1

`-` df1 데이터선언; 각 observation은 영화이름의 알파벳순서로 나열.

In [7]:
import pandas as pd 
df1=pd.DataFrame({'nodename':['Ant-man','Hulk','Iron-man'],'open':[2020,2012,2010]})
df1

   nodename  open
0   Ant-man  2020
1      Hulk  2012
2  Iron-man  2010

`-` df2 데이터선언; observation은 영화개봉순으로 나열.

In [8]:
df2=pd.DataFrame({'nodename':['Iron-man','Hulk','Ant-man'],'box-office':[100,300,50]})
df2

   nodename  box-office
0  Iron-man         100
1      Hulk         300
2   Ant-man          50

`-` df1,df2는 nodename이라는 공통된 열이 존재함 $\to$ inner join 으로 두 데이터를 합칠 수 있다.

df1에서 나열된 obsevation 순으로 합치자.

In [9]:
pd.merge(df1,df2)

   nodename  open  box-office
0   Ant-man  2020          50
1      Hulk  2012         300
2  Iron-man  2010         100

df2에서 나열된 observation 순으로 합치자.

In [10]:
pd.merge(df2,df1)

   nodename  box-office  open
0  Iron-man         100  2010
1      Hulk         300  2012
2   Ant-man          50  2020

### 예제2: observation 수가 달라도 가능함