# 판다스 - 인덱싱
> 작성완료 

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- categories: [파이썬]

### About this doc

`-` 데이터프레임에서 열을 선택하는 방법에 대하여 다룬다.

### 데이터 선언

In [3]:
import numpy as np
import pandas as pd

In [4]:
dic={'X1':np.random.normal(0,1,5), 
     'X2':np.random.normal(0,1,5),
     'X3':np.random.normal(0,1,5)}
df=pd.DataFrame(dic)
df

         X1        X2        X3
0  0.659255  0.165344  0.733850
1  0.461843  0.648005  0.261899
2  0.894380 -0.483557 -0.385227
3 -0.172640 -0.225751 -0.270766
4  2.349347 -0.379206 -0.676576

###  첫번째 열을 선택하는 4가지 방법
`-` `df`에서 첫번째 열을 선택하는 방법은 아래와 같이 4가지의 방법이 있다.

- `df.X1` 
- `df[['X1']]`
- `df.loc[:,['X1']]`
- `df.iloc[:,0]`

### 방법1: `df.X1`

`-` 첫번째 방법은 `df.X1`와 같이 사용하는 것이다. 

`-` 이것은 가장 간단한 방법이다. 

`-` 하지만 컬럼이름에 `.`이 들어가면 쓸 수 없다는 치명적인 단점이 있다. 즉 컬럼이름이 `X1`인 경우는 쓸 수 있지만 컬럼이름이 `X.1`와 같은 경우 쓸 수 없다.

In [5]:
df.X1

0    0.659255
1    0.461843
2    0.894380
3   -0.172640
4    2.349347
Name: X1, dtype: float64

### 방법2: `df[['X1']]`

`-` 두번째 방법은 추출하고 싶은 인덱스의 이름을 `list`형으로 전달하는 방법이다. 

`-` `df[['X1']]` 이 방법은 위와 달리 컬럼이름에 `.`이 있어도 쓸 수 있다.

In [6]:
df[['X1']]

         X1
0  0.659255
1  0.461843
2  0.894380
3 -0.172640
4  2.349347

`-` 또한 위의 방법과 달리 여러개의 컬럼을 선택가능하다.  즉 아래가 가능하다.

In [7]:
df[['X1','X2']]

         X1        X2
0  0.659255  0.165344
1  0.461843  0.648005
2  0.894380 -0.483557
3 -0.172640 -0.225751
4  2.349347 -0.379206

`-` 하지만 슬라이싱을 활용하여 여러컬럼을 선택할 수는 없다. 즉 아래가 불가능하다.

In [8]:
df['X1':'X3']

TypeError: cannot do slice indexing on RangeIndex with these indexers [X1] of type str

### 방법3: `df.loc[:,'X1']`

`-` 세번째는 `loc`을 이용한 방법이다. 

`-` `df.loc[:,'X1']`은 기본적으로 컬럼이름에 "."이 포함되어도 사용할 수 있다.

In [11]:
df.loc[:,'X1']

0    0.659255
1    0.461843
2    0.894380
3   -0.172640
4    2.349347
Name: X1, dtype: float64

`-` 또한 여러개의 컬럼을 호출할 수 있다. 즉 아래가 가능하다.

In [12]:
df.loc[:,['X1','X2']]

         X1        X2
0  0.659255  0.165344
1  0.461843  0.648005
2  0.894380 -0.483557
3 -0.172640 -0.225751
4  2.349347 -0.379206

`-` 슬라이싱을 통하여 여러개의 컬럼을 선택할수 있다.

In [13]:
df.loc[:,'X1':'X3']

         X1        X2        X3
0  0.659255  0.165344  0.733850
1  0.461843  0.648005  0.261899
2  0.894380 -0.483557 -0.385227
3 -0.172640 -0.225751 -0.270766
4  2.349347 -0.379206 -0.676576

>Note: (단점) 이 방법의 단점은 컬럼의 `index-set`을 정의하고 접근하는것은 불가능하다. 예를들어 `홀수번째 컬럼들만 출력하는 코드`를 짤 수 없다.

### 방법4: `df.iloc[:,0]`

`–` 마지막 방법은 `iloc`을 사용하는 것이다. 

`–` `iloc`역시 `loc`과 마찬가지로 슬라이싱이 가능하다. 

`–` 하지만 `loc`의 경우와 그 결과가 다르다. 1,2,3번째 변수를 `loc`으로 추출하고 싶을 경우

In [16]:
df.loc[:,'X1':'X3']

         X1        X2        X3
0  0.659255  0.165344  0.733850
1  0.461843  0.648005  0.261899
2  0.894380 -0.483557 -0.385227
3 -0.172640 -0.225751 -0.270766
4  2.349347 -0.379206 -0.676576

와 같이 하지만 같은 결과를 `iloc`으로 구현하려면

In [17]:
df.iloc[:,0:3]

         X1        X2        X3
0  0.659255  0.165344  0.733850
1  0.461843  0.648005  0.261899
2  0.894380 -0.483557 -0.385227
3 -0.172640 -0.225751 -0.270766
4  2.349347 -0.379206 -0.676576

와 같이 해야한다. 즉 `loc`의 경우 양쪽인덱스가 모두 포함되지만 `iloc`의 경우 마지막 인덱스는 포함되지 않는다.

### ***`iloc`의 장점***

`–` `iloc`의 장점은 아래와 같이 `index-set` 을 정의하고 접근하는것도 가능하다. 예를들어 홀수번째 번수들만 출력하는 코드를 다음과 같이 구현가능하다.

In [18]:
index1=[0,2]
df.iloc[:,index1]

         X1        X3
0  0.659255  0.733850
1  0.461843  0.261899
2  0.894380 -0.385227
3 -0.172640 -0.270766
4  2.349347 -0.676576