# (정리) pandas

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- categories: [파이썬]

### About this doc

`-` 이 문서는 아래의 문서들을 상속받아 작성되었다. 

- [판다스에서 인덱싱하기, 신록예찬](https://miruetoto.github.io/yechan/%ED%8C%8C%EC%9D%B4%EC%8D%AC/2020/08/31/(%EC%83%98%ED%94%8C)-%ED%8C%90%EB%8B%A4%EC%8A%A4%EC%97%90%EC%84%9C-%EC%9D%B8%EB%8D%B1%EC%8B%B1%ED%95%98%EA%B8%B0-%ED%8C%8C%EC%9D%B4%EC%8D%AC.html)

### import

In [113]:
import pandas as pd
import numpy as np
from dfply import *

### read data from github

In [114]:
url='https://raw.githubusercontent.com/PacktPublishing/Pandas-Cookbook-Second-Edition/master/data/movie.csv'
df = pd.read_csv(url, index_col=0)
df

,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
color,,,,,,,,,,,,,,,,,,,,,
Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,Eric Mabius,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,Eva Boehnke,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,Alan Ruck,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,John August,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

- NaN: missing, not a number

### convert numpy and indexing

In [115]:
data=df.to_numpy()
data

array([['James Cameron', 723.0, 178.0, ..., 7.9, 1.78, 33000],
       ['Gore Verbinski', 302.0, 169.0, ..., 7.1, 2.35, 0],
       ['Sam Mendes', 602.0, 148.0, ..., 6.8, 2.35, 85000],
       ...,
       ['Benjamin Roberds', 13.0, 76.0, ..., 6.3, nan, 16],
       ['Daniel Hsia', 14.0, 100.0, ..., 6.3, 2.35, 660],
       ['Jon Gunn', 43.0, 90.0, ..., 6.6, 1.85, 456]], dtype=object)

In [116]:
data[0] ## first observation

array(['James Cameron', 723.0, 178.0, 0.0, 855.0, 'Joel David Moore',
       1000.0, 760505847.0, 'Action|Adventure|Fantasy|Sci-Fi',
       'CCH Pounder', 'Avatar', 886204, 4834, 'Wes Studi', 0.0,
       'avatar|future|marine|native|paraplegic',
       'http://www.imdb.com/title/tt0499549/?ref_=fn_tt_tt_1', 3054.0,
       'English', 'USA', 'PG-13', 237000000.0, 2009.0, 936.0, 7.9, 1.78,
       33000], dtype=object)

In [117]:
data[0][0] # (first observation, first variable)

'James Cameron'

In [118]:
data.T[0] # first variable

array(['James Cameron', 'Gore Verbinski', 'Sam Mendes', ...,
       'Benjamin Roberds', 'Daniel Hsia', 'Jon Gunn'], dtype=object)

In [119]:
data[:,0] # first variable

array(['James Cameron', 'Gore Verbinski', 'Sam Mendes', ...,
       'Benjamin Roberds', 'Daniel Hsia', 'Jon Gunn'], dtype=object)

### select column

#### `df`에서 하나의 열을 선택하는 방법

In [120]:
dic={'X1':np.random.normal(0,1,5), 
     'X2':np.random.normal(0,1,5),
     'X3':np.random.normal(0,1,5)}
df=pd.DataFrame(dic)
df

         X1        X2        X3
0  0.994481  1.340418  0.581463
1  0.116595 -0.594872  0.377041
2  0.052723 -1.586597 -0.972149
3 -0.014302 -0.149805  1.757051
4 -0.092762 -1.130025 -1.002090

`-` 방법1

In [121]:
df.X1

0    0.994481
1    0.116595
2    0.052723
3   -0.014302
4   -0.092762
Name: X1, dtype: float64

`-` 방법2

In [122]:
df['X1']

0    0.994481
1    0.116595
2    0.052723
3   -0.014302
4   -0.092762
Name: X1, dtype: float64

`-` 방법3

In [123]:
df[['X1']]

         X1
0  0.994481
1  0.116595
2  0.052723
3 -0.014302
4 -0.092762

- `df['X1']`는 series를 리턴하고 `df[['X1']]`는 dataframe을 리턴한다.

`-` 방법4

In [124]:
df.loc[:,'X1']

0    0.994481
1    0.116595
2    0.052723
3   -0.014302
4   -0.092762
Name: X1, dtype: float64

`-` 방법5

In [125]:
df.loc[:,['X1']]

         X1
0  0.994481
1  0.116595
2  0.052723
3 -0.014302
4 -0.092762

- `df.loc[:,'X1']`는 series를 리턴하고 `df[['X1']]`는 dataframe을 리턴한다.

`-` 방법6

In [126]:
df.iloc[:,0]

0    0.994481
1    0.116595
2    0.052723
3   -0.014302
4   -0.092762
Name: X1, dtype: float64

`-` 방법7

In [127]:
df.iloc[:,[0]]

         X1
0  0.994481
1  0.116595
2  0.052723
3 -0.014302
4 -0.092762

`-` 방법8 (`dfply`)

In [135]:
df >> select(0)

         X1
0  0.994481
1  0.116595
2  0.052723
3 -0.014302
4 -0.092762

In [136]:
df >> select([0])

         X1
0  0.994481
1  0.116595
2  0.052723
3 -0.014302
4 -0.092762

In [138]:
df >> select('X1')

         X1
0  0.994481
1  0.116595
2  0.052723
3 -0.014302
4 -0.092762

In [144]:
df >> select(['X1'])

         X1
0  0.994481
1  0.116595
2  0.052723
3 -0.014302
4 -0.092762

***요약***

- `df.X1` 이 가장 간단하고 편리함. 그런데 변수이름을 알고 있어야 한다는 단점이 있음. 
- `df.X1` 은 변수이름에 `.`이 포함된 경우는 사용불가. 그밖에도 변수이름에 공백이 있는등 이상한 형태의 변수이름에는 사용불가능.
- 변수이름을 모르면서 위치로 select하는 방법은 df.iloc을 이용하는 방법이 유일함. (dfply 패지키 사용하는 방법은 제외)

#### 열이름이 integer일 경우

In [154]:
df = pd.DataFrame(np.array([[1,2,3],[3,4,5],[5,6,7]]))
df

   0  1  2
0  1  2  3
1  3  4  5
2  5  6  7

`-` 아래가 모두 가능

In [156]:
df[0]

0    1
1    3
2    5
Name: 0, dtype: int64

In [162]:
df[[0]]

   0
0  1
1  3
2  5

In [160]:
df.loc[:,[0]]

   0
0  1
1  3
2  5

In [161]:
df.iloc[:,[0]]

   0
0  1
1  3
2  5

#### 1,2,3열을 선택

In [164]:
dic={'X1':np.random.normal(0,1,5), 
     'X2':np.random.normal(0,1,5),
     'X3':np.random.normal(0,1,5),
     'X4':np.random.normal(0,1,5)
    }
df=pd.DataFrame(dic)
df

         X1        X2        X3        X4
0 -1.007326  0.211947  0.502961  1.002363
1 -0.025777 -0.977503  1.195062 -0.404275
2  1.780113 -0.036004 -1.423360 -1.136555
3  0.312279  0.522670 -2.213946 -1.004610
4  1.934208 -0.736165  0.189475  0.864337

`-` 방법1

In [168]:
df[['X1','X2','X3']]

         X1        X2        X3
0 -1.007326  0.211947  0.502961
1 -0.025777 -0.977503  1.195062
2  1.780113 -0.036004 -1.423360
3  0.312279  0.522670 -2.213946
4  1.934208 -0.736165  0.189475

위와 동일한 문법을 응용하면

In [171]:
varlist=['X'+i for i in '123']
varlist

['X1', 'X2', 'X3']

In [172]:
df[varlist]

         X1        X2        X3
0 -1.007326  0.211947  0.502961
1 -0.025777 -0.977503  1.195062
2  1.780113 -0.036004 -1.423360
3  0.312279  0.522670 -2.213946
4  1.934208 -0.736165  0.189475

`-` 방법2

In [177]:
df.loc[:,['X1','X2','X3']]

         X1        X2        X3
0 -1.007326  0.211947  0.502961
1 -0.025777 -0.977503  1.195062
2  1.780113 -0.036004 -1.423360
3  0.312279  0.522670 -2.213946
4  1.934208 -0.736165  0.189475

`-` 방법3

In [178]:
df.loc[:,'X1':'X3']

         X1        X2        X3
0 -1.007326  0.211947  0.502961
1 -0.025777 -0.977503  1.195062
2  1.780113 -0.036004 -1.423360
3  0.312279  0.522670 -2.213946
4  1.934208 -0.736165  0.189475

`-` 방법4

In [179]:
df.iloc[:,[0,1,2]]

         X1        X2        X3
0 -1.007326  0.211947  0.502961
1 -0.025777 -0.977503  1.195062
2  1.780113 -0.036004 -1.423360
3  0.312279  0.522670 -2.213946
4  1.934208 -0.736165  0.189475

이 방법을 응용하면

In [184]:
idx = range(3)
idx

range(0, 3)

In [185]:
df.iloc[:,idx]

         X1        X2        X3
0 -1.007326  0.211947  0.502961
1 -0.025777 -0.977503  1.195062
2  1.780113 -0.036004 -1.423360
3  0.312279  0.522670 -2.213946
4  1.934208 -0.736165  0.189475

In [186]:
idx = np.arange(3)
idx

array([0, 1, 2])

In [187]:
df.iloc[:,idx]

         X1        X2        X3
0 -1.007326  0.211947  0.502961
1 -0.025777 -0.977503  1.195062
2  1.780113 -0.036004 -1.423360
3  0.312279  0.522670 -2.213946
4  1.934208 -0.736165  0.189475

In [189]:
idx = np.arange(3.)
idx

array([0., 1., 2.])

In [190]:
df.iloc[:,idx]

         X1        X2        X3
0 -1.007326  0.211947  0.502961
1 -0.025777 -0.977503  1.195062
2  1.780113 -0.036004 -1.423360
3  0.312279  0.522670 -2.213946
4  1.934208 -0.736165  0.189475

- idx의 값이 float형으로 저장되어 있어도 에러나지 않음

`-` 방법5

In [192]:
df.iloc[:,0:3]

         X1        X2        X3
0 -1.007326  0.211947  0.502961
1 -0.025777 -0.977503  1.195062
2  1.780113 -0.036004 -1.423360
3  0.312279  0.522670 -2.213946
4  1.934208 -0.736165  0.189475

**(주의) loc에서의 슬라이싱은 마지막변수를 포함하지만 iloc에서는 포함하지 않음.**

`-` 아래를 비교하라.

In [198]:
df.iloc[:,0:3] ## 3은 포함되지 않는다.

         X1        X2        X3
0 -1.007326  0.211947  0.502961
1 -0.025777 -0.977503  1.195062
2  1.780113 -0.036004 -1.423360
3  0.312279  0.522670 -2.213946
4  1.934208 -0.736165  0.189475

In [199]:
df.loc[:,'X1':'X3'] ## 'X3'이 포함된다.

         X1        X2        X3
0 -1.007326  0.211947  0.502961
1 -0.025777 -0.977503  1.195062
2  1.780113 -0.036004 -1.423360
3  0.312279  0.522670 -2.213946
4  1.934208 -0.736165  0.189475

`-` 그래서 column의 이름이 integer일 경우는 종종 매우 헷갈리는 결과가 나옴

In [203]:
_df = pd.DataFrame(np.array([[1,2,3,4],[3,4,5,6],[5,6,7,8]]))
_df

   0  1  2  3
0  1  2  3  4
1  3  4  5  6
2  5  6  7  8

In [204]:
_df.loc[:,0:2]

   0  1  2
0  1  2  3
1  3  4  5
2  5  6  7

In [205]:
_df.iloc[:,0:2]

   0  1
0  1  2
1  3  4
2  5  6

> note: 사실 이것은 일부러 헷갈리게 예제를 구성한것이다. 실제로는 헷갈리는 상황이 많이 발생하지 않는다. 왜냐하면 보통 위의 예제와 같은 경우에는 ndarray 로 처리하고 colname이 있는 경우만 데이터프레임으로 처리하기 때문

`-` 방법5