# 파이썬입문 기말고사 (draft)
> 작성완료

- toc:false
- branch: master
- badges: false
- comments: false
- author: 최규빈
- categories: [파이썬입문]

### \# 1. (20점)
N사에서 게임유저들에게 여름방학 기념이벤트로 **진명왕의 집판검**이라는 이름의 아이템을 선물했다고 하자. **진명왕의 집판검**은 총 5회에 걸쳐서 강화(upgrade)될 수 있데 강화의 성공확률은 30%라고 하자. 강화가 5번성공하면 더 이상 강화가 진행되지 않는다고 하자. 아래는 이 아이템에 강화를 진행하였을때 각 강화상태를 설명한 예시이다. 

|시도횟수|강화성공여부|강화상태|비고|
|:-:|:-:|:-:|:-|
|1|강화실패|+0 $\to$ +0|강화실패로 인하여 강화상태 변화없음 |
|2|강화성공|+0 $\to$ +1|강화성공으로 인한 강화상태 변화|
|3|강화실패|+1 $\to$ +1|강화실패로 인하여 강화상태 변화없음 |
|4|강화성공|+1 $\to$ +2|강화성공으로 인한 강화상태 변화|
|5|강화성공|+2 $\to$ +3|강화성공으로 인한 강화상태 변화|
|6|강화성공|+3 $\to$ +4|강화성공으로 인한 강화상태 변화|
|7|강화실패|+4 $\to$ +4|강화실패로 인하여 강화상태 변화없음 |
|8|강화성공|+4 $\to$ +5|모든 강화 성공|
|9|-|+5 $\to$ +5|더 이상 강화시도 하지 않음|
|10|$\dots$|$\dots$|$\dots$|


강화는 하루에 한 번씩만 시도할 수 있으며 시도가능한 기간은 7월1일부터 8월31일까지로 한정되어 있다고 하자. 따라서 방학동안 유저들은 총 62번 시도를 할 수 있다. 방학이 끝난이후 100명 유저중 대략 몇명정도 강화에 성공하겠는가? 파이썬을 통한 시뮬레이션을 활용하여 추론하라. (단 모든 유저가 62번의 강화시도를 하였다고 가정하자)

### \# 2. (70점)

강화성공확률을 70%로 수정한다. 강화에 누적2회 실패하면 강화상태가 초기화 된다고 하자. (따라서 강화실패 누적횟수를 카운트하는 변수가 필요하다)
단, 강화실패 누적횟수는 누적2회 달성시 0으로 초기화 된다. 또한 강화상태가 +0인 경우는 실패하여도 강화누적횟수가 추가되지 않는다. 

|시도횟수|강화성공여부|강화상태|강화실패누적|비고|
|:-:|:-:|:-:|:-:|:-|
|1|강화성공|+0 $\to$ +1| 0 $\to$ 0|- |
|2|강화성공|+1 $\to$ +2|0 $\to$ 0 |-|
|3|강화실패|+2 $\to$ +2 |0 $\to$ 1|-| 
|4|강화성공|+2 $\to$ +3 |1 $\to$ 1|-|
|5|강화실패|+3 $\to$ +0 |1 $\to$ 0| 강화실패로 누적2회로 인한 초기화|
|6|강화실패|+0 $\to$ +0|0 $\to$ 0| 강화실패 누적횟수 증가하지 않음|
|7|강화성공|+0 $\to$ +1 |0 $\to$ 0|-|
|8|강화성공|+1 $\to$ +2|0 $\to$ 0|-|
|9|강화성공|+2 $\to$ +3|0 $\to$ 0|-|
|10|강화성공|+3 $\to$ +4|0 $\to$ 0|-|
|11|강화성공|+4 $\to$ +5|0 $\to$ 0|모든 강화 성공|
|12|-|+5 $\to$ +5|0 $\to$ 0|더 이상 강화시도 하지 않음|
|13|$\dots$|$\dots$|$\dots$|$\dots$|

`(1)` 이 경우 62일의 방학뒤에 100명의 유저중 대략 몇명정도 강화에 성공하겠는가? 파이썬을 통한 시뮬레이션을 활용하여 추론하라. (단 모든 유저가 62번의 강화시도를 하였다고 가정하자)

`(2)` 31번째 시도 이후 몇명의 유저가 강화에 성공하였는가?

`(3)` 100명의 유저중 50명이상 강화에 성공하는 순간 모든 유저의 강화성공확률을 90%로 증가시킨다고 하자. 62일의 방학뒤에 100명의 유저중 몇명 정도 강화에 성공하는가?

### Hint

필요하다면 아래의 코드를 활용하라.

`-` p의 확률로 0 혹은 1을 100개 뽑는 함수예시

In [32]:
import numpy as np 
np.random.binomial(n=1, p=0.3, size=100) # 0.3 의 확률로 0 혹은 1을 추출

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0])

In [33]:
np.random.binomial(n=1, p=0.7, size=100) # 0.7 의 확률로 0 혹은 1을 추출

array([0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1])

`-` 강화 성공시에 강화상태를 업그레이드 하는 코드예시

In [42]:
import pandas as pd
upgradestate=pd.DataFrame({'day0':[0]*100})
upgradestate

    day0
0      0
1      0
2      0
3      0
4      0
..   ...
95     0
96     0
97     0
98     0
99     0

[100 rows x 1 columns]

In [45]:
i=1
upgradestate['day%s' % i]=upgradestate['day%s' % (i-1)]+np.random.binomial(n=1, p=0.7, size=100) 
upgradestate

    day0  day1
0      0     0
1      0     1
2      0     0
3      0     0
4      0     1
..   ...   ...
95     0     1
96     0     1
97     0     0
98     0     1
99     0     0

[100 rows x 2 columns]

`-` 'day1'에서 강화실패시 누적

### \# 3. 다음문장을 잘 읽고 참 거짓을 판단하여라. (10점)

(1) tuple은 원소의 값을 임의로 바꿀 수 있다.

(2) ... (추가예정입니다)