# (노트) 티블

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- categories: [R]

In [2]:
library(tidyverse)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.6     ✔ dplyr   1.0.7
✔ tidyr   1.1.4     ✔ stringr 1.4.0
✔ readr   2.1.1     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

### 티블 만드는 방법

`-` 방법1: 선언하여 만들기 (새롭게 정의)

In [3]:
tibble(v1=1:3,v2=c(T,F,T), v3=c("a","b","c"))

  v1 v2    v3
1 1   TRUE a
2 2  FALSE b
3 3   TRUE c

- 각 열들의 자료형이 모두 달라도 가능 (티블의 매력) 
- 티블의 형태는 매트릭스 같지만 이처럼 다른 자료형이 들어가는 것은 마치 리스트를 연상시킨다.

`-` 방법2: 선언하여 만들기2 (기존에 정의된 벡터등을 활용)

In [31]:
x=1:5
y=c("a","b","c","d","e")
tibble(x,y)

  x y
1 1 a
2 2 b
3 3 c
4 4 d
5 5 e

`-` 방법3: 벡터를 일단 만들고 티블로 변형

In [32]:
as_tibble(x)

  value
1 1
2 2
3 3
4 4
5 5

`-` 방법4: 매트릭스를 일단 만들고 티블로 변형

In [33]:
as_tibble(cbind(x,y))

  x y
1 1 a
2 2 b
3 3 c
4 4 d
5 5 e

- 모두 chr로 저장되는 단점이 있음!

`-` 방법5: 리스트에서 생성

In [50]:
as_tibble(list(x=x,y=y))

  x y
1 1 a
2 2 b
3 3 c
4 4 d
5 5 e

`-` 데이터프레임의 경우도 티블과 비슷하게 만들 수 있다.

In [34]:
data.frame(v1=1:3,v2=c(T,F,T), v3=c("a","b","c")) # 방법1

  v1 v2    v3
1 1   TRUE a
2 2  FALSE b
3 3   TRUE c

In [35]:
data.frame(x,y) # 방법2

  x y
1 1 a
2 2 b
3 3 c
4 4 d
5 5 e

In [36]:
data.frame(x) # 방법3

  x
1 1
2 2
3 3
4 4
5 5

In [37]:
data.frame(cbind(x,y)) # 방법4

  x y
1 1 a
2 2 b
3 3 c
4 4 d
5 5 e

In [51]:
data.frame(list(x=x,y=y)) # 방법5

  x y
1 1 a
2 2 b
3 3 c
4 4 d
5 5 e

`-` tibble()과 data.frame()이 항상 같은 결과를 주는 것은 아님

In [57]:
lst= list(x=x,y=y,z=cbind(x,y))
lst

$x
[1] 1 2 3 4 5

$y
[1] "a" "b" "c" "d" "e"

$z
     x   y
[1,] "1" "a"
[2,] "2" "b"
[3,] "3" "c"
[4,] "4" "d"
[5,] "5" "e"

In [58]:
as_tibble(lst)

  x y z
1 1 a 1, a
2 2 b 2, b
3 3 c 3, c
4 4 d 4, d
5 5 e 5, e

In [59]:
data.frame(lst)

  x y z.x z.y
1 1 a 1   a
2 2 b 2   b
3 3 c 3   c
4 4 d 4   d
5 5 e 5   e

`-` 데이터프레임과 티블은 as_tibble()과 data.frame()을 이용해 서로의 형태로 변화가능하다.

In [38]:
data.frame(v1=1:3,v2=c(T,F,T), v3=c("a","b","c"))

  v1 v2    v3
1 1   TRUE a
2 2  FALSE b
3 3   TRUE c

In [39]:
data.frame(v1=1:3,v2=c(T,F,T), v3=c("a","b","c")) %>% as_tibble

  v1 v2    v3
1 1   TRUE a
2 2  FALSE b
3 3   TRUE c

In [40]:
data.frame(v1=1:3,v2=c(T,F,T), v3=c("a","b","c")) %>% as_tibble %>% data.frame

  v1 v2    v3
1 1   TRUE a
2 2  FALSE b
3 3   TRUE c

즉 아래가 가능함

In [41]:
df=data.frame(v1=1:3,v2=c(T,F,T), v3=c("a","b","c")) 
df

  v1 v2    v3
1 1   TRUE a
2 2  FALSE b
3 3   TRUE c

In [43]:
df=as_tibble(df)
df

  v1 v2    v3
1 1   TRUE a
2 2  FALSE b
3 3   TRUE c

In [44]:
df=data.frame(df)
df

  v1 v2    v3
1 1   TRUE a
2 2  FALSE b
3 3   TRUE c

### 데이터프레임, 티블의 해석

`-` 매트릭스: (1) 모든 열은 동일한 숫자의 row를 가져야하며 (2) 행렬의 모든 원소는 동일한 자료형을 가져야 한다.

`-` 리스트: (1) 모든 원소는 동일한 길이의 벡터로 구성될 필요가 없다. (애초에 모든 원소가 벡터일 이유도 없어요!) (2) 그리고 각 원소가 동일한 자료형을 가질 필요도 없다.

`-` 티블 혹은 데이터프레임은 

- 자료형이 자유로운 매트릭스로 해석할 수 있고 
- 모든 원소가 동일한 길이의 벡터로 구성된 리스트

로 생각할 수 있다.

### 데이터프레임과 티블 기본사용법

`-` 데이터 셋팅

In [65]:
x= 1:3
y= c(T,F,T)
z= c("a","b","c")

lst = list(x=x,y=y,z=z)
mat = cbind(x,y,z)
df = tibble(x=x,y=y,z=z)

In [68]:
print(lst)
print(mat)
print(df)

$x
[1] 1 2 3

$y
[1]  TRUE FALSE  TRUE

$z
[1] "a" "b" "c"

     x   y       z
[1,] "1" "TRUE"  "a"
[2,] "2" "FALSE" "b"
[3,] "3" "TRUE"  "c"
# A tibble: 3 × 3
      x y     z
  <int> <lgl> <chr>
1     1 TRUE  a
2     2 FALSE b
3     3 TRUE  c

`-` df에서 열들의 이름을 알고 싶다?

In [73]:
print(colnames(lst))
print(colnames(mat))
print(colnames(df))

NULL
[1] "x" "y" "z"
[1] "x" "y" "z"

In [74]:
print(names(lst))
print(names(mat))
print(names(df))

[1] "x" "y" "z"
NULL
[1] "x" "y" "z"