# (노트) purrr 
> 작성완료 

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- categories: [R]

### About this doc

`-` purrr

### Lib

In [1]:
library(tidyverse)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.3     ✔ purrr   0.3.4
✔ tibble  3.1.1     ✔ dplyr   1.0.5
✔ tidyr   1.1.3     ✔ stringr 1.4.0
✔ readr   1.4.0     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

### map_dbl, map_int, map_chr, map_lgl: list(a=1:5, b:1:30) $\to$ list(fun(a),fun(b))

`-` data

In [2]:
df <- tibble(
  a = rnorm(10),
  b = rnorm(10),
  c = rnorm(10),
  d = rnorm(10)
)
print(df)

# A tibble: 10 x 4
         a       b        c      d
     <dbl>   <dbl>    <dbl>  <dbl>
 1 -0.882  -0.267  -0.00829 -2.45
 2  1.53    1.51   -0.624   -0.383
 3 -1.33    1.97   -0.505    1.48
 4  0.987  -0.418  -1.47    -0.219
 5 -0.800   1.40   -0.451    0.260
 6  1.57    0.801  -2.12     0.845
 7  0.0990 -0.475   0.0639   1.00
 8  0.101   0.644  -0.782    0.697
 9  1.22    0.0471  0.432    0.423
10  1.73    0.509  -0.953   -0.984

#### use1

In [5]:
map_dbl(df, mean) %>% print()
map_dbl(df, median) %>% print()
map_dbl(df, sd) %>% print()

          a           b           c           d
 0.42218821  0.57159037 -0.64167193  0.06686763
         a          b          c          d
 0.5441529  0.5766656 -0.5644257  0.3419035
        a         b         c         d
1.1404138 0.8579740 0.7526226 1.1422112

`-` 결과는 벡터로 나온다. (벡터는 길이가 4이고 각 원소마다 a,b,c,d 라는 이름이 있음)

`-` 결과가 벡터이므로 아래와 같은 연산이 가능함

In [13]:
print(map_dbl(df, mean) + 1 )

        a         b         c         d
1.4221882 1.5715904 0.3583281 1.0668676

`-` 아래와 같이 각 원소에 이름이 있는 벡터를 선언할 수 있음.

In [15]:
c(a=1.1,b=2.2,c=3.3,d=4.4) %>% print()

  a   b   c   d
1.1 2.2 3.3 4.4

`-` map_dbl()이 아니라 map()을 사용해도 좋음. 단지 결과가 리스트로 나옴

In [17]:
map(df,mean) %>% print()

$a
[1] 0.4221882

$b
[1] 0.5715904

$c
[1] -0.6416719

$d
[1] 0.06686763

In [18]:
map(df,median) %>% print()

$a
[1] 0.5441529

$b
[1] 0.5766656

$c
[1] -0.5644257

$d
[1] 0.3419035

In [19]:
map(df,sd) %>% print()

$a
[1] 1.140414

$b
[1] 0.857974

$c
[1] 0.7526226

$d
[1] 1.142211

#### use2

In [7]:
df %>% map_dbl(mean)
df %>% map_dbl(median)
df %>% map_dbl(sd)

          a           b           c           d
-0.01499685  0.32609079 -0.54987837 -0.17796258

          a           b           c           d
-0.03043249  0.31130958 -0.40458600 -0.21319741

        a         b         c         d
0.7406295 0.6817528 1.3134598 0.9258914

#### use3: map_dbl은 additional arguments 를 전달할 수 있다.

In [12]:
mean(c(0,0,0,1,1,1,1,1))
mean(c(0,0,0,1,1,1,1,1),trim=0.5)

[1] 0.625

[1] 1

In [13]:
map_dbl(df, mean, trim = 0.5)

          a           b           c           d
-0.03043249  0.31130958 -0.40458600 -0.21319741

#### use4

In [20]:
z <- list(x = 1:3, y = 4:50)
z
map_dbl(z, length)

$x
[1] 1 2 3

$y
 [1]  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
[26] 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50

 x  y
 3 47

In [42]:
map(z, length)

$x
[1] 3

$y
[1] 47

In [40]:
map_dbl(z, mean)

 x  y
 2 27

In [41]:
map(z, mean)

$x
[1] 2

$y
[1] 27

#### use5

In [25]:
mtcars

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [26]:
mtcars %>% split(.$cyl)

$`4`
                mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Datsun 710     22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Merc 240D      24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230       22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Fiat 128       32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1
Honda Civic    30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2
Toyota Corolla 33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1
Toyota Corona  21.5   4 120.1  97 3.70 2.465 20.01  1  0    3    1
Fiat X1-9      27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1
Porsche 914-2  26.0   4 120.3  91 4.43 2.140 16.70  0  1    5    2
Lotus Europa   30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2
Volvo 142E     21.4   4 121.0 109 4.11 2.780 18.60  1  1    4    2

$`6`
                mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4      21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag  21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Hornet 4 Drive 21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Valiant        18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Merc 280       19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4
Merc 280C      17.8   6 167.6 123 3.92 3.440 18.90  1  0    4    4
Ferrari Dino   19.7   6 145.0 175 3.62 2.770 15.50  0  1    5    6

$`8`
                     mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Hornet Sportabout   18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Duster 360          14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 450SE          16.4   8 275.8 180 3.07 4.070 17.40  0  0    3    3
Merc 450SL          17.3   8 275.8 180 3.07 3.730 17.60  0  0    3    3
Merc 450SLC         15.2   8 275.8 180 3.07 3.780 18.00  0  0    3    3
Cadillac Fleetwood  10.4   8 472.0 205 2.93 5.250 17.98  0  0    3    4
Lincoln Continental 10.4   8 460.0 215 3.00 5.424 17.82  0  0    3    4
Chrysler Imperial   14.7   8 440.0 230 3.23 5.345 17.42  0  0    3    4
Dodge Challenger    15.5   8 318.0 150 2.76 3.520 16.87  0  0    3    2
AMC Javelin         15.2   8 304.0 150 3.15 3.435 17.30  0  0    3    2
Camaro Z28          13.3   8 350.0 245 3.73 3.840 15.41  0  0    3    4
Pontiac Firebird    19.2   8 400.0 175 3.08 3.845 17.05  0  0    3    2
Ford Pantera L      15.8   8 351.0 264 4.22 3.170 14.50  0  1    5    4
Maserati Bora       15.0   8 301.0 335 3.54 3.570 14.60  0  1    5    8

In [38]:
mtcars %>% split(.$cyl) %>% map(function(df) lm(mpg ~ wt, data = df))

$`4`

Call:
lm(formula = mpg ~ wt, data = df)

Coefficients:
(Intercept)           wt
     39.571       -5.647


$`6`

Call:
lm(formula = mpg ~ wt, data = df)

Coefficients:
(Intercept)           wt
      28.41        -2.78


$`8`

Call:
lm(formula = mpg ~ wt, data = df)

Coefficients:
(Intercept)           wt
     23.868       -2.192

In [31]:
mtcars %>% split(.$cyl) %>% map(~lm(mpg ~ wt, data = .))

$`4`

Call:
lm(formula = mpg ~ wt, data = .)

Coefficients:
(Intercept)           wt
     39.571       -5.647


$`6`

Call:
lm(formula = mpg ~ wt, data = .)

Coefficients:
(Intercept)           wt
      28.41        -2.78


$`8`

Call:
lm(formula = mpg ~ wt, data = .)

Coefficients:
(Intercept)           wt
     23.868       -2.192

In [33]:
mtcars %>% split(.$cyl) %>% map(~lm(mpg ~ wt, data = .)) %>% 
  map(summary)

$`4`

Call:
lm(formula = mpg ~ wt, data = .)

Residuals:
    Min      1Q  Median      3Q     Max
-4.1513 -1.9795 -0.6272  1.9299  5.2523

Coefficients:
            Estimate Std. Error t value Pr(>|t|)
(Intercept)   39.571      4.347   9.104 7.77e-06 ***
wt            -5.647      1.850  -3.052   0.0137 *
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 3.332 on 9 degrees of freedom
Multiple R-squared:  0.5086,	Adjusted R-squared:  0.454
F-statistic: 9.316 on 1 and 9 DF,  p-value: 0.01374


$`6`

Call:
lm(formula = mpg ~ wt, data = .)

Residuals:
     Mazda RX4  Mazda RX4 Wag Hornet 4 Drive        Valiant       Merc 280
       -0.1250         0.5840         1.9292        -0.6897         0.3547
     Merc 280C   Ferrari Dino
       -1.0453        -1.0080

Coefficients:
            Estimate Std. Error t value Pr(>|t|)
(Intercept)   28.409      4.184   6.789  0.00105 **
wt            -2.780      1.335  -2.083  0.09176 .
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 1.165 on 5 degrees of freedom
Multiple R-squared:  0.4645,	Adjusted R-squared:  0.3574
F-statistic: 4.337 on 1 and 5 DF,  p-value: 0.09176


$`8`

Call:
lm(formula = mpg ~ wt, data = .)

Residuals:
    Min      1Q  Median      3Q     Max
-2.1491 -1.4664 -0.8458  1.5711  3.7619

Coefficients:
            Estimate Std. Error t value Pr(>|t|)
(Intercept)  23.8680     3.0055   7.942 4.05e-06 ***
wt           -2.1924     0.7392  -2.966   0.0118 *
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 2.024 on 12 degrees of freedom
Multiple R-squared:  0.423,	Adjusted R-squared:  0.3749
F-statistic: 8.796 on 1 and 12 DF,  p-value: 0.01179

In [36]:
mtcars %>% split(.$cyl) %>% map(~lm(mpg ~ wt, data = .)) %>% 
  map(summary) %>% map_dbl(~.$r.squared)

        4         6         8
0.5086326 0.4645102 0.4229655