# (노트) 판다스 - 행선택 

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- hide: false
- categories: [파이썬]

### import

In [2]:
import numpy as np
import pandas as pd

### 첫번째 행을 선택하는 방법

In [204]:
dic={'X1':np.random.normal(0,1,5), 
     'X2':np.random.normal(0,1,5),
     'X3':np.random.normal(0,1,5),
     'X4':np.random.normal(0,1,5),
     'X5':np.random.normal(0,1,5),  
     'X6':np.random.normal(0,1,5)
    }
df1=pd.DataFrame(dic)
df1

         X1        X2        X3        X4        X5        X6
0  0.449326 -1.340404 -0.254330 -0.971849  0.407148 -0.615758
1  0.287723  0.445965  1.171644 -1.393476 -0.128202 -0.591189
2  0.675554  2.437100 -0.318418  1.221115  1.169011 -0.015953
3  0.743230  0.666278  0.821528  0.405328  1.733926 -0.024356
4 -0.322457  1.583010  1.661233 -1.814506  0.302469  0.997066

`-` 방법1

In [205]:
df1.iloc[0] # 이상해

X1    0.449326
X2   -1.340404
X3   -0.254330
X4   -0.971849
X5    0.407148
X6   -0.615758
Name: 0, dtype: float64

`-` 방법2

In [206]:
df1.iloc[0,:]

X1    0.449326
X2   -1.340404
X3   -0.254330
X4   -0.971849
X5    0.407148
X6   -0.615758
Name: 0, dtype: float64

`-` 방법3

In [207]:
df1.iloc[[0]]

         X1        X2       X3        X4        X5        X6
0  0.449326 -1.340404 -0.25433 -0.971849  0.407148 -0.615758

`-` 방법4

In [208]:
df1.iloc[[0],:]

         X1        X2       X3        X4        X5        X6
0  0.449326 -1.340404 -0.25433 -0.971849  0.407148 -0.615758

`-` 방법5

In [209]:
df1.loc[0]

X1    0.449326
X2   -1.340404
X3   -0.254330
X4   -0.971849
X5    0.407148
X6   -0.615758
Name: 0, dtype: float64

`-` 방법6

In [210]:
df1.loc[0,:]

X1    0.449326
X2   -1.340404
X3   -0.254330
X4   -0.971849
X5    0.407148
X6   -0.615758
Name: 0, dtype: float64

`-` 방법7

In [211]:
df1.loc[[0]]

         X1        X2       X3        X4        X5        X6
0  0.449326 -1.340404 -0.25433 -0.971849  0.407148 -0.615758

`-` 방법8

In [212]:
df1.loc[[0],:]

         X1        X2       X3        X4        X5        X6
0  0.449326 -1.340404 -0.25433 -0.971849  0.407148 -0.615758

`-` 방법9

In [213]:
df1.loc[[True,False,False,False,False],:]

         X1        X2       X3        X4        X5        X6
0  0.449326 -1.340404 -0.25433 -0.971849  0.407148 -0.615758

`-` 방법10

In [214]:
df1.loc[[True,False,False,False,False]]

         X1        X2       X3        X4        X5        X6
0  0.449326 -1.340404 -0.25433 -0.971849  0.407148 -0.615758

`-` 방법11

In [215]:
df1.iloc[[True,False,False,False,False],:]

         X1        X2       X3        X4        X5        X6
0  0.449326 -1.340404 -0.25433 -0.971849  0.407148 -0.615758

`-` 방법12

In [216]:
df1.iloc[[True,False,False,False,False]]

         X1        X2       X3        X4        X5        X6
0  0.449326 -1.340404 -0.25433 -0.971849  0.407148 -0.615758

### 여러개의 1,3행을 선택하는 방법

`-` 방법1

In [177]:
df.loc[[0,2],:]

         X1        X2        X3        X4        X5        X6
0 -1.852014  0.470273  0.718961  2.605273 -1.518844  0.303483
2 -0.082570  0.252466 -1.755272  0.555258 -0.719960 -1.831031

`-` 방법2

In [178]:
df.iloc[[0,2],:]

         X1        X2        X3        X4        X5        X6
0 -1.852014  0.470273  0.718961  2.605273 -1.518844  0.303483
2 -0.082570  0.252466 -1.755272  0.555258 -0.719960 -1.831031

`-` 불인덱싱, 슬라이싱도 가능함. (이것들은 생략할게요~)

#### loc vs iloc ??

`-` 위의 경우는 row의 인덱스이름이 정수인 경우임

`-` 정수가 아닌 경우

In [220]:
_df= pd.DataFrame({'A':[1,2,3],'B':[4,5,6]},index=list('abc'))
_df

   A  B
a  1  4
b  2  5
c  3  6

In [221]:
_df.loc[['a','b'],:]

   A  B
a  1  4
b  2  5

In [222]:
_df.iloc[[0,1],:]

   A  B
a  1  4
b  2  5

`-` 대부분의 경우 obervatio에 특정한 이름이 있는 경우는 없으므로 loc이 그다지 쓸모 없음

`-` 그렇지만 특정 경우에는 쓸모 있음

In [223]:
_df=pd.DataFrame(np.random.randn(20,4),columns=list('ABCD'),index=pd.date_range('20201225',periods=20))
_df

                   A         B         C         D
2020-12-25 -0.359752  0.521507  0.280662  0.907407
2020-12-26  0.210061  1.285977 -1.540000  0.735020
2020-12-27  0.846027  0.693259  1.865635  0.944089
2020-12-28  0.747401  1.133861  0.861790  0.559377
2020-12-29  0.750016 -1.276119 -1.112284 -0.820795
2020-12-30 -0.612230  0.965399  0.849743  0.568011
2020-12-31  0.626535 -1.008876  1.385723 -0.280979
2021-01-01  0.728509  0.890507 -1.234721 -0.923866
2021-01-02 -0.909982 -0.635628 -0.529984  0.463975
2021-01-03 -0.543736 -0.625050  0.606186 -0.785445
2021-01-04 -0.368165 -1.754367  0.569304 -0.022941
2021-01-05 -1.400423 -0.485507  1.066330 -0.336971
2021-01-06 -2.783235 -1.850748  0.587250 -1.087506
2021-01-07  0.117771 -0.196555  0.554328 -0.628978
2021-01-08 -0.667862  0.586774 -0.385894 -0.572318
2021-01-09 -0.422079 -1.567576  0.855075 -0.350744
2021-01-10  1.544884  2.150816 -0.217486 -0.439209
2021-01-11 -0.738083 -2.559839 -0.288263  1.437569
2021-01-12 -1.303355 -0.293737  0.817323 -1.925663
2021-01-13 -0.687083  0.324115 -0.321932 -0.255650

`-` 1월5일부터 1월8일까지 자료만 보고 싶다!

In [224]:
_df.loc['20210105':'20210108']

                   A         B         C         D
2021-01-05 -1.400423 -0.485507  1.066330 -0.336971
2021-01-06 -2.783235 -1.850748  0.587250 -1.087506
2021-01-07  0.117771 -0.196555  0.554328 -0.628978
2021-01-08 -0.667862  0.586774 -0.385894 -0.572318

`-` iloc으로 하려면 힘들다..

In [225]:
_df.index

DatetimeIndex(['2020-12-25', '2020-12-26', '2020-12-27', '2020-12-28',
               '2020-12-29', '2020-12-30', '2020-12-31', '2021-01-01',
               '2021-01-02', '2021-01-03', '2021-01-04', '2021-01-05',
               '2021-01-06', '2021-01-07', '2021-01-08', '2021-01-09',
               '2021-01-10', '2021-01-11', '2021-01-12', '2021-01-13'],
              dtype='datetime64[ns]', freq='D')

In [226]:
pd.Series(_df.index)

0    2020-12-25
1    2020-12-26
2    2020-12-27
3    2020-12-28
4    2020-12-29
5    2020-12-30
6    2020-12-31
7    2021-01-01
8    2021-01-02
9    2021-01-03
10   2021-01-04
11   2021-01-05
12   2021-01-06
13   2021-01-07
14   2021-01-08
15   2021-01-09
16   2021-01-10
17   2021-01-11
18   2021-01-12
19   2021-01-13
dtype: datetime64[ns]

In [227]:
_df.iloc[11:15] # 14으로하면 안된다. 마지막 인덱스가 포함되지 않으니까!

                   A         B         C         D
2021-01-05 -1.400423 -0.485507  1.066330 -0.336971
2021-01-06 -2.783235 -1.850748  0.587250 -1.087506
2021-01-07  0.117771 -0.196555  0.554328 -0.628978
2021-01-08 -0.667862  0.586774 -0.385894 -0.572318

#### 자주하는 실수

`-` 나는 아래와 같은 실수를 많이함

In [228]:
_df.loc['A']

KeyError: 'A'

`-` 올바른 방법

In [229]:
_df['A']

2020-12-25   -0.359752
2020-12-26    0.210061
2020-12-27    0.846027
2020-12-28    0.747401
2020-12-29    0.750016
2020-12-30   -0.612230
2020-12-31    0.626535
2021-01-01    0.728509
2021-01-02   -0.909982
2021-01-03   -0.543736
2021-01-04   -0.368165
2021-01-05   -1.400423
2021-01-06   -2.783235
2021-01-07    0.117771
2021-01-08   -0.667862
2021-01-09   -0.422079
2021-01-10    1.544884
2021-01-11   -0.738083
2021-01-12   -1.303355
2021-01-13   -0.687083
Freq: D, Name: A, dtype: float64

- 이런방식이 사실 좀 이상해보여서 한번쓰기 시작하면 잘쓰는데 금방까먹고 다시 헷갈림

`-` 아래의 사실을 기억하자. 
- 기본적으로 loc, iloc은 `[2], [2:]` 처럼 1차원으로 원소를 인덱싱할수도 있고, `[2,3], [:,2]`와 같이 2차원으로 인덱싱 할수도 있다. 
- 1차원으로 인덱싱하는 경우는 기본적으로 행을 인덱싱한다. $\to$ **loc, iloc은 행과 더 친하고 열과 친하지 않다.**
- 따라서 열을 선택하는 방법에 있어서 loc, iloc이 그렇게 친화적인 방법은 아니다. 
- 그렇지만 달리 열을 선택하는 쉬운 방법이 존재하지 않아서 열을 선택할때에도 loc, iloc이 선호된다.

### 슬라이싱응용

In [230]:
_df=pd.DataFrame(np.random.randn(10,4),columns=list('ABCD'),index=pd.date_range('20210101',periods=10))
_df.iloc[::2]

                   A         B         C         D
2021-01-01 -1.361026 -0.522299  0.792276  1.074594
2021-01-03  2.813564  1.495976  1.545519 -1.691953
2021-01-05 -0.802702 -0.384998 -0.418294 -0.329850
2021-01-07 -1.002307  0.010978 -0.096056 -0.992631
2021-01-09 -1.531024  0.450450  0.601330  0.169163

#### 이것은 칼럼에도 적용가능 $\to$ 그런데 잘 쓰지 않음

In [232]:
_df.iloc[:,::2]

                   A         C
2021-01-01 -1.361026  0.792276
2021-01-02  0.391679 -0.571396
2021-01-03  2.813564  1.545519
2021-01-04  1.833291 -0.538719
2021-01-05 -0.802702 -0.418294
2021-01-06  0.906382  1.068642
2021-01-07 -1.002307 -0.096056
2021-01-08  0.899889 -1.083999
2021-01-09 -1.531024  0.601330
2021-01-10 -1.182769 -0.085093

**잘 쓰지 않는 이유?**
- row를 특정 간격으로 뽑는 일은 빈번함 (예를들어 일별데이터를 주별데이터로 바꾸고 싶을 경우?) 
- col을 특정 간격으로 뽑아야 하는 일은 없음.

### lambda + map

In [233]:
df2 = pd.DataFrame(np.random.normal(size=(10,4)),columns=list('ABCD'))
df2

          A         B         C         D
0  1.847747 -0.135137  0.270376 -0.184955
1 -0.752069  1.343118  1.544871  0.174940
2 -0.450088 -0.173808 -0.327113  2.152646
3  1.704047 -2.370501  0.139030 -0.964231
4  1.181108  0.758522 -0.571636 -0.905563
5 -0.733437 -0.357610  1.101668 -0.494430
6  1.704264 -0.511046 -0.802806 -1.856951
7 -1.059690 -1.947002 -1.075315 -0.744245
8  1.778361  0.444605  1.515776 -0.388332
9 -0.220174 -1.248556  0.999474  1.180490

#### 컬럼A의 값이 0보다 큰 경우만

`-` 방법1

In [234]:
df2.loc[map(lambda x: x>0, df['A']),:]

          A         B         C         D
0  1.847747 -0.135137  0.270376 -0.184955
5 -0.733437 -0.357610  1.101668 -0.494430
7 -1.059690 -1.947002 -1.075315 -0.744245

`-` 방법2

In [235]:
df2.loc[lambda df: df['A']>0, : ]

          A         B         C         D
0  1.847747 -0.135137  0.270376 -0.184955
3  1.704047 -2.370501  0.139030 -0.964231
4  1.181108  0.758522 -0.571636 -0.905563
6  1.704264 -0.511046 -0.802806 -1.856951
8  1.778361  0.444605  1.515776 -0.388332

- ?? 
- map의 기능은 (1) 리스트의 원소별로 (2) 함수를 적용하여 아웃풋을 구하고 (3) 나온 각각의 결과를 다시 하나의 리스트로 묶는 역할 
- 우리는 이중에서 (1), (3)에만 집중했음
- 하지만 생각해보면 일단 (2) 일단함수를 적용하는 기능이 있었음 
- **그런데 위의 코드를 보면 함수를 적용한 결과가 아니라 함수오브젝트 자체를 전달하여도 동작함**

***요약!!***
- True, False 로 이루어진 벡터를 리스트의 형태로 전달하여 인덱싱하면 당연히 가능 (원래 아는거) 
- True, False 로 이루어진 벡터로 포함된 리스트를 리턴할 수 있는 함수자체를 전달하여도 인덱싱 가능

`-` 방법3

In [236]:
df2.iloc[map(lambda x: x>0, df['A']),:]

          A         B         C         D
0  1.847747 -0.135137  0.270376 -0.184955
5 -0.733437 -0.357610  1.101668 -0.494430
7 -1.059690 -1.947002 -1.075315 -0.744245

`-` 방법4: 실패

In [237]:
df2.iloc[lambda df: df['A']>0,:]

NotImplementedError: iLocation based boolean indexing on an integer type is not available

- 위에서.. iloc을 loc으로 바꾸면 되는데.. 
- iloc입장에서 조금 서운하다..

#### 칼럼A>0 이고  칼럼B<0 인 경우

`-` 방법1

In [238]:
df2.loc[map(lambda x,y: x>0 and y<0, df['A'],df['B']),:]

          A        B         C        D
5 -0.733437 -0.35761  1.101668 -0.49443

`-` 방법2

In [248]:
df2.loc[map(lambda x,y: x>0 & y<0, df['A'],df['B']),:]

TypeError: unsupported operand type(s) for &: 'int' and 'float'

- ??? 아래를 관찰

***보충학습***

In [244]:
0<3.2 & 0<2.2

TypeError: unsupported operand type(s) for &: 'float' and 'int'

In [245]:
(0<3.2) & (0<2.2)

True

***보충학습끝***

아래와 같이 수정하면 잘 된다.

In [246]:
df2.loc[map(lambda x,y: (x>0) & (y<0), df['A'],df['B']),:]

          A        B         C        D
5 -0.733437 -0.35761  1.101668 -0.49443

`-` 방법3: 실패

In [240]:
df2.loc[lambda df: (df['A']>0) and (df['B']<0),:]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

- and는 벡터연산지원불가능

***보충학습***

In [241]:
np.array([True,False]) and np.array([True,False])

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [242]:
np.array([True,False]) & np.array([True,False])

array([ True, False])

***보충학습끝***

`-` 방법4

In [249]:
df2.loc[lambda df: (df['A']>0) & (df['B']<0),:]

          A         B         C         D
0  1.847747 -0.135137  0.270376 -0.184955
3  1.704047 -2.370501  0.139030 -0.964231
6  1.704264 -0.511046 -0.802806 -1.856951

`-` iloc을 이용한 것은 생략

### query

#### 컬럼A>0, 컬럼B<0 인 경우 선택

`-` 방법1

In [253]:
df2.query('A>0 & B<0')

          A         B         C         D
0  1.847747 -0.135137  0.270376 -0.184955
3  1.704047 -2.370501  0.139030 -0.964231
6  1.704264 -0.511046 -0.802806 -1.856951

`-` 방법2

In [254]:
df2.query('A>0 and B<0')

          A         B         C         D
0  1.847747 -0.135137  0.270376 -0.184955
3  1.704047 -2.370501  0.139030 -0.964231
6  1.704264 -0.511046 -0.802806 -1.856951

#### A<B<C 를 필터

In [255]:
df2

          A         B         C         D
0  1.847747 -0.135137  0.270376 -0.184955
1 -0.752069  1.343118  1.544871  0.174940
2 -0.450088 -0.173808 -0.327113  2.152646
3  1.704047 -2.370501  0.139030 -0.964231
4  1.181108  0.758522 -0.571636 -0.905563
5 -0.733437 -0.357610  1.101668 -0.494430
6  1.704264 -0.511046 -0.802806 -1.856951
7 -1.059690 -1.947002 -1.075315 -0.744245
8  1.778361  0.444605  1.515776 -0.388332
9 -0.220174 -1.248556  0.999474  1.180490

In [256]:
df2.query('A<B<C')

          A         B         C        D
1 -0.752069  1.343118  1.544871  0.17494
5 -0.733437 -0.357610  1.101668 -0.49443

#### A>mean(A) 선택: query외부변수 사용

`-` 방법1

In [260]:
np.mean(df2.A)

0.5000069099552247

In [261]:
df2.query('A>0.5000069099552247')

          A         B         C         D
0  1.847747 -0.135137  0.270376 -0.184955
3  1.704047 -2.370501  0.139030 -0.964231
4  1.181108  0.758522 -0.571636 -0.905563
6  1.704264 -0.511046 -0.802806 -1.856951
8  1.778361  0.444605  1.515776 -0.388332

`-` 방법2

In [266]:
mean_of_A=np.mean(df2.A)

In [267]:
df2.query('A > @mean_of_A')

          A         B         C         D
0  1.847747 -0.135137  0.270376 -0.184955
3  1.704047 -2.370501  0.139030 -0.964231
4  1.181108  0.758522 -0.571636 -0.905563
6  1.704264 -0.511046 -0.802806 -1.856951
8  1.778361  0.444605  1.515776 -0.388332

#### A>mean(A) 이고 A<1.8 인것을 선택

`-` 방법1

In [270]:
df2.query('A >  @mean_of_A and A<1.8')

          A         B         C         D
3  1.704047 -2.370501  0.139030 -0.964231
4  1.181108  0.758522 -0.571636 -0.905563
6  1.704264 -0.511046 -0.802806 -1.856951
8  1.778361  0.444605  1.515776 -0.388332

`-` 방법2 (가독성)

In [286]:
df2.query(
    " A >  @mean_of_A" 
    " and A<1.8"
)

          A         B         C         D
3  1.704047 -2.370501  0.139030 -0.964231
4  1.181108  0.758522 -0.571636 -0.905563
6  1.704264 -0.511046 -0.802806 -1.856951
8  1.778361  0.444605  1.515776 -0.388332

`-` 아래는 에러발생 (왜??)

In [287]:
df2.query(
    "A >  @mean_of_A" 
    "and A<1.8"
)

SyntaxError: invalid syntax (<unknown>, line 1)