# (노트) 판다스 - 칼럼변환 혹은 칼럼연산

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- categories: [파이썬]

### import

In [246]:
import pandas as pd
import numpy as np

### 컬럼추가

In [209]:
df=pd.DataFrame({'X1':[1,2,3,4,5],'X2':[2,3,4,5,6]})
df

   X1  X2
0   1   2
1   2   3
2   3   4
3   4   5
4   5   6

`-` 새로운 칼럼 [3,3,3,3,3]을 추가하자.

In [210]:
df.assign(X3=[3,3,3,3,3]) ## 계산결과

   X1  X2  X3
0   1   2   3
1   2   3   3
2   3   4   3
3   4   5   3
4   5   6   3

In [211]:
df ## 원래 자료는 변화하지 않음

   X1  X2
0   1   2
1   2   3
2   3   4
3   4   5
4   5   6

In [212]:
df= df.assign(X3=[3,3,3,3,3]) ## 계산결과를 update

In [213]:
df

   X1  X2  X3
0   1   2   3
1   2   3   3
2   3   4   3
3   4   5   3
4   5   6   3

`-` 같은이름일경우?

In [214]:
df.assign(X2=[2,2,2,2,2]) ## 덮어씌워진다.

   X1  X2  X3
0   1   2   3
1   2   2   3
2   3   2   3
3   4   2   3
4   5   2   3

In [215]:
df ## 역시 저장되지는 않음.

   X1  X2  X3
0   1   2   3
1   2   3   3
2   3   4   3
3   4   5   3
4   5   6   3

`-` 길이가 다른것을 추가할수는 없다.

In [216]:
df.assign(X4=[3,3,3,3,3,5,5,5])

ValueError: Length of values (8) does not match length of index (5)

`-` 2개를 추가할 수 있다.

In [217]:
df.assign(X4=[4,4,4,4,4],X5=[5,5,5,5,5])

   X1  X2  X3  X4  X5
0   1   2   3   4   5
1   2   3   3   4   5
2   3   4   3   4   5
3   4   5   3   4   5
4   5   6   3   4   5

`-` 참고로 이것은 아래처럼 연달아 추가하는것과 같은 결과임

In [218]:
df.assign(X4=[4,4,4,4,4]).assign(X5=[5,5,5,5,5])

   X1  X2  X3  X4  X5
0   1   2   3   4   5
1   2   3   3   4   5
2   3   4   3   4   5
3   4   5   3   4   5
4   5   6   3   4   5

`-` 연산의 결과를 추가하는 방법

In [219]:
df

   X1  X2  X3
0   1   2   3
1   2   3   3
2   3   4   3
3   4   5   3
4   5   6   3

In [262]:
df.assign(X4=df.X3+1)

   X1  X2  X3  X4
0   1   2   3   4
1   2   3   3   4
2   3   4   3   4
3   4   5   3   4
4   5   6   3   4

`-` 아래와 같이 쓸 수 없다.

In [263]:
df.assign(X4=X3+1)

NameError: name 'X3' is not defined

In [ ]:
`-` 아

In [222]:
df.assign(X4=df.X3+1,X5=df.X4+1)

AttributeError: 'DataFrame' object has no attribute 'X4'

`-` 연쇄적으로 해도 불가능

In [223]:
df.assign(X4=df.X3+1).assign(X5=df.X4+1)

AttributeError: 'DataFrame' object has no attribute 'X4'

`-` 아래와 같이 해야함

In [256]:
df.eval(
    '''
    X4=X3+1
    X5=X4+1
    X6=X5-3
    ''')

   X1  X2  X3  X4  X5  X6
0   1   2   3   4   5   2
1   2   3   3   4   5   2
2   3   4   3   4   5   2
3   4   5   3   4   5   2
4   5   6   3   4   5   2

- 엔터가 엄청 큰 역할을 한다.

`-` 좀 더 복잡한 함수일 경우는?

`-` 방법1

In [269]:
f= lambda x: (x-np.mean(x))/np.std(x)

In [270]:
f(df.X1)

0   -1.414214
1   -0.707107
2    0.000000
3    0.707107
4    1.414214
Name: X1, dtype: float64

In [271]:
df.assign(X4=f(df.X1))

   X1  X2  X3        X4
0   1   2   3 -1.414214
1   2   3   3 -0.707107
2   3   4   3  0.000000
3   4   5   3  0.707107
4   5   6   3  1.414214

`-` 방법2

In [319]:
df.assign(X4= lambda df: (df.X1-np.mean(df.X1))/np.std(df.X1))

   X1  X2  X3        X4
0   1   2   3 -1.414214
1   2   3   3 -0.707107
2   3   4   3  0.000000
3   4   5   3  0.707107
4   5   6   3  1.414214

In [326]:
def f(x):
    if x<2: 
        y=2
    elif x<4:
        y=4
    else:
        y=6
    return y

In [334]:
df.assign(X4=list(map(f,df.X1)))

   X1  X2  X3  X4
0   1   2   3   2
1   2   3   3   4
2   3   4   3   4
3   4   5   3   6
4   5   6   3   6