# 2021년 1학기 파이썬입문 기말고사 
> 작성완료

- toc:false
- branch: master
- badges: false
- comments: false
- hide: false
- author: 최규빈
- categories: [파이썬입문]

### Note 

`-` 1~2는 동일하게 나옵니다. 

`-` 3은 몇문제가 추가될 예정입니다. 

`-` 시험문제에 대한 질문대응을 위하여 카카오톡 채널을 임시 운영합니다. 
 - 채널사용방법: (모바일) 카카오톡 -> 채팅 -> 상단의돋보기아이콘클릭 -> "전북대 파이썬" 으로 검색 -> "전북대학교 파이썬입문 (2021)" 친구추가 및 질문 
 - 채널운영시간: 13일 20:00~24:00 / 14일 06:00 ~ 10:00 
 - 질문범위: 문제에 대한 이해 + 간단한 코드 구현 질문가능

`-` 수정내용1: 대략 몇명정도 강화에 성공하겠는가? $\to$ 대략 몇명정도 +5강화상태에 있겠는가? 
    
`-` 수정내용2: 단, 모든 유저가 62번의 강화시도를 하였다고 가정하자 $\to$ 단, +5강화에 성공하지 못한 모든 유저는 반드시 하루에 한번 강화를 시도해야 한다고 가정하자.

`-` 수정내용3: 힌트중 `upgradetry` 변수명을 `attemptresult` 로 수정

`-` 수정내용4: 100명의 유저중 50명이상 강화에 성공하는 순간 모든 유저의 강화성공확률을 90%로 증가시킨다고 하자. $\to$ 100명의 유저중 50명이상의 유저가 +5 강화상태에 도달하는 순간 모든 유저의 강화성공확률을 90%로 증가시킨다고 하자.

`-` 수정내용5: 힌트내용에서 아래를 수정합니다. 
 - 강화성공상태를 기록하는 매트릭스 (0~9 사이의 값이 저장됨)" $\to$ "강화성공상태를 기록하는 매트릭스 (0~5 사이의 값이 저장됨)"
 - attemp 메소드 attempt 메소드로 수정 
 - 1번에서 강화(upgrade)될 수 있데 $\to$ 강화(upgrade)될 수 있는데 로 수정

### \# 1. (20점)
N사에서 게임유저들에게 여름방학 기념이벤트로 **진명왕의 집판검**이라는 이름의 아이템을 선물했다고 하자. **진명왕의 집판검**은 총 5회에 걸쳐서 강화(upgrade)될 수 있는데 강화의 성공확률은 10%라고 하자. 강화가 5번성공하면 더 이상 강화가 진행되지 않는다고 하자. (따라서 더 이상 강화시도를 하지 않아도 무방하다) 아래는 이 아이템에 강화를 진행하였을때 각 강화상태를 설명한 예시이다. 

|시도횟수|강화성공여부|강화상태|비고|
|:-:|:-:|:-:|:-|
|1|강화실패|+0 $\to$ +0|강화실패로 인하여 강화상태 변화없음 |
|2|강화성공|+0 $\to$ +1|강화성공으로 인한 강화상태 변화|
|3|강화실패|+1 $\to$ +1|강화실패로 인하여 강화상태 변화없음 |
|4|강화성공|+1 $\to$ +2|강화성공으로 인한 강화상태 변화|
|5|강화성공|+2 $\to$ +3|강화성공으로 인한 강화상태 변화|
|6|강화성공|+3 $\to$ +4|강화성공으로 인한 강화상태 변화|
|7|강화실패|+4 $\to$ +4|강화실패로 인하여 강화상태 변화없음 |
|8|강화성공|+4 $\to$ +5|모든 강화 성공|
|9|-|+5 $\to$ +5|더 이상 강화시도 하지 않음|
|10|$\dots$|$\dots$|$\dots$|


강화는 하루에 한 번씩만 시도할 수 있으며 시도가능한 기간은 7월1일부터 8월31일까지로 한정되어 있다고 하자. 따라서 방학동안 유저들은 총 62번 시도를 할 수 있다. 방학이 끝난이후 100명 유저중 대략 몇명정도 +5 강화상태에 있겠는가? 파이썬을 통한 시뮬레이션을 활용하여 추론하라. (단, +5강화에 성공하지 못한 모든 유저는 반드시 하루에 한번 강화를 시도해야 한다고 가정하자.)

### \# 2. (70점)

강화성공확률을 70%로 수정한다. 강화에 누적2회 실패하면 강화상태가 초기화 된다고 하자. (따라서 강화실패 누적횟수를 카운트하는 변수가 필요하다)
단, 강화실패 누적횟수는 누적2회 달성시 0으로 초기화 된다. 또한 강화상태가 +0인 경우는 실패하여도 강화누적횟수가 추가되지 않는다. 

|시도횟수|강화성공여부|강화상태|강화실패누적|비고|
|:-:|:-:|:-:|:-:|:-|
|1|강화성공|+0 $\to$ +1| 0 $\to$ 0|- |
|2|강화성공|+1 $\to$ +2|0 $\to$ 0 |-|
|3|강화실패|+2 $\to$ +2 |0 $\to$ 1|-| 
|4|강화성공|+2 $\to$ +3 |1 $\to$ 1|-|
|5|강화실패|+3 $\to$ +0 |1 $\to$ 0| 강화실패로 누적2회로 인한 초기화|
|6|강화실패|+0 $\to$ +0|0 $\to$ 0| 강화실패 누적횟수 증가하지 않음|
|7|강화성공|+0 $\to$ +1 |0 $\to$ 0|-|
|8|강화성공|+1 $\to$ +2|0 $\to$ 0|-|
|9|강화성공|+2 $\to$ +3|0 $\to$ 0|-|
|10|강화성공|+3 $\to$ +4|0 $\to$ 0|-|
|11|강화성공|+4 $\to$ +5|0 $\to$ 0|모든 강화 성공|
|12|-|+5 $\to$ +5|0 $\to$ 0|더 이상 강화시도 하지 않음|
|13|$\dots$|$\dots$|$\dots$|$\dots$|

`(1)` 이 경우 62일의 방학뒤에 100명의 유저중 대략 몇명정도 +5 강화상태에 있겠는가? 시뮬레이션을 활용하여 추론하라. (단, +5강화에 성공하지 못한 모든 유저는 반드시 하루에 한번 강화를 시도해야 한다고 가정하자.)

`(2)` 31번째 시도 이후 대략 몇명의 유저가 +5 강화상태에 있겠는가?

`(3)` 100명의 유저중 50명이상의 유저가 +5 강화상태에 도달하는 순간 모든 유저의 강화성공확률을 90%로 증가시킨다고 하자. 62일의 방학뒤에 100명의 유저 중 몇명 정도가 +5 강화상태에 있겠는가?

### \#1~2에 대한 Hint

#### TIP1: 클래스를 활용하여 코드를 짜면 편리합니다. (클래스를 활용하지 않아도 감점없습니다. 돌아가기만 하면 됩니다)

`-` 클래스 변수 

- prob: 강화성공확률을 기록하는 변수 (0~1 사이의 값이 저장됨) 
- attemptresult: 강화성공여부를 기록하는 매트릭스 (성공하면 1, 실패시 0이 저장됨) 
- upgradestate: 강화성공상태를 기록하는 매트릭스 (0~5 사이의 값이 저장됨) 
- failstate: 강화실패누적을 기록하는 매트릭스 (0~2 사이의 값이 저장됨) 
- ratio: +5강인 유저와 그렇지 않은 유저의 비율을 기록하는 변수 (0~1 사이의 값이 저장됨) 

`-` 클래스 메소드

- attempt(): prob에 따라 강화를 시도하고 결과를 attemptresult에 기록하는 함수 
- update(): attemptresult값에 따라 upgradestate, failstate, ratio 값을 갱신하는 함수 
- reset(): 강화누적2회 실패여부를 체크하고 upgradestate, failstate 를 초기화하는 함수
- arrangeprobt(): ratio의 값에 따라 prob 값을 조정하는 함수

#### TIP2: 필요하다면 아래의 코드를 활용하세요

`-` p의 확률로 0 혹은 1을 100개 뽑는 함수예시

In [32]:
import numpy as np 
np.random.binomial(n=1, p=0.3, size=100) # 0.3 의 확률로 0 혹은 1을 추출

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0])

In [33]:
np.random.binomial(n=1, p=0.7, size=100) # 0.7 의 확률로 0 혹은 1을 추출

array([0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1])

`-` 강화 성공시에 강화상태를 업그레이드 하는 코드예시

In [52]:
import pandas as pd
upgradestate=pd.DataFrame({'day0':[0]*100})
upgradestate

    day0
0      0
1      0
2      0
3      0
4      0
..   ...
95     0
96     0
97     0
98     0
99     0

[100 rows x 1 columns]

In [53]:
i=1
attemptresult=np.random.binomial(n=1, p=0.7, size=100) 
upgradestate['day%s' % i]=upgradestate['day%s' % (i-1)]+attemptresult
upgradestate

    day0  day1
0      0     1
1      0     1
2      0     1
3      0     1
4      0     1
..   ...   ...
95     0     1
96     0     1
97     0     1
98     0     1
99     0     1

[100 rows x 2 columns]

`-` 강화실패시 누적횟수를 증가하는 코드 예시

In [54]:
i=1
failstate=pd.DataFrame({'day0':[0]*100})
failstate['day%s' % i]=failstate['day%s' % (i-1)]+(attemptresult==0)*1
failstate

    day0  day1
0      0     0
1      0     0
2      0     0
3      0     0
4      0     0
..   ...   ...
95     0     0
96     0     0
97     0     0
98     0     0
99     0     0

[100 rows x 2 columns]

`-` 강화상태가 5일 경우에는 더 이상 강화상태를 증가시키지 않는 코드 예시

In [60]:
upgradestate_=np.array([4]*50+[5]*50)
upgradestate_

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [63]:
upgradestate_+attemptresult

array([5, 5, 5, 5, 5, 5, 4, 5, 4, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       4, 5, 5, 5, 4, 5, 4, 4, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 4, 5, 5,
       5, 4, 5, 5, 4, 5, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5,
       6, 6, 5, 6, 6, 6, 6, 5, 6, 6, 5, 6, 6, 6, 5, 5, 6, 6, 5, 6, 5, 6,
       5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [70]:
np.minimum(upgradestate_+attemptresult,5)

array([5, 5, 5, 5, 5, 5, 4, 5, 4, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       4, 5, 5, 5, 4, 5, 4, 4, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 4, 5, 5,
       5, 4, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

### \# 3. 다음문장을 잘 읽고 참 거짓을 판단하여라. (10점)

(1) tuple은 원소의 값을 임의로 바꿀 수 있다.

(2) class 에 정의된 함수(=메서드)는 self 만을 인자로 받을수 있다.