# (노트) 판다스 - 치환 

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- hide: false
- categories: [파이썬]

### where / mask (inplace transform)

`-` 기능1

In [103]:
_df=pd.DataFrame(np.random.normal(size=(5,2)),columns=list('AB'))
_df

          A         B
0 -0.461594  0.205284
1 -0.461377  0.140585
2 -0.521255 -0.522288
3 -0.482910 -0.421654
4 -0.395020  0.935864

In [107]:
_df.where(_df>0)

    A         B
0 NaN  0.205284
1 NaN  0.140585
2 NaN       NaN
3 NaN       NaN
4 NaN  0.935864

그다지 유용해 보이지도 않고 아래와 같은 코드이다.

In [110]:
_df[_df>0]

    A         B
0 NaN  0.205284
1 NaN  0.140585
2 NaN       NaN
3 NaN       NaN
4 NaN  0.935864

`-` 기능2: NaN에 해당하는 값들을 치환할수 있다.

In [141]:
_df

          A         B
0 -0.461594  0.205284
1 -0.461377  0.140585
2 -0.521255 -0.522288
3 -0.482910 -0.421654
4 -0.395020  0.935864

In [142]:
_df.where(_df>0,0)

     A         B
0  0.0  0.205284
1  0.0  0.140585
2  0.0  0.000000
3  0.0  0.000000
4  0.0  0.935864

In [113]:
_df.where(_df>0, -_df)

          A         B
0  0.461594  0.205284
1  0.461377  0.140585
2  0.521255  0.522288
3  0.482910  0.421654
4  0.395020  0.935864

`-` lambda와 함께 사용가능

In [131]:
_df.where(lambda x: x>0, lambda x: 0)

     A         B
0  0.0  0.205284
1  0.0  0.140585
2  0.0  0.000000
3  0.0  0.000000
4  0.0  0.935864

In [129]:
_df.where(lambda x: x>0, lambda x: -x)

          A         B
0  0.461594  0.205284
1  0.461377  0.140585
2  0.521255  0.522288
3  0.482910  0.421654
4  0.395020  0.935864

`-` mask: where의 반대

In [138]:
_df

          A         B
0 -0.461594  0.205284
1 -0.461377  0.140585
2 -0.521255 -0.522288
3 -0.482910 -0.421654
4 -0.395020  0.935864

In [139]:
_df.where(_df>0,0)

     A         B
0  0.0  0.205284
1  0.0  0.140585
2  0.0  0.000000
3  0.0  0.000000
4  0.0  0.935864

In [140]:
_df.mask(_df>0,0)

          A         B
0 -0.461594  0.000000
1 -0.461377  0.000000
2 -0.521255 -0.522288
3 -0.482910 -0.421654
4 -0.395020  0.000000

In [143]:
_df.mask(lambda x: x>0,0)

          A         B
0 -0.461594  0.000000
1 -0.461377  0.000000
2 -0.521255 -0.522288
3 -0.482910 -0.421654
4 -0.395020  0.000000

`-` np.where과 비교

In [133]:
_df

          A         B
0 -0.461594  0.205284
1 -0.461377  0.140585
2 -0.521255 -0.522288
3 -0.482910 -0.421654
4 -0.395020  0.935864

In [132]:
np.where(_df<0,1,0) # R에서의 ifelse와 같음

array([[1, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 0]])

### where / mask (inplace transform)

`-` 기능1

In [103]:
_df=pd.DataFrame(np.random.normal(size=(5,2)),columns=list('AB'))
_df

          A         B
0 -0.461594  0.205284
1 -0.461377  0.140585
2 -0.521255 -0.522288
3 -0.482910 -0.421654
4 -0.395020  0.935864

In [107]:
_df.where(_df>0)

    A         B
0 NaN  0.205284
1 NaN  0.140585
2 NaN       NaN
3 NaN       NaN
4 NaN  0.935864

그다지 유용해 보이지도 않고 아래와 같은 코드이다.

In [110]:
_df[_df>0]

    A         B
0 NaN  0.205284
1 NaN  0.140585
2 NaN       NaN
3 NaN       NaN
4 NaN  0.935864

`-` 기능2: NaN에 해당하는 값들을 치환할수 있다.

In [141]:
_df

          A         B
0 -0.461594  0.205284
1 -0.461377  0.140585
2 -0.521255 -0.522288
3 -0.482910 -0.421654
4 -0.395020  0.935864

In [142]:
_df.where(_df>0,0)

     A         B
0  0.0  0.205284
1  0.0  0.140585
2  0.0  0.000000
3  0.0  0.000000
4  0.0  0.935864

In [113]:
_df.where(_df>0, -_df)

          A         B
0  0.461594  0.205284
1  0.461377  0.140585
2  0.521255  0.522288
3  0.482910  0.421654
4  0.395020  0.935864

`-` lambda와 함께 사용가능

In [131]:
_df.where(lambda x: x>0, lambda x: 0)

     A         B
0  0.0  0.205284
1  0.0  0.140585
2  0.0  0.000000
3  0.0  0.000000
4  0.0  0.935864

In [129]:
_df.where(lambda x: x>0, lambda x: -x)

          A         B
0  0.461594  0.205284
1  0.461377  0.140585
2  0.521255  0.522288
3  0.482910  0.421654
4  0.395020  0.935864

`-` mask: where의 반대

In [138]:
_df

          A         B
0 -0.461594  0.205284
1 -0.461377  0.140585
2 -0.521255 -0.522288
3 -0.482910 -0.421654
4 -0.395020  0.935864

In [139]:
_df.where(_df>0,0)

     A         B
0  0.0  0.205284
1  0.0  0.140585
2  0.0  0.000000
3  0.0  0.000000
4  0.0  0.935864

In [140]:
_df.mask(_df>0,0)

          A         B
0 -0.461594  0.000000
1 -0.461377  0.000000
2 -0.521255 -0.522288
3 -0.482910 -0.421654
4 -0.395020  0.000000

In [143]:
_df.mask(lambda x: x>0,0)

          A         B
0 -0.461594  0.000000
1 -0.461377  0.000000
2 -0.521255 -0.522288
3 -0.482910 -0.421654
4 -0.395020  0.000000

`-` np.where과 비교

In [133]:
_df

          A         B
0 -0.461594  0.205284
1 -0.461377  0.140585
2 -0.521255 -0.522288
3 -0.482910 -0.421654
4 -0.395020  0.935864

In [132]:
np.where(_df<0,1,0) # R에서의 ifelse와 같음

array([[1, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 0]])

### where / mask (inplace transform)

`-` 기능1

In [103]:
_df=pd.DataFrame(np.random.normal(size=(5,2)),columns=list('AB'))
_df

          A         B
0 -0.461594  0.205284
1 -0.461377  0.140585
2 -0.521255 -0.522288
3 -0.482910 -0.421654
4 -0.395020  0.935864

In [107]:
_df.where(_df>0)

    A         B
0 NaN  0.205284
1 NaN  0.140585
2 NaN       NaN
3 NaN       NaN
4 NaN  0.935864

그다지 유용해 보이지도 않고 아래와 같은 코드이다.

In [110]:
_df[_df>0]

    A         B
0 NaN  0.205284
1 NaN  0.140585
2 NaN       NaN
3 NaN       NaN
4 NaN  0.935864

`-` 기능2: NaN에 해당하는 값들을 치환할수 있다.

In [141]:
_df

          A         B
0 -0.461594  0.205284
1 -0.461377  0.140585
2 -0.521255 -0.522288
3 -0.482910 -0.421654
4 -0.395020  0.935864

In [142]:
_df.where(_df>0,0)

     A         B
0  0.0  0.205284
1  0.0  0.140585
2  0.0  0.000000
3  0.0  0.000000
4  0.0  0.935864

In [113]:
_df.where(_df>0, -_df)

          A         B
0  0.461594  0.205284
1  0.461377  0.140585
2  0.521255  0.522288
3  0.482910  0.421654
4  0.395020  0.935864

`-` lambda와 함께 사용가능

In [131]:
_df.where(lambda x: x>0, lambda x: 0)

     A         B
0  0.0  0.205284
1  0.0  0.140585
2  0.0  0.000000
3  0.0  0.000000
4  0.0  0.935864

In [129]:
_df.where(lambda x: x>0, lambda x: -x)

          A         B
0  0.461594  0.205284
1  0.461377  0.140585
2  0.521255  0.522288
3  0.482910  0.421654
4  0.395020  0.935864

`-` mask: where의 반대

In [138]:
_df

          A         B
0 -0.461594  0.205284
1 -0.461377  0.140585
2 -0.521255 -0.522288
3 -0.482910 -0.421654
4 -0.395020  0.935864

In [139]:
_df.where(_df>0,0)

     A         B
0  0.0  0.205284
1  0.0  0.140585
2  0.0  0.000000
3  0.0  0.000000
4  0.0  0.935864

In [140]:
_df.mask(_df>0,0)

          A         B
0 -0.461594  0.000000
1 -0.461377  0.000000
2 -0.521255 -0.522288
3 -0.482910 -0.421654
4 -0.395020  0.000000

In [143]:
_df.mask(lambda x: x>0,0)

          A         B
0 -0.461594  0.000000
1 -0.461377  0.000000
2 -0.521255 -0.522288
3 -0.482910 -0.421654
4 -0.395020  0.000000

`-` np.where과 비교

In [133]:
_df

          A         B
0 -0.461594  0.205284
1 -0.461377  0.140585
2 -0.521255 -0.522288
3 -0.482910 -0.421654
4 -0.395020  0.935864

In [132]:
np.where(_df<0,1,0) # R에서의 ifelse와 같음

array([[1, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 0]])