# (정리) pandas

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- categories: [파이썬]

## import

In [2]:
import pandas as pd
import numpy as np

## I. make data, read data, profiling

### 1. make data

### 2. read data

#### 예제: read data from github

In [3]:
url='https://raw.githubusercontent.com/PacktPublishing/Pandas-Cookbook-Second-Edition/master/data/movie.csv'
df = pd.read_csv(url, index_col=0)
df

,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
color,,,,,,,,,,,,,,,,,,,,,
Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,Eric Mabius,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,Eva Boehnke,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,Alan Ruck,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,John August,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

- NaN: missing, not a number

### 3. profiling

In [4]:
url='https://raw.githubusercontent.com/PacktPublishing/Pandas-Cookbook-Second-Edition/master/data/movie.csv'
df = pd.read_csv(url, index_col=0)
df.describe()

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4867.000000,4901.000000,4814.000000,4893.000000,4909.000000,4.054000e+03,4.916000e+03,4916.000000,4903.000000,4895.000000,4.432000e+03,4810.000000,4903.000000,4916.000000,4590.000000,4916.000000
mean,137.988905,107.090798,691.014541,631.276313,6494.488491,4.764451e+07,8.264492e+04,9579.815907,1.377320,267.668846,3.654749e+07,2002.447609,1621.923516,6.437429,2.222349,7348.294142
std,120.239379,25.286015,2832.954125,1625.874802,15106.986884,6.737255e+07,1.383222e+05,18164.316990,2.023826,372.934839,1.002427e+08,12.453977,4011.299523,1.127802,1.402940,19206.016458
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
25%,49.000000,93.000000,7.000000,132.000000,607.000000,5.019656e+06,8.361750e+03,1394.750000,0.000000,64.000000,6.000000e+06,1999.000000,277.000000,5.800000,1.850000,0.000000
50%,108.000000,103.000000,48.000000,366.000000,982.000000,2.504396e+07,3.313250e+04,3049.000000,1.000000,153.000000,1.985000e+07,2005.000000,593.000000,6.600000,2.350000,159.000000
75%,191.000000,118.000000,189.750000,633.000000,11000.000000,6.110841e+07,9.377275e+04,13616.750000,2.000000,320.500000,4.300000e+07,2011.000000,912.000000,7.200000,2.350000,2000.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,4.200000e+09,2016.000000,137000.000000,9.500000,16.000000,349000.000000

## II. select and filter

In [5]:
url='https://raw.githubusercontent.com/PacktPublishing/Pandas-Cookbook-Second-Edition/master/data/movie.csv'
df = pd.read_csv(url, index_col=0)
data=df.to_numpy()
data

array([['James Cameron', 723.0, 178.0, ..., 7.9, 1.78, 33000],
       ['Gore Verbinski', 302.0, 169.0, ..., 7.1, 2.35, 0],
       ['Sam Mendes', 602.0, 148.0, ..., 6.8, 2.35, 85000],
       ...,
       ['Benjamin Roberds', 13.0, 76.0, ..., 6.3, nan, 16],
       ['Daniel Hsia', 14.0, 100.0, ..., 6.3, 2.35, 660],
       ['Jon Gunn', 43.0, 90.0, ..., 6.6, 1.85, 456]], dtype=object)

In [6]:
data[0] ## first observation

array(['James Cameron', 723.0, 178.0, 0.0, 855.0, 'Joel David Moore',
       1000.0, 760505847.0, 'Action|Adventure|Fantasy|Sci-Fi',
       'CCH Pounder', 'Avatar', 886204, 4834, 'Wes Studi', 0.0,
       'avatar|future|marine|native|paraplegic',
       'http://www.imdb.com/title/tt0499549/?ref_=fn_tt_tt_1', 3054.0,
       'English', 'USA', 'PG-13', 237000000.0, 2009.0, 936.0, 7.9, 1.78,
       33000], dtype=object)

In [7]:
data[0,:] ## first observation

array(['James Cameron', 723.0, 178.0, 0.0, 855.0, 'Joel David Moore',
       1000.0, 760505847.0, 'Action|Adventure|Fantasy|Sci-Fi',
       'CCH Pounder', 'Avatar', 886204, 4834, 'Wes Studi', 0.0,
       'avatar|future|marine|native|paraplegic',
       'http://www.imdb.com/title/tt0499549/?ref_=fn_tt_tt_1', 3054.0,
       'English', 'USA', 'PG-13', 237000000.0, 2009.0, 936.0, 7.9, 1.78,
       33000], dtype=object)

In [8]:
data.T[0] # first variable

array(['James Cameron', 'Gore Verbinski', 'Sam Mendes', ...,
       'Benjamin Roberds', 'Daniel Hsia', 'Jon Gunn'], dtype=object)

In [9]:
data[:,0] # first variable

array(['James Cameron', 'Gore Verbinski', 'Sam Mendes', ...,
       'Benjamin Roberds', 'Daniel Hsia', 'Jon Gunn'], dtype=object)

In [10]:
data[0][0] # (first observation, first variable)

'James Cameron'

### 1. select column

#### 예제: 하나의 열을 선택

In [11]:
dic={'X1':np.random.normal(0,1,5), 
     'X2':np.random.normal(0,1,5),
     'X3':np.random.normal(0,1,5)}
df=pd.DataFrame(dic)
df

         X1        X2        X3
0  1.503425 -0.452285 -0.849588
1  0.580809  0.634236  1.402876
2 -0.805731  0.366918 -0.928336
3  0.014254 -1.072588  0.324546
4 -2.108220 -0.319980  0.262438

`-` 방법1

In [12]:
df.X1

0    1.503425
1    0.580809
2   -0.805731
3    0.014254
4   -2.108220
Name: X1, dtype: float64

`-` 방법2

In [13]:
df['X1']

0    1.503425
1    0.580809
2   -0.805731
3    0.014254
4   -2.108220
Name: X1, dtype: float64

`-` 방법3

In [14]:
df[['X1']]

         X1
0  1.503425
1  0.580809
2 -0.805731
3  0.014254
4 -2.108220

- `df['X1']`는 series를 리턴하고 `df[['X1']]`는 dataframe을 리턴한다.

`-` 방법4

In [15]:
df.loc[:,'X1']

0    1.503425
1    0.580809
2   -0.805731
3    0.014254
4   -2.108220
Name: X1, dtype: float64

`-` 방법5

In [16]:
df.loc[:,['X1']]

         X1
0  1.503425
1  0.580809
2 -0.805731
3  0.014254
4 -2.108220

- `df.loc[:,'X1']`는 series를 리턴하고 `df[['X1']]`는 dataframe을 리턴한다.

`-` 방법6

In [17]:
df.loc[:,[True,False,False]]

         X1
0  1.503425
1  0.580809
2 -0.805731
3  0.014254
4 -2.108220

- 불인덱싱가능

`-` 방법7

In [18]:
df.iloc[:,0]

0    1.503425
1    0.580809
2   -0.805731
3    0.014254
4   -2.108220
Name: X1, dtype: float64

`-` 방법8

In [19]:
df.iloc[:,[0]]

         X1
0  1.503425
1  0.580809
2 -0.805731
3  0.014254
4 -2.108220

`-` 방법9

In [20]:
df.iloc[:,[True,False,False]]

         X1
0  1.503425
1  0.580809
2 -0.805731
3  0.014254
4 -2.108220

**참고: 열이름이 integer일 경우**

In [21]:
_df = pd.DataFrame(np.array([[1,2,3],[3,4,5],[5,6,7]]))
_df

   0  1  2
0  1  2  3
1  3  4  5
2  5  6  7

`-` 아래가 모두 가능

In [22]:
_df[0]

0    1
1    3
2    5
Name: 0, dtype: int64

In [23]:
_df[[0]]

   0
0  1
1  3
2  5

In [24]:
_df.loc[:,[0]]

   0
0  1
1  3
2  5

In [25]:
_df.iloc[:,[0]]

   0
0  1
1  3
2  5

**방법 1~9의 요약**

- `df.X1` 이 가장 간단하고 편리함. 그런데 변수이름을 알고 있어야 한다는 단점이 있음. 
- `df.X1` 은 변수이름에 `.`이 포함된 경우는 사용불가. 그밖에도 변수이름에 공백이 있는등 이상한 형태의 변수이름에는 사용불가능.

#### 예제: `df`에서 1,2,3열을 선택

In [26]:
dic={'X1':np.random.normal(0,1,5), 
     'X2':np.random.normal(0,1,5),
     'X3':np.random.normal(0,1,5),
     'X4':np.random.normal(0,1,5)
    }
df=pd.DataFrame(dic)
df

         X1        X2        X3        X4
0 -1.907817 -0.790811 -0.246227 -1.113627
1  1.650106 -1.747030  1.336080 -1.421119
2 -0.282799 -1.920867  0.040738 -0.195458
3 -0.948650 -0.027383  0.483993  0.224683
4 -0.989510 -1.040666 -1.327560  0.497181

`-` 방법1

In [27]:
df[['X1','X2','X3']]

         X1        X2        X3
0 -1.907817 -0.790811 -0.246227
1  1.650106 -1.747030  1.336080
2 -0.282799 -1.920867  0.040738
3 -0.948650 -0.027383  0.483993
4 -0.989510 -1.040666 -1.327560

위와 동일한 문법을 응용하면

In [28]:
varlist=['X'+i for i in '123']
varlist

['X1', 'X2', 'X3']

In [29]:
df[varlist]

         X1        X2        X3
0 -1.907817 -0.790811 -0.246227
1  1.650106 -1.747030  1.336080
2 -0.282799 -1.920867  0.040738
3 -0.948650 -0.027383  0.483993
4 -0.989510 -1.040666 -1.327560

`-` 방법2

In [30]:
df.loc[:,['X1','X2','X3']]

         X1        X2        X3
0 -1.907817 -0.790811 -0.246227
1  1.650106 -1.747030  1.336080
2 -0.282799 -1.920867  0.040738
3 -0.948650 -0.027383  0.483993
4 -0.989510 -1.040666 -1.327560

`-` 방법3

In [31]:
df.loc[:,'X1':'X3']

         X1        X2        X3
0 -1.907817 -0.790811 -0.246227
1  1.650106 -1.747030  1.336080
2 -0.282799 -1.920867  0.040738
3 -0.948650 -0.027383  0.483993
4 -0.989510 -1.040666 -1.327560

`-` 방법4

In [32]:
df.loc[:,[True,True,True,False]]

         X1        X2        X3
0 -1.907817 -0.790811 -0.246227
1  1.650106 -1.747030  1.336080
2 -0.282799 -1.920867  0.040738
3 -0.948650 -0.027383  0.483993
4 -0.989510 -1.040666 -1.327560

응용하면 아래도 가능하다

In [33]:
_cols=df.columns.to_list()
_cols

['X1', 'X2', 'X3', 'X4']

In [34]:
import re

In [35]:
re.match('X',_cols[0])

`-` 방법5

In [36]:
df.iloc[:,[0,1,2]]

         X1        X2        X3
0 -1.907817 -0.790811 -0.246227
1  1.650106 -1.747030  1.336080
2 -0.282799 -1.920867  0.040738
3 -0.948650 -0.027383  0.483993
4 -0.989510 -1.040666 -1.327560

이 방법을 응용하면

In [37]:
idx = range(3)
idx

range(0, 3)

In [38]:
df.iloc[:,idx]

         X1        X2        X3
0 -1.907817 -0.790811 -0.246227
1  1.650106 -1.747030  1.336080
2 -0.282799 -1.920867  0.040738
3 -0.948650 -0.027383  0.483993
4 -0.989510 -1.040666 -1.327560

In [39]:
idx = np.arange(3)
idx

array([0, 1, 2])

In [40]:
df.iloc[:,idx]

         X1        X2        X3
0 -1.907817 -0.790811 -0.246227
1  1.650106 -1.747030  1.336080
2 -0.282799 -1.920867  0.040738
3 -0.948650 -0.027383  0.483993
4 -0.989510 -1.040666 -1.327560

In [41]:
idx = np.arange(3.)
idx

array([0., 1., 2.])

In [42]:
df.iloc[:,idx]

         X1        X2        X3
0 -1.907817 -0.790811 -0.246227
1  1.650106 -1.747030  1.336080
2 -0.282799 -1.920867  0.040738
3 -0.948650 -0.027383  0.483993
4 -0.989510 -1.040666 -1.327560

- idx의 값이 float형으로 저장되어 있어도 에러나지 않음

`-` 방법6

In [43]:
df.iloc[:,[True,True,True,False]]

         X1        X2        X3
0 -1.907817 -0.790811 -0.246227
1  1.650106 -1.747030  1.336080
2 -0.282799 -1.920867  0.040738
3 -0.948650 -0.027383  0.483993
4 -0.989510 -1.040666 -1.327560

**(주의) loc에서의 슬라이싱은 마지막변수를 포함하지만 iloc에서는 포함하지 않음.**

`-` 아래를 비교하라.

In [44]:
df.iloc[:,0:3] ## 3은 포함되지 않는다.

         X1        X2        X3
0 -1.907817 -0.790811 -0.246227
1  1.650106 -1.747030  1.336080
2 -0.282799 -1.920867  0.040738
3 -0.948650 -0.027383  0.483993
4 -0.989510 -1.040666 -1.327560

In [45]:
df.loc[:,'X1':'X3'] ## 'X3'이 포함된다.

         X1        X2        X3
0 -1.907817 -0.790811 -0.246227
1  1.650106 -1.747030  1.336080
2 -0.282799 -1.920867  0.040738
3 -0.948650 -0.027383  0.483993
4 -0.989510 -1.040666 -1.327560

`-` 그래서 column의 이름이 integer일 경우는 종종 매우 헷갈리는 결과가 나옴

In [46]:
_df = pd.DataFrame(np.array([[1,2,3,4],[3,4,5,6],[5,6,7,8]]))
_df

   0  1  2  3
0  1  2  3  4
1  3  4  5  6
2  5  6  7  8

In [47]:
_df.loc[:,0:2]

   0  1  2
0  1  2  3
1  3  4  5
2  5  6  7

In [48]:
_df.iloc[:,0:2]

   0  1
0  1  2
1  3  4
2  5  6

> note: 사실 이것은 일부러 헷갈리게 예제를 구성한것이다. 실제로는 헷갈리는 상황이 많이 발생하지 않는다. 왜냐하면 보통 위의 예제와 같은 경우에는 ndarray로 처리하고 colname이 있는 경우만 데이터프레임으로 처리하기 때문

**방법 1~6의 요약**

`-` 내가 생각할때 가장 독특한 방법은 아래이다. (그런데 컬럼이름 양옆에 따옴표를 붙이는 것이 불편함)

In [49]:
df.loc[:,'X1':'X3']

         X1        X2        X3
0 -1.907817 -0.790811 -0.246227
1  1.650106 -1.747030  1.336080
2 -0.282799 -1.920867  0.040738
3 -0.948650 -0.027383  0.483993
4 -0.989510 -1.040666 -1.327560

- 이방법은 오로지 판다스에서만 가능하다.

`-` 변수이름이 순서대로 정리되어 있지 않아도 사용할 수 있다.

In [50]:
_dic={'Y1':np.random.normal(0,1,5), 
      'Y2':np.random.normal(0,1,5),
      'X1':np.random.normal(0,1,5),
      'X2':np.random.normal(0,1,5)}
_df=pd.DataFrame(_dic)
_df

         Y1        Y2        X1        X2
0 -0.734773 -1.599649  0.518970 -1.662894
1  0.679337 -0.130844 -0.985108 -0.110248
2 -1.264149 -0.085269 -2.574022  0.011470
3 -0.525075 -0.349322  0.250697 -0.756816
4  1.238033  0.812356 -0.114869  1.020324

In [51]:
_df.loc[:,'Y1':'X1']

         Y1        Y2        X1
0 -0.734773 -1.599649  0.518970
1  0.679337 -0.130844 -0.985108
2 -1.264149 -0.085269 -2.574022
3 -0.525075 -0.349322  0.250697
4  1.238033  0.812356 -0.114869

#### 예제: movie data

In [52]:
url='https://raw.githubusercontent.com/PacktPublishing/Pandas-Cookbook-Second-Edition/master/data/movie.csv'
df = pd.read_csv(url, index_col=0)
df

,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
color,,,,,,,,,,,,,,,,,,,,,
Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,Eric Mabius,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,Eva Boehnke,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,Alan Ruck,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,John August,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

`-` 열의 이름을 출력해보자.

In [53]:
cols=df.columns.to_list()
cols

['director_name',
 'num_critic_for_reviews',
 'duration',
 'director_facebook_likes',
 'actor_3_facebook_likes',
 'actor_2_name',
 'actor_1_facebook_likes',
 'gross',
 'genres',
 'actor_1_name',
 'movie_title',
 'num_voted_users',
 'cast_total_facebook_likes',
 'actor_3_name',
 'facenumber_in_poster',
 'plot_keywords',
 'movie_imdb_link',
 'num_user_for_reviews',
 'language',
 'country',
 'content_rating',
 'budget',
 'title_year',
 'actor_2_facebook_likes',
 'imdb_score',
 'aspect_ratio',
 'movie_facebook_likes']

`-` 팁: 열의 이름을 인덱스와 함께 출력하기 위해서는 아래와 같이 하면 쉽다.

In [54]:
pd.Series(cols)

0                 director_name
1        num_critic_for_reviews
2                      duration
3       director_facebook_likes
4        actor_3_facebook_likes
5                  actor_2_name
6        actor_1_facebook_likes
7                         gross
8                        genres
9                  actor_1_name
10                  movie_title
11              num_voted_users
12    cast_total_facebook_likes
13                 actor_3_name
14         facenumber_in_poster
15                plot_keywords
16              movie_imdb_link
17         num_user_for_reviews
18                     language
19                      country
20               content_rating
21                       budget
22                   title_year
23       actor_2_facebook_likes
24                   imdb_score
25                 aspect_ratio
26         movie_facebook_likes
dtype: object

`-` actor로 시작하는 변수들을 뽑아보자.

In [55]:
_cols = list(filter(lambda x: 'actor' in x[:5] , cols))
_cols

['actor_3_facebook_likes',
 'actor_2_name',
 'actor_1_facebook_likes',
 'actor_1_name',
 'actor_3_name',
 'actor_2_facebook_likes']

In [56]:
df.loc[:, _cols]

,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,actor_1_name,actor_3_name,actor_2_facebook_likes
color,,,,,,
Color,855.0,Joel David Moore,1000.0,CCH Pounder,Wes Studi,936.0
Color,1000.0,Orlando Bloom,40000.0,Johnny Depp,Jack Davenport,5000.0
Color,161.0,Rory Kinnear,11000.0,Christoph Waltz,Stephanie Sigman,393.0
Color,23000.0,Christian Bale,27000.0,Tom Hardy,Joseph Gordon-Levitt,23000.0
NaN,NaN,Rob Walker,131.0,Doug Walker,NaN,12.0
...,...,...,...,...,...,...
Color,318.0,Daphne Zuniga,637.0,Eric Mabius,Crystal Lowe,470.0
Color,319.0,Valorie Curry,841.0,Natalie Zea,Sam Underwood,593.0
Color,0.0,Maxwell Moody,0.0,Eva Boehnke,David Chandler,0.0
Color,489.0,Daniel Henney,946.0,Alan Ruck,Eliza Coupe,719.0
Color,16.0,Brian Herzlinger,86.0,John August,Jon Gunn,23.0

또는 아래와 같이 할 수 있다.

In [57]:
_bools = list(map(lambda x: 'actor' in x[:5] , cols))
print(_bools)
display(df.loc[:,_bools])
display(df.iloc[:,_bools])

[False, False, False, False, True, True, True, False, False, True, False, False, False, True, False, False, False, False, False, False, False, False, False, True, False, False, False]

,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,actor_1_name,actor_3_name,actor_2_facebook_likes
color,,,,,,
Color,855.0,Joel David Moore,1000.0,CCH Pounder,Wes Studi,936.0
Color,1000.0,Orlando Bloom,40000.0,Johnny Depp,Jack Davenport,5000.0
Color,161.0,Rory Kinnear,11000.0,Christoph Waltz,Stephanie Sigman,393.0
Color,23000.0,Christian Bale,27000.0,Tom Hardy,Joseph Gordon-Levitt,23000.0
NaN,NaN,Rob Walker,131.0,Doug Walker,NaN,12.0
...,...,...,...,...,...,...
Color,318.0,Daphne Zuniga,637.0,Eric Mabius,Crystal Lowe,470.0
Color,319.0,Valorie Curry,841.0,Natalie Zea,Sam Underwood,593.0
Color,0.0,Maxwell Moody,0.0,Eva Boehnke,David Chandler,0.0
Color,489.0,Daniel Henney,946.0,Alan Ruck,Eliza Coupe,719.0
Color,16.0,Brian Herzlinger,86.0,John August,Jon Gunn,23.0

,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,actor_1_name,actor_3_name,actor_2_facebook_likes
color,,,,,,
Color,855.0,Joel David Moore,1000.0,CCH Pounder,Wes Studi,936.0
Color,1000.0,Orlando Bloom,40000.0,Johnny Depp,Jack Davenport,5000.0
Color,161.0,Rory Kinnear,11000.0,Christoph Waltz,Stephanie Sigman,393.0
Color,23000.0,Christian Bale,27000.0,Tom Hardy,Joseph Gordon-Levitt,23000.0
NaN,NaN,Rob Walker,131.0,Doug Walker,NaN,12.0
...,...,...,...,...,...,...
Color,318.0,Daphne Zuniga,637.0,Eric Mabius,Crystal Lowe,470.0
Color,319.0,Valorie Curry,841.0,Natalie Zea,Sam Underwood,593.0
Color,0.0,Maxwell Moody,0.0,Eva Boehnke,David Chandler,0.0
Color,489.0,Daniel Henney,946.0,Alan Ruck,Eliza Coupe,719.0
Color,16.0,Brian Herzlinger,86.0,John August,Jon Gunn,23.0

`-` imdb가 포함된 변수들만 뽑아보자.

In [58]:
_cols = list(filter(lambda x: 'imdb' in x , cols))
_cols

['movie_imdb_link', 'imdb_score']

In [59]:
df.loc[:,_cols]

                                         movie_imdb_link  imdb_score
color
Color  http://www.imdb.com/title/tt0499549/?ref_=fn_t...         7.9
Color  http://www.imdb.com/title/tt0449088/?ref_=fn_t...         7.1
Color  http://www.imdb.com/title/tt2379713/?ref_=fn_t...         6.8
Color  http://www.imdb.com/title/tt1345836/?ref_=fn_t...         8.5
NaN    http://www.imdb.com/title/tt5289954/?ref_=fn_t...         7.1
...                                                  ...         ...
Color  http://www.imdb.com/title/tt3000844/?ref_=fn_t...         7.7
Color  http://www.imdb.com/title/tt2071645/?ref_=fn_t...         7.5
Color  http://www.imdb.com/title/tt2107644/?ref_=fn_t...         6.3
Color  http://www.imdb.com/title/tt2070597/?ref_=fn_t...         6.3
Color  http://www.imdb.com/title/tt0378407/?ref_=fn_t...         6.6

[4916 rows x 2 columns]

또는 아래와 같이 할 수 있다.

In [60]:
_bools = list(map(lambda x: 'imdb' in x , cols))
print(_bools)
display(df.loc[:,_bools])
display(df.iloc[:,_bools])

[False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, True, False, False]

                                         movie_imdb_link  imdb_score
color
Color  http://www.imdb.com/title/tt0499549/?ref_=fn_t...         7.9
Color  http://www.imdb.com/title/tt0449088/?ref_=fn_t...         7.1
Color  http://www.imdb.com/title/tt2379713/?ref_=fn_t...         6.8
Color  http://www.imdb.com/title/tt1345836/?ref_=fn_t...         8.5
NaN    http://www.imdb.com/title/tt5289954/?ref_=fn_t...         7.1
...                                                  ...         ...
Color  http://www.imdb.com/title/tt3000844/?ref_=fn_t...         7.7
Color  http://www.imdb.com/title/tt2071645/?ref_=fn_t...         7.5
Color  http://www.imdb.com/title/tt2107644/?ref_=fn_t...         6.3
Color  http://www.imdb.com/title/tt2070597/?ref_=fn_t...         6.3
Color  http://www.imdb.com/title/tt0378407/?ref_=fn_t...         6.6

[4916 rows x 2 columns]

                                         movie_imdb_link  imdb_score
color
Color  http://www.imdb.com/title/tt0499549/?ref_=fn_t...         7.9
Color  http://www.imdb.com/title/tt0449088/?ref_=fn_t...         7.1
Color  http://www.imdb.com/title/tt2379713/?ref_=fn_t...         6.8
Color  http://www.imdb.com/title/tt1345836/?ref_=fn_t...         8.5
NaN    http://www.imdb.com/title/tt5289954/?ref_=fn_t...         7.1
...                                                  ...         ...
Color  http://www.imdb.com/title/tt3000844/?ref_=fn_t...         7.7
Color  http://www.imdb.com/title/tt2071645/?ref_=fn_t...         7.5
Color  http://www.imdb.com/title/tt2107644/?ref_=fn_t...         6.3
Color  http://www.imdb.com/title/tt2070597/?ref_=fn_t...         6.3
Color  http://www.imdb.com/title/tt0378407/?ref_=fn_t...         6.6

[4916 rows x 2 columns]

`-` likes로 끝나는 변수들을 뽑아보자.

In [61]:
_cols = list(filter(lambda x: 'likes' in x[-5:] , cols))
_cols

['director_facebook_likes',
 'actor_3_facebook_likes',
 'actor_1_facebook_likes',
 'cast_total_facebook_likes',
 'actor_2_facebook_likes',
 'movie_facebook_likes']

In [62]:
df.loc[:,_cols]

,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,cast_total_facebook_likes,actor_2_facebook_likes,movie_facebook_likes
color,,,,,,
Color,0.0,855.0,1000.0,4834,936.0,33000
Color,563.0,1000.0,40000.0,48350,5000.0,0
Color,0.0,161.0,11000.0,11700,393.0,85000
Color,22000.0,23000.0,27000.0,106759,23000.0,164000
NaN,131.0,NaN,131.0,143,12.0,0
...,...,...,...,...,...,...
Color,2.0,318.0,637.0,2283,470.0,84
Color,NaN,319.0,841.0,1753,593.0,32000
Color,0.0,0.0,0.0,0,0.0,16
Color,0.0,489.0,946.0,2386,719.0,660
Color,16.0,16.0,86.0,163,23.0,456

또는 아래와 같이 할 수 있다.

In [63]:
_bools = list(map(lambda x: 'likes' in x[-5:] , cols))
print(_bools)
display(df.loc[:,_bools])
display(df.iloc[:,_bools])

[False, False, False, True, True, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, True, False, False, True]

,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,cast_total_facebook_likes,actor_2_facebook_likes,movie_facebook_likes
color,,,,,,
Color,0.0,855.0,1000.0,4834,936.0,33000
Color,563.0,1000.0,40000.0,48350,5000.0,0
Color,0.0,161.0,11000.0,11700,393.0,85000
Color,22000.0,23000.0,27000.0,106759,23000.0,164000
NaN,131.0,NaN,131.0,143,12.0,0
...,...,...,...,...,...,...
Color,2.0,318.0,637.0,2283,470.0,84
Color,NaN,319.0,841.0,1753,593.0,32000
Color,0.0,0.0,0.0,0,0.0,16
Color,0.0,489.0,946.0,2386,719.0,660
Color,16.0,16.0,86.0,163,23.0,456

,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,cast_total_facebook_likes,actor_2_facebook_likes,movie_facebook_likes
color,,,,,,
Color,0.0,855.0,1000.0,4834,936.0,33000
Color,563.0,1000.0,40000.0,48350,5000.0,0
Color,0.0,161.0,11000.0,11700,393.0,85000
Color,22000.0,23000.0,27000.0,106759,23000.0,164000
NaN,131.0,NaN,131.0,143,12.0,0
...,...,...,...,...,...,...
Color,2.0,318.0,637.0,2283,470.0,84
Color,NaN,319.0,841.0,1753,593.0,32000
Color,0.0,0.0,0.0,0,0.0,16
Color,0.0,489.0,946.0,2386,719.0,660
Color,16.0,16.0,86.0,163,23.0,456

### 2. filter

## III. transform, grouping for aggregation

## IV. combining

## V. tidydata

### 1. weapons

#### tidying (wide $\to$ long)

`-` stack()

#### untidying (long $\to$ wide)

### 2. Examples

#### 예제: state_fruit

(문제)

https://github.com/PacktPublishing/Pandas-Cookbook-Second-Edition/blob/master/data/state_fruit.csv

`-` 문제의 깃헙주소로 들어가서 데이터를 관찰 $\to$ 좌측상단이 'State'로 채워져있음 $\to$ 데이터를 읽을때 `index_col=0` 옵션을 사용함.

In [479]:
url = 'https://raw.githubusercontent.com/PacktPublishing/Pandas-Cookbook-Second-Edition/master/data/state_fruit.csv'
state_fruit = pd.read_csv(url,index_col=0) 
state_fruit

         Apple  Orange  Banana
Texas       12      10      40
Arizona      9       7      12
Florida      0      14     190

(풀이1)

In [493]:
state_fruit.stack()

Texas    Apple      12
         Orange     10
         Banana     40
Arizona  Apple       9
         Orange      7
         Banana     12
Florida  Apple       0
         Orange     14
         Banana    190
dtype: int64

In [494]:
state_fruit.stack().reset_index()

   level_0 level_1    0
0    Texas   Apple   12
1    Texas  Orange   10
2    Texas  Banana   40
3  Arizona   Apple    9
4  Arizona  Orange    7
5  Arizona  Banana   12
6  Florida   Apple    0
7  Florida  Orange   14
8  Florida  Banana  190

In [495]:
_tidy=state_fruit.stack().reset_index()
_tidy

   level_0 level_1    0
0    Texas   Apple   12
1    Texas  Orange   10
2    Texas  Banana   40
3  Arizona   Apple    9
4  Arizona  Orange    7
5  Arizona  Banana   12
6  Florida   Apple    0
7  Florida  Orange   14
8  Florida  Banana  190

In [496]:
_tidy=_tidy.rename(columns={'level_0':'G1','level_1':'G2'})
_tidy

        G1      G2    0
0    Texas   Apple   12
1    Texas  Orange   10
2    Texas  Banana   40
3  Arizona   Apple    9
4  Arizona  Orange    7
5  Arizona  Banana   12
6  Florida   Apple    0
7  Florida  Orange   14
8  Florida  Banana  190

In [497]:
_tidy=_tidy.rename(columns={0:'X1'})
_tidy

        G1      G2   X1
0    Texas   Apple   12
1    Texas  Orange   10
2    Texas  Banana   40
3  Arizona   Apple    9
4  Arizona  Orange    7
5  Arizona  Banana   12
6  Florida   Apple    0
7  Florida  Orange   14
8  Florida  Banana  190

(풀이2)

In [498]:
_tidy= state_fruit.stack().reset_index()
_tidy

   level_0 level_1    0
0    Texas   Apple   12
1    Texas  Orange   10
2    Texas  Banana   40
3  Arizona   Apple    9
4  Arizona  Orange    7
5  Arizona  Banana   12
6  Florida   Apple    0
7  Florida  Orange   14
8  Florida  Banana  190

In [499]:
_tidy.columns

Index(['level_0', 'level_1', 0], dtype='object')

In [500]:
pd.Index(['G1','G2','X1'])

Index(['G1', 'G2', 'X1'], dtype='object')

In [501]:
_tidy.columns=pd.Index(['G1','G2','X1'])

In [502]:
_tidy

        G1      G2   X1
0    Texas   Apple   12
1    Texas  Orange   10
2    Texas  Banana   40
3  Arizona   Apple    9
4  Arizona  Orange    7
5  Arizona  Banana   12
6  Florida   Apple    0
7  Florida  Orange   14
8  Florida  Banana  190

- 풀이1은 하나씩 생각나는대로 이름을 바꿔주면 되는 반면 풀이2는 한번에 모든 이름을 바꿔야한다.

(틀린풀이) 열이름을 변경할때 df.columns.values를 이용하여 억지로 바꾸면 문제가 생긴다.

In [513]:
_tidy= state_fruit.stack().reset_index()
_tidy

   level_0 level_1    0
0    Texas   Apple   12
1    Texas  Orange   10
2    Texas  Banana   40
3  Arizona   Apple    9
4  Arizona  Orange    7
5  Arizona  Banana   12
6  Florida   Apple    0
7  Florida  Orange   14
8  Florida  Banana  190

In [514]:
_tidy.columns

Index(['level_0', 'level_1', 0], dtype='object')

In [515]:
_tidy.columns.values

array(['level_0', 'level_1', 0], dtype=object)

In [516]:
_tidy.columns.values[0]

'level_0'

In [517]:
_tidy.columns.values[0]='G1'
_tidy.columns.values[1]='G2'
_tidy.columns.values[2]='G3'

In [518]:
_tidy.columns

Index(['G1', 'G2', 'G3'], dtype='object')

In [519]:
_tidy

        G1      G2   G3
0    Texas   Apple   12
1    Texas  Orange   10
2    Texas  Banana   40
3  Arizona   Apple    9
4  Arizona  Orange    7
5  Arizona  Banana   12
6  Florida   Apple    0
7  Florida  Orange   14
8  Florida  Banana  190

- 얼핏보면 맞아보이는데 key로 인덱싱이 안된다. (한마디로 위의 데이터프레임은 깨져있다.)

`-` KeyError를 확인하자.

In [530]:
_tidy['G1']

KeyError: 'G1'

(풀이3)

In [417]:
_tidy= state_fruit.stack()
_tidy

Texas    Apple      12
         Orange     10
         Banana     40
Arizona  Apple       9
         Orange      7
         Banana     12
Florida  Apple       0
         Orange     14
         Banana    190
dtype: int64

In [418]:
_tidy=_tidy.rename_axis(['G1','G2'])
_tidy

G1       G2
Texas    Apple      12
         Orange     10
         Banana     40
Arizona  Apple       9
         Orange      7
         Banana     12
Florida  Apple       0
         Orange     14
         Banana    190
dtype: int64

In [419]:
_tidy.reset_index()

        G1      G2    0
0    Texas   Apple   12
1    Texas  Orange   10
2    Texas  Banana   40
3  Arizona   Apple    9
4  Arizona  Orange    7
5  Arizona  Banana   12
6  Florida   Apple    0
7  Florida  Orange   14
8  Florida  Banana  190

In [420]:
_tidy.reset_index().rename(columns={0:'X1'})

        G1      G2   X1
0    Texas   Apple   12
1    Texas  Orange   10
2    Texas  Banana   40
3  Arizona   Apple    9
4  Arizona  Orange    7
5  Arizona  Banana   12
6  Florida   Apple    0
7  Florida  Orange   14
8  Florida  Banana  190

(풀이4)

In [421]:
state_fruit.stack()

Texas    Apple      12
         Orange     10
         Banana     40
Arizona  Apple       9
         Orange      7
         Banana     12
Florida  Apple       0
         Orange     14
         Banana    190
dtype: int64

In [422]:
state_fruit.stack().rename_axis(['G1','G2'])

G1       G2
Texas    Apple      12
         Orange     10
         Banana     40
Arizona  Apple       9
         Orange      7
         Banana     12
Florida  Apple       0
         Orange     14
         Banana    190
dtype: int64

In [423]:
state_fruit.stack().rename_axis(['G1','G2']).reset_index(name='X1')

        G1      G2   X1
0    Texas   Apple   12
1    Texas  Orange   10
2    Texas  Banana   40
3  Arizona   Apple    9
4  Arizona  Orange    7
5  Arizona  Banana   12
6  Florida   Apple    0
7  Florida  Orange   14
8  Florida  Banana  190

(풀이5) 데이터를 불러올때 아예 좌측상단이 채워졌다고 생각하고 불러오자. 즉 `index=0`을 사용하지 말자.

In [464]:
url = 'https://raw.githubusercontent.com/PacktPublishing/Pandas-Cookbook-Second-Edition/master/data/state_fruit.csv'
state_fruit = pd.read_csv(url)  #state_fruit = pd.read_csv(url,index_col=0) 
state_fruit

  Unnamed: 0  Apple  Orange  Banana
0      Texas     12      10      40
1    Arizona      9       7      12
2    Florida      0      14     190

In [465]:
state_fruit.columns.values

array(['Unnamed: 0', 'Apple', 'Orange', 'Banana'], dtype=object)

In [467]:
state_fruit=state_fruit.rename(columns={'Unnamed: 0':'G1'})
state_fruit

        G1  Apple  Orange  Banana
0    Texas     12      10      40
1  Arizona      9       7      12
2  Florida      0      14     190

In [473]:
state_fruit=state_fruit.melt(id_vars=['G1'])
state_fruit

        G1 variable  value
0    Texas    Apple     12
1  Arizona    Apple      9
2  Florida    Apple      0
3    Texas   Orange     10
4  Arizona   Orange      7
5  Florida   Orange     14
6    Texas   Banana     40
7  Arizona   Banana     12
8  Florida   Banana    190

In [1]:
state_fruit.rename(columns={'variable':'G2','value':'X1'})

NameError: name 'state_fruit' is not defined

#### 예제: state_fruit2

(문제)

https://github.com/PacktPublishing/Pandas-Cookbook-Second-Edition/blob/master/data/state_fruit2.csv

`-` 문제의 깃헙주소로 들어가서 데이터를 관찰 $\to$ 좌측상단이 'State'로 채워져있음 $\to$ 데이터를 읽을때 `index_col=0` 옵션을 사용하지 않음.

In [426]:
url = 'https://raw.githubusercontent.com/PacktPublishing/Pandas-Cookbook-Second-Edition/master/data/state_fruit2.csv'
state_fruit2 = pd.read_csv(url) # 문제의 주소로 들어가서 데이터를 살펴보자 -> 좌측상단이 채워짐 -> index_col=0 으로 불러오지 않음. 
state_fruit2

     State  Apple  Orange  Banana
0    Texas     12      10      40
1  Arizona      9       7      12
2  Florida      0      14     190

- index1: `{State: [Texas, Arizona, Florida]}` = row
- index2: `{??? :[Apple, Orange, Banana]}` = col

(풀이1)

In [433]:
state_fruit2.melt()

   variable    value
0     State    Texas
1     State  Arizona
2     State  Florida
3     Apple       12
4     Apple        9
5     Apple        0
6    Orange       10
7    Orange        7
8    Orange       14
9    Banana       40
10   Banana       12
11   Banana      190

In [434]:
state_fruit2.melt(id_vars=['State'])

     State variable  value
0    Texas    Apple     12
1  Arizona    Apple      9
2  Florida    Apple      0
3    Texas   Orange     10
4  Arizona   Orange      7
5  Florida   Orange     14
6    Texas   Banana     40
7  Arizona   Banana     12
8  Florida   Banana    190

In [ ]:
-

In [435]:
state_fruit2.melt(id_vars=['State'],var_name='Fruit')

     State   Fruit  value
0    Texas   Apple     12
1  Arizona   Apple      9
2  Florida   Apple      0
3    Texas  Orange     10
4  Arizona  Orange      7
5  Florida  Orange     14
6    Texas  Banana     40
7  Arizona  Banana     12
8  Florida  Banana    190

In [437]:
state_fruit2.melt(id_vars=['State'],var_name='Fruit',value_name='Weight')

     State   Fruit  Weight
0    Texas   Apple      12
1  Arizona   Apple       9
2  Florida   Apple       0
3    Texas  Orange      10
4  Arizona  Orange       7
5  Florida  Orange      14
6    Texas  Banana      40
7  Arizona  Banana      12
8  Florida  Banana     190

In [436]:
state_fruit2.melt(id_vars=['State'],value_vars=['Orange','Apple','Banana'])

     State variable  value
0    Texas   Orange     10
1  Arizona   Orange      7
2  Florida   Orange     14
3    Texas    Apple     12
4  Arizona    Apple      9
5  Florida    Apple      0
6    Texas   Banana     40
7  Arizona   Banana     12
8  Florida   Banana    190

***melt를 이용하여 데이터를 깨끗하게 만들기 위한 작전 (변형하고 싶은 데이터의 형태가 직관적으로 떠오르지 않을 경우)***

`*` Step1: [State, Apple, Orange, Banana] 중 하나의 변수를 선택하여 index1로 설정한다. 
- 요령1: [State, Apple, Orange, Banana] 중에서 숫자를 값으로 가지는 변수명은 제외한다. $\to$ 여기에서 Apple, Orange, Banana가 제외됨. 
- 요령2: 여기서 선택되는 변수가 `G1`자리에 들어온다. `G1`자리에 어울릴만한 변수를 선택.

`*` Step2: melt()사용. 필수옵션은 `id_vars`, `var_name`. 
- `id_vars`: Step1에서 선택한 변수이름, 즉 State. `G1`에 해당하는 변수명. 
- `var_name`: Step1에서 선택한 변수를 제외한 나머지 변수명(즉 [Apple, Orange, Banana])을 통합할 만한 변수이름을 '새롭게 정의함'. 이름이 잘 생각안나면 그냥 `G2`로 정하자. 
- `value_name`: 설정안해도 무방. `X1`자리의 이름임. `X1`에 적당한 이름을 주면 된다.

## VI. visualization