# (노트) pandas - select columns 

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- categories: [파이썬]

### import

In [25]:
import pandas as pd
import numpy as np

### numpy로 indexing

In [24]:
url='https://raw.githubusercontent.com/PacktPublishing/Pandas-Cookbook-Second-Edition/master/data/movie.csv'
df = pd.read_csv(url)
data=df.to_numpy()
data

array([['Color', 'James Cameron', 723.0, ..., 7.9, 1.78, 33000],
       ['Color', 'Gore Verbinski', 302.0, ..., 7.1, 2.35, 0],
       ['Color', 'Sam Mendes', 602.0, ..., 6.8, 2.35, 85000],
       ...,
       ['Color', 'Benjamin Roberds', 13.0, ..., 6.3, nan, 16],
       ['Color', 'Daniel Hsia', 14.0, ..., 6.3, 2.35, 660],
       ['Color', 'Jon Gunn', 43.0, ..., 6.6, 1.85, 456]], dtype=object)

In [18]:
data[0] ## first observation

array(['Color', 'James Cameron', 723.0, 178.0, 0.0, 855.0,
       'Joel David Moore', 1000.0, 760505847.0,
       'Action|Adventure|Fantasy|Sci-Fi', 'CCH Pounder', 'Avatar', 886204,
       4834, 'Wes Studi', 0.0, 'avatar|future|marine|native|paraplegic',
       'http://www.imdb.com/title/tt0499549/?ref_=fn_tt_tt_1', 3054.0,
       'English', 'USA', 'PG-13', 237000000.0, 2009.0, 936.0, 7.9, 1.78,
       33000], dtype=object)

In [19]:
data[0,:] ## first observation

array(['Color', 'James Cameron', 723.0, 178.0, 0.0, 855.0,
       'Joel David Moore', 1000.0, 760505847.0,
       'Action|Adventure|Fantasy|Sci-Fi', 'CCH Pounder', 'Avatar', 886204,
       4834, 'Wes Studi', 0.0, 'avatar|future|marine|native|paraplegic',
       'http://www.imdb.com/title/tt0499549/?ref_=fn_tt_tt_1', 3054.0,
       'English', 'USA', 'PG-13', 237000000.0, 2009.0, 936.0, 7.9, 1.78,
       33000], dtype=object)

In [20]:
data.T[0] # first variable

array(['Color', 'Color', 'Color', ..., 'Color', 'Color', 'Color'],
      dtype=object)

In [21]:
data[:,0] # first variable

array(['Color', 'Color', 'Color', ..., 'Color', 'Color', 'Color'],
      dtype=object)

In [22]:
data[0][0] # (first observation, first variable)

'Color'

### 예제1: 하나의 열을 선택

In [11]:
dic={'X1':np.random.normal(0,1,5), 
     'X2':np.random.normal(0,1,5),
     'X3':np.random.normal(0,1,5)}
df=pd.DataFrame(dic)
df

         X1        X2        X3
0  1.503425 -0.452285 -0.849588
1  0.580809  0.634236  1.402876
2 -0.805731  0.366918 -0.928336
3  0.014254 -1.072588  0.324546
4 -2.108220 -0.319980  0.262438

`-` 방법1

In [12]:
df.X1

0    1.503425
1    0.580809
2   -0.805731
3    0.014254
4   -2.108220
Name: X1, dtype: float64

`-` 방법2

In [13]:
df['X1']

0    1.503425
1    0.580809
2   -0.805731
3    0.014254
4   -2.108220
Name: X1, dtype: float64

`-` 방법3

In [14]:
df[['X1']]

         X1
0  1.503425
1  0.580809
2 -0.805731
3  0.014254
4 -2.108220

- `df['X1']`는 series를 리턴하고 `df[['X1']]`는 dataframe을 리턴한다.

`-` 방법4

In [15]:
df.loc[:,'X1']

0    1.503425
1    0.580809
2   -0.805731
3    0.014254
4   -2.108220
Name: X1, dtype: float64

`-` 방법5

In [16]:
df.loc[:,['X1']]

         X1
0  1.503425
1  0.580809
2 -0.805731
3  0.014254
4 -2.108220

- `df.loc[:,'X1']`는 series를 리턴하고 `df[['X1']]`는 dataframe을 리턴한다.

`-` 방법6

In [17]:
df.loc[:,[True,False,False]]

         X1
0  1.503425
1  0.580809
2 -0.805731
3  0.014254
4 -2.108220

- 불인덱싱가능

`-` 방법7

In [18]:
df.iloc[:,0]

0    1.503425
1    0.580809
2   -0.805731
3    0.014254
4   -2.108220
Name: X1, dtype: float64

`-` 방법8

In [19]:
df.iloc[:,[0]]

         X1
0  1.503425
1  0.580809
2 -0.805731
3  0.014254
4 -2.108220

`-` 방법9

In [20]:
df.iloc[:,[True,False,False]]

         X1
0  1.503425
1  0.580809
2 -0.805731
3  0.014254
4 -2.108220

**참고: 열이름이 integer일 경우**

In [21]:
_df = pd.DataFrame(np.array([[1,2,3],[3,4,5],[5,6,7]]))
_df

   0  1  2
0  1  2  3
1  3  4  5
2  5  6  7

`-` 아래가 모두 가능

In [22]:
_df[0]

0    1
1    3
2    5
Name: 0, dtype: int64

In [23]:
_df[[0]]

   0
0  1
1  3
2  5

In [24]:
_df.loc[:,[0]]

   0
0  1
1  3
2  5

In [25]:
_df.iloc[:,[0]]

   0
0  1
1  3
2  5

**방법 1~9의 요약**

- `df.X1` 이 가장 간단하고 편리함. 그런데 변수이름을 알고 있어야 한다는 단점이 있음. 
- `df.X1` 은 변수이름에 `.`이 포함된 경우는 사용불가. 그밖에도 변수이름에 공백이 있는등 이상한 형태의 변수이름에는 사용불가능.

### 예제2: `df`에서 1,2,3열을 선택

In [26]:
dic={'X1':np.random.normal(0,1,5), 
     'X2':np.random.normal(0,1,5),
     'X3':np.random.normal(0,1,5),
     'X4':np.random.normal(0,1,5)
    }
df=pd.DataFrame(dic)
df

         X1        X2        X3        X4
0 -1.907817 -0.790811 -0.246227 -1.113627
1  1.650106 -1.747030  1.336080 -1.421119
2 -0.282799 -1.920867  0.040738 -0.195458
3 -0.948650 -0.027383  0.483993  0.224683
4 -0.989510 -1.040666 -1.327560  0.497181

`-` 방법1

In [27]:
df[['X1','X2','X3']]

         X1        X2        X3
0 -1.907817 -0.790811 -0.246227
1  1.650106 -1.747030  1.336080
2 -0.282799 -1.920867  0.040738
3 -0.948650 -0.027383  0.483993
4 -0.989510 -1.040666 -1.327560

위와 동일한 문법을 응용하면

In [28]:
varlist=['X'+i for i in '123']
varlist

['X1', 'X2', 'X3']

In [29]:
df[varlist]

         X1        X2        X3
0 -1.907817 -0.790811 -0.246227
1  1.650106 -1.747030  1.336080
2 -0.282799 -1.920867  0.040738
3 -0.948650 -0.027383  0.483993
4 -0.989510 -1.040666 -1.327560

`-` 방법2

In [30]:
df.loc[:,['X1','X2','X3']]

         X1        X2        X3
0 -1.907817 -0.790811 -0.246227
1  1.650106 -1.747030  1.336080
2 -0.282799 -1.920867  0.040738
3 -0.948650 -0.027383  0.483993
4 -0.989510 -1.040666 -1.327560

`-` 방법3

In [31]:
df.loc[:,'X1':'X3']

         X1        X2        X3
0 -1.907817 -0.790811 -0.246227
1  1.650106 -1.747030  1.336080
2 -0.282799 -1.920867  0.040738
3 -0.948650 -0.027383  0.483993
4 -0.989510 -1.040666 -1.327560

`-` 방법4

In [32]:
df.loc[:,[True,True,True,False]]

         X1        X2        X3
0 -1.907817 -0.790811 -0.246227
1  1.650106 -1.747030  1.336080
2 -0.282799 -1.920867  0.040738
3 -0.948650 -0.027383  0.483993
4 -0.989510 -1.040666 -1.327560

응용하면 아래도 가능하다

In [33]:
_cols=df.columns.to_list()
_cols

['X1', 'X2', 'X3', 'X4']

In [34]:
import re

In [35]:
re.match('X',_cols[0])

`-` 방법5

In [36]:
df.iloc[:,[0,1,2]]

         X1        X2        X3
0 -1.907817 -0.790811 -0.246227
1  1.650106 -1.747030  1.336080
2 -0.282799 -1.920867  0.040738
3 -0.948650 -0.027383  0.483993
4 -0.989510 -1.040666 -1.327560

이 방법을 응용하면

In [37]:
idx = range(3)
idx

range(0, 3)

In [38]:
df.iloc[:,idx]

         X1        X2        X3
0 -1.907817 -0.790811 -0.246227
1  1.650106 -1.747030  1.336080
2 -0.282799 -1.920867  0.040738
3 -0.948650 -0.027383  0.483993
4 -0.989510 -1.040666 -1.327560

In [39]:
idx = np.arange(3)
idx

array([0, 1, 2])

In [40]:
df.iloc[:,idx]

         X1        X2        X3
0 -1.907817 -0.790811 -0.246227
1  1.650106 -1.747030  1.336080
2 -0.282799 -1.920867  0.040738
3 -0.948650 -0.027383  0.483993
4 -0.989510 -1.040666 -1.327560

In [41]:
idx = np.arange(3.)
idx

array([0., 1., 2.])

In [42]:
df.iloc[:,idx]

         X1        X2        X3
0 -1.907817 -0.790811 -0.246227
1  1.650106 -1.747030  1.336080
2 -0.282799 -1.920867  0.040738
3 -0.948650 -0.027383  0.483993
4 -0.989510 -1.040666 -1.327560

- idx의 값이 float형으로 저장되어 있어도 에러나지 않음

`-` 방법6

In [43]:
df.iloc[:,[True,True,True,False]]

         X1        X2        X3
0 -1.907817 -0.790811 -0.246227
1  1.650106 -1.747030  1.336080
2 -0.282799 -1.920867  0.040738
3 -0.948650 -0.027383  0.483993
4 -0.989510 -1.040666 -1.327560

**(주의) loc에서의 슬라이싱은 마지막변수를 포함하지만 iloc에서는 포함하지 않음.**

`-` 아래를 비교하라.

In [44]:
df.iloc[:,0:3] ## 3은 포함되지 않는다.

         X1        X2        X3
0 -1.907817 -0.790811 -0.246227
1  1.650106 -1.747030  1.336080
2 -0.282799 -1.920867  0.040738
3 -0.948650 -0.027383  0.483993
4 -0.989510 -1.040666 -1.327560

In [45]:
df.loc[:,'X1':'X3'] ## 'X3'이 포함된다.

         X1        X2        X3
0 -1.907817 -0.790811 -0.246227
1  1.650106 -1.747030  1.336080
2 -0.282799 -1.920867  0.040738
3 -0.948650 -0.027383  0.483993
4 -0.989510 -1.040666 -1.327560

`-` 그래서 column의 이름이 integer일 경우는 종종 매우 헷갈리는 결과가 나옴

In [46]:
_df = pd.DataFrame(np.array([[1,2,3,4],[3,4,5,6],[5,6,7,8]]))
_df

   0  1  2  3
0  1  2  3  4
1  3  4  5  6
2  5  6  7  8

In [47]:
_df.loc[:,0:2]

   0  1  2
0  1  2  3
1  3  4  5
2  5  6  7

In [48]:
_df.iloc[:,0:2]

   0  1
0  1  2
1  3  4
2  5  6

> note: 사실 이것은 일부러 헷갈리게 예제를 구성한것이다. 실제로는 헷갈리는 상황이 많이 발생하지 않는다. 왜냐하면 보통 위의 예제와 같은 경우에는 ndarray로 처리하고 colname이 있는 경우만 데이터프레임으로 처리하기 때문

**방법 1~6의 요약**

`-` 내가 생각할때 가장 독특한 방법은 아래이다. (그런데 컬럼이름 양옆에 따옴표를 붙이는 것이 불편함)

In [49]:
df.loc[:,'X1':'X3']

         X1        X2        X3
0 -1.907817 -0.790811 -0.246227
1  1.650106 -1.747030  1.336080
2 -0.282799 -1.920867  0.040738
3 -0.948650 -0.027383  0.483993
4 -0.989510 -1.040666 -1.327560

- 이방법은 오로지 판다스에서만 가능하다.

`-` 변수이름이 순서대로 정리되어 있지 않아도 사용할 수 있다.

In [50]:
_dic={'Y1':np.random.normal(0,1,5), 
      'Y2':np.random.normal(0,1,5),
      'X1':np.random.normal(0,1,5),
      'X2':np.random.normal(0,1,5)}
_df=pd.DataFrame(_dic)
_df

         Y1        Y2        X1        X2
0 -0.734773 -1.599649  0.518970 -1.662894
1  0.679337 -0.130844 -0.985108 -0.110248
2 -1.264149 -0.085269 -2.574022  0.011470
3 -0.525075 -0.349322  0.250697 -0.756816
4  1.238033  0.812356 -0.114869  1.020324

In [51]:
_df.loc[:,'Y1':'X1']

         Y1        Y2        X1
0 -0.734773 -1.599649  0.518970
1  0.679337 -0.130844 -0.985108
2 -1.264149 -0.085269 -2.574022
3 -0.525075 -0.349322  0.250697
4  1.238033  0.812356 -0.114869

### 예제3: movie data - 특정조건에 맞는 열을 선택

In [5]:
url='https://raw.githubusercontent.com/PacktPublishing/Pandas-Cookbook-Second-Edition/master/data/movie.csv'
df = pd.read_csv(url)
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

`-` 열의 이름을 출력해보자.

In [6]:
cols=df.columns.to_list()
cols

['color',
 'director_name',
 'num_critic_for_reviews',
 'duration',
 'director_facebook_likes',
 'actor_3_facebook_likes',
 'actor_2_name',
 'actor_1_facebook_likes',
 'gross',
 'genres',
 'actor_1_name',
 'movie_title',
 'num_voted_users',
 'cast_total_facebook_likes',
 'actor_3_name',
 'facenumber_in_poster',
 'plot_keywords',
 'movie_imdb_link',
 'num_user_for_reviews',
 'language',
 'country',
 'content_rating',
 'budget',
 'title_year',
 'actor_2_facebook_likes',
 'imdb_score',
 'aspect_ratio',
 'movie_facebook_likes']

`-` 팁: 열의 이름을 인덱스와 함께 출력하기 위해서는 아래와 같이 하면 쉽다.

In [7]:
pd.Series(cols)

0                         color
1                 director_name
2        num_critic_for_reviews
3                      duration
4       director_facebook_likes
5        actor_3_facebook_likes
6                  actor_2_name
7        actor_1_facebook_likes
8                         gross
9                        genres
10                 actor_1_name
11                  movie_title
12              num_voted_users
13    cast_total_facebook_likes
14                 actor_3_name
15         facenumber_in_poster
16                plot_keywords
17              movie_imdb_link
18         num_user_for_reviews
19                     language
20                      country
21               content_rating
22                       budget
23                   title_year
24       actor_2_facebook_likes
25                   imdb_score
26                 aspect_ratio
27         movie_facebook_likes
dtype: object

`-` actor로 시작하는 변수들을 뽑아보자.

In [8]:
_cols = list(filter(lambda x: 'actor' in x[:5] , cols))
_cols

['actor_3_facebook_likes',
 'actor_2_name',
 'actor_1_facebook_likes',
 'actor_1_name',
 'actor_3_name',
 'actor_2_facebook_likes']

In [9]:
df.loc[:, _cols]

,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,actor_1_name,actor_3_name,actor_2_facebook_likes
0,855.0,Joel David Moore,1000.0,CCH Pounder,Wes Studi,936.0
1,1000.0,Orlando Bloom,40000.0,Johnny Depp,Jack Davenport,5000.0
2,161.0,Rory Kinnear,11000.0,Christoph Waltz,Stephanie Sigman,393.0
3,23000.0,Christian Bale,27000.0,Tom Hardy,Joseph Gordon-Levitt,23000.0
4,NaN,Rob Walker,131.0,Doug Walker,NaN,12.0
...,...,...,...,...,...,...
4911,318.0,Daphne Zuniga,637.0,Eric Mabius,Crystal Lowe,470.0
4912,319.0,Valorie Curry,841.0,Natalie Zea,Sam Underwood,593.0
4913,0.0,Maxwell Moody,0.0,Eva Boehnke,David Chandler,0.0
4914,489.0,Daniel Henney,946.0,Alan Ruck,Eliza Coupe,719.0
4915,16.0,Brian Herzlinger,86.0,John August,Jon Gunn,23.0

또는 아래와 같이 할 수 있다.

In [10]:
_bools = list(map(lambda x: 'actor' in x[:5] , cols))
print(_bools)
display(df.loc[:,_bools])
display(df.iloc[:,_bools])

[False, False, False, False, False, True, True, True, False, False, True, False, False, False, True, False, False, False, False, False, False, False, False, False, True, False, False, False]

,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,actor_1_name,actor_3_name,actor_2_facebook_likes
0,855.0,Joel David Moore,1000.0,CCH Pounder,Wes Studi,936.0
1,1000.0,Orlando Bloom,40000.0,Johnny Depp,Jack Davenport,5000.0
2,161.0,Rory Kinnear,11000.0,Christoph Waltz,Stephanie Sigman,393.0
3,23000.0,Christian Bale,27000.0,Tom Hardy,Joseph Gordon-Levitt,23000.0
4,NaN,Rob Walker,131.0,Doug Walker,NaN,12.0
...,...,...,...,...,...,...
4911,318.0,Daphne Zuniga,637.0,Eric Mabius,Crystal Lowe,470.0
4912,319.0,Valorie Curry,841.0,Natalie Zea,Sam Underwood,593.0
4913,0.0,Maxwell Moody,0.0,Eva Boehnke,David Chandler,0.0
4914,489.0,Daniel Henney,946.0,Alan Ruck,Eliza Coupe,719.0
4915,16.0,Brian Herzlinger,86.0,John August,Jon Gunn,23.0

,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,actor_1_name,actor_3_name,actor_2_facebook_likes
0,855.0,Joel David Moore,1000.0,CCH Pounder,Wes Studi,936.0
1,1000.0,Orlando Bloom,40000.0,Johnny Depp,Jack Davenport,5000.0
2,161.0,Rory Kinnear,11000.0,Christoph Waltz,Stephanie Sigman,393.0
3,23000.0,Christian Bale,27000.0,Tom Hardy,Joseph Gordon-Levitt,23000.0
4,NaN,Rob Walker,131.0,Doug Walker,NaN,12.0
...,...,...,...,...,...,...
4911,318.0,Daphne Zuniga,637.0,Eric Mabius,Crystal Lowe,470.0
4912,319.0,Valorie Curry,841.0,Natalie Zea,Sam Underwood,593.0
4913,0.0,Maxwell Moody,0.0,Eva Boehnke,David Chandler,0.0
4914,489.0,Daniel Henney,946.0,Alan Ruck,Eliza Coupe,719.0
4915,16.0,Brian Herzlinger,86.0,John August,Jon Gunn,23.0

`-` imdb가 포함된 변수들만 뽑아보자.

In [11]:
_cols = list(filter(lambda x: 'imdb' in x , cols))
_cols

['movie_imdb_link', 'imdb_score']

In [12]:
df.loc[:,_cols]

                                        movie_imdb_link  imdb_score
0     http://www.imdb.com/title/tt0499549/?ref_=fn_t...         7.9
1     http://www.imdb.com/title/tt0449088/?ref_=fn_t...         7.1
2     http://www.imdb.com/title/tt2379713/?ref_=fn_t...         6.8
3     http://www.imdb.com/title/tt1345836/?ref_=fn_t...         8.5
4     http://www.imdb.com/title/tt5289954/?ref_=fn_t...         7.1
...                                                 ...         ...
4911  http://www.imdb.com/title/tt3000844/?ref_=fn_t...         7.7
4912  http://www.imdb.com/title/tt2071645/?ref_=fn_t...         7.5
4913  http://www.imdb.com/title/tt2107644/?ref_=fn_t...         6.3
4914  http://www.imdb.com/title/tt2070597/?ref_=fn_t...         6.3
4915  http://www.imdb.com/title/tt0378407/?ref_=fn_t...         6.6

[4916 rows x 2 columns]

또는 아래와 같이 할 수 있다.

In [13]:
_bools = list(map(lambda x: 'imdb' in x , cols))
print(_bools)
display(df.loc[:,_bools])
display(df.iloc[:,_bools])

[False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, True, False, False]

                                        movie_imdb_link  imdb_score
0     http://www.imdb.com/title/tt0499549/?ref_=fn_t...         7.9
1     http://www.imdb.com/title/tt0449088/?ref_=fn_t...         7.1
2     http://www.imdb.com/title/tt2379713/?ref_=fn_t...         6.8
3     http://www.imdb.com/title/tt1345836/?ref_=fn_t...         8.5
4     http://www.imdb.com/title/tt5289954/?ref_=fn_t...         7.1
...                                                 ...         ...
4911  http://www.imdb.com/title/tt3000844/?ref_=fn_t...         7.7
4912  http://www.imdb.com/title/tt2071645/?ref_=fn_t...         7.5
4913  http://www.imdb.com/title/tt2107644/?ref_=fn_t...         6.3
4914  http://www.imdb.com/title/tt2070597/?ref_=fn_t...         6.3
4915  http://www.imdb.com/title/tt0378407/?ref_=fn_t...         6.6

[4916 rows x 2 columns]

                                        movie_imdb_link  imdb_score
0     http://www.imdb.com/title/tt0499549/?ref_=fn_t...         7.9
1     http://www.imdb.com/title/tt0449088/?ref_=fn_t...         7.1
2     http://www.imdb.com/title/tt2379713/?ref_=fn_t...         6.8
3     http://www.imdb.com/title/tt1345836/?ref_=fn_t...         8.5
4     http://www.imdb.com/title/tt5289954/?ref_=fn_t...         7.1
...                                                 ...         ...
4911  http://www.imdb.com/title/tt3000844/?ref_=fn_t...         7.7
4912  http://www.imdb.com/title/tt2071645/?ref_=fn_t...         7.5
4913  http://www.imdb.com/title/tt2107644/?ref_=fn_t...         6.3
4914  http://www.imdb.com/title/tt2070597/?ref_=fn_t...         6.3
4915  http://www.imdb.com/title/tt0378407/?ref_=fn_t...         6.6

[4916 rows x 2 columns]

`-` likes로 끝나는 변수들을 뽑아보자.

In [14]:
_cols = list(filter(lambda x: 'likes' in x[-5:] , cols))
_cols

['director_facebook_likes',
 'actor_3_facebook_likes',
 'actor_1_facebook_likes',
 'cast_total_facebook_likes',
 'actor_2_facebook_likes',
 'movie_facebook_likes']

In [15]:
df.loc[:,_cols]

,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,cast_total_facebook_likes,actor_2_facebook_likes,movie_facebook_likes
0,0.0,855.0,1000.0,4834,936.0,33000
1,563.0,1000.0,40000.0,48350,5000.0,0
2,0.0,161.0,11000.0,11700,393.0,85000
3,22000.0,23000.0,27000.0,106759,23000.0,164000
4,131.0,NaN,131.0,143,12.0,0
...,...,...,...,...,...,...
4911,2.0,318.0,637.0,2283,470.0,84
4912,NaN,319.0,841.0,1753,593.0,32000
4913,0.0,0.0,0.0,0,0.0,16
4914,0.0,489.0,946.0,2386,719.0,660
4915,16.0,16.0,86.0,163,23.0,456

또는 아래와 같이 할 수 있다.

In [16]:
_bools = list(map(lambda x: 'likes' in x[-5:] , cols))
print(_bools)
display(df.loc[:,_bools])
display(df.iloc[:,_bools])

[False, False, False, False, True, True, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, True, False, False, True]

,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,cast_total_facebook_likes,actor_2_facebook_likes,movie_facebook_likes
0,0.0,855.0,1000.0,4834,936.0,33000
1,563.0,1000.0,40000.0,48350,5000.0,0
2,0.0,161.0,11000.0,11700,393.0,85000
3,22000.0,23000.0,27000.0,106759,23000.0,164000
4,131.0,NaN,131.0,143,12.0,0
...,...,...,...,...,...,...
4911,2.0,318.0,637.0,2283,470.0,84
4912,NaN,319.0,841.0,1753,593.0,32000
4913,0.0,0.0,0.0,0,0.0,16
4914,0.0,489.0,946.0,2386,719.0,660
4915,16.0,16.0,86.0,163,23.0,456

,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,cast_total_facebook_likes,actor_2_facebook_likes,movie_facebook_likes
0,0.0,855.0,1000.0,4834,936.0,33000
1,563.0,1000.0,40000.0,48350,5000.0,0
2,0.0,161.0,11000.0,11700,393.0,85000
3,22000.0,23000.0,27000.0,106759,23000.0,164000
4,131.0,NaN,131.0,143,12.0,0
...,...,...,...,...,...,...
4911,2.0,318.0,637.0,2283,470.0,84
4912,NaN,319.0,841.0,1753,593.0,32000
4913,0.0,0.0,0.0,0,0.0,16
4914,0.0,489.0,946.0,2386,719.0,660
4915,16.0,16.0,86.0,163,23.0,456