# (노트) 판다스 - 행선택 

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- hide: false
- categories: [파이썬]

### import

In [2]:
import numpy as np
import pandas as pd

### 첫번째 행을 선택하는 방법

In [3]:
dic={'X1':np.random.normal(0,1,5), 
     'X2':np.random.normal(0,1,5),
     'X3':np.random.normal(0,1,5),
     'X4':np.random.normal(0,1,5),
     'X5':np.random.normal(0,1,5),  
     'X6':np.random.normal(0,1,5)
    }
df1=pd.DataFrame(dic)
df1

         X1        X2        X3        X4        X5        X6
0  0.379501  0.494396 -0.506120 -0.944683 -0.956560  0.762222
1  1.213642  0.155406  0.667611  0.517425  0.531747  0.310939
2  0.422227  0.618214  0.265054 -0.434589  0.614729 -0.050697
3  1.533960  1.677501 -1.032213  0.351609  0.732322  0.978424
4 -2.001326 -1.458116 -0.573582  0.499791  0.213391 -1.014252

`-` 방법1

In [4]:
df1.iloc[0] # 이상해

X1    0.379501
X2    0.494396
X3   -0.506120
X4   -0.944683
X5   -0.956560
X6    0.762222
Name: 0, dtype: float64

`-` 방법2

In [5]:
df1.iloc[0,:]

X1    0.379501
X2    0.494396
X3   -0.506120
X4   -0.944683
X5   -0.956560
X6    0.762222
Name: 0, dtype: float64

`-` 방법3

In [6]:
df1.iloc[[0]]

         X1        X2       X3        X4       X5        X6
0  0.379501  0.494396 -0.50612 -0.944683 -0.95656  0.762222

`-` 방법4

In [7]:
df1.iloc[[0],:]

         X1        X2       X3        X4       X5        X6
0  0.379501  0.494396 -0.50612 -0.944683 -0.95656  0.762222

`-` 방법5

In [8]:
df1.loc[0]

X1    0.379501
X2    0.494396
X3   -0.506120
X4   -0.944683
X5   -0.956560
X6    0.762222
Name: 0, dtype: float64

`-` 방법6

In [9]:
df1.loc[0,:]

X1    0.379501
X2    0.494396
X3   -0.506120
X4   -0.944683
X5   -0.956560
X6    0.762222
Name: 0, dtype: float64

`-` 방법7

In [10]:
df1.loc[[0]]

         X1        X2       X3        X4       X5        X6
0  0.379501  0.494396 -0.50612 -0.944683 -0.95656  0.762222

`-` 방법8

In [11]:
df1.loc[[0],:]

         X1        X2       X3        X4       X5        X6
0  0.379501  0.494396 -0.50612 -0.944683 -0.95656  0.762222

`-` 방법9

In [12]:
df1.loc[[True,False,False,False,False],:]

         X1        X2       X3        X4       X5        X6
0  0.379501  0.494396 -0.50612 -0.944683 -0.95656  0.762222

`-` 방법10

In [13]:
df1.loc[[True,False,False,False,False]]

         X1        X2       X3        X4       X5        X6
0  0.379501  0.494396 -0.50612 -0.944683 -0.95656  0.762222

`-` 방법11

In [14]:
df1.iloc[[True,False,False,False,False],:]

         X1        X2       X3        X4       X5        X6
0  0.379501  0.494396 -0.50612 -0.944683 -0.95656  0.762222

`-` 방법12

In [15]:
df1.iloc[[True,False,False,False,False]]

         X1        X2       X3        X4       X5        X6
0  0.379501  0.494396 -0.50612 -0.944683 -0.95656  0.762222

### 여러개의 1,3행을 선택하는 방법

`-` 방법1

In [18]:
df1.loc[[0,2],:]

         X1        X2        X3        X4        X5        X6
0  0.379501  0.494396 -0.506120 -0.944683 -0.956560  0.762222
2  0.422227  0.618214  0.265054 -0.434589  0.614729 -0.050697

`-` 방법2

In [19]:
df1.iloc[[0,2],:]

         X1        X2        X3        X4        X5        X6
0  0.379501  0.494396 -0.506120 -0.944683 -0.956560  0.762222
2  0.422227  0.618214  0.265054 -0.434589  0.614729 -0.050697

`-` 불인덱싱, 슬라이싱도 가능함. (이것들은 생략할게요~)

#### loc vs iloc ??

`-` 위의 경우는 row의 인덱스이름이 정수인 경우임

`-` 정수가 아닌 경우

In [20]:
_df= pd.DataFrame({'A':[1,2,3],'B':[4,5,6]},index=list('abc'))
_df

   A  B
a  1  4
b  2  5
c  3  6

In [21]:
_df.loc[['a','b'],:]

   A  B
a  1  4
b  2  5

In [22]:
_df.iloc[[0,1],:]

   A  B
a  1  4
b  2  5

`-` 대부분의 경우 obervatio에 특정한 이름이 있는 경우는 없으므로 loc이 그다지 쓸모 없음

`-` 그렇지만 특정 경우에는 쓸모 있음

In [23]:
_df=pd.DataFrame(np.random.randn(20,4),columns=list('ABCD'),index=pd.date_range('20201225',periods=20))
_df

                   A         B         C         D
2020-12-25  1.272189 -0.754312 -0.347811  0.611944
2020-12-26 -0.406148  0.010089 -0.295499 -0.136403
2020-12-27 -1.216721 -0.470580  0.711822 -0.119125
2020-12-28 -0.205796  1.772613 -1.729415  1.783847
2020-12-29 -0.303640  1.674550 -0.458836 -0.412247
2020-12-30  0.785633 -0.368881 -1.995277 -0.599916
2020-12-31  0.170225 -0.636751  2.544430 -1.029227
2021-01-01  0.575042  0.861714  1.090717  0.334177
2021-01-02 -0.946147  0.219109  1.169939  0.869609
2021-01-03  0.609258 -0.653446  1.331541 -0.909926
2021-01-04  0.845029 -1.199362 -2.936850 -0.197011
2021-01-05  3.447651 -1.551133  0.445413  0.364367
2021-01-06 -0.264333  1.043092  0.462908  0.515472
2021-01-07 -1.355877 -0.893314  1.269725 -0.521313
2021-01-08  0.605179 -1.459240 -1.232659 -0.774998
2021-01-09 -0.592312 -0.814458 -0.676868  1.602603
2021-01-10  0.467987  0.802171  1.886093  0.327331
2021-01-11 -0.729894  0.067344  0.775511  0.212939
2021-01-12  1.035323  0.216158 -0.606175  0.331533
2021-01-13 -0.292210  1.579517 -0.001933  1.208735

`-` 1월5일부터 1월8일까지 자료만 보고 싶다!

In [27]:
_df.loc['20210105':'20210108']

                   A         B         C         D
2021-01-05  3.447651 -1.551133  0.445413  0.364367
2021-01-06 -0.264333  1.043092  0.462908  0.515472
2021-01-07 -1.355877 -0.893314  1.269725 -0.521313
2021-01-08  0.605179 -1.459240 -1.232659 -0.774998

`-` iloc으로 하려면 힘들다..

In [28]:
_df.index

DatetimeIndex(['2020-12-25', '2020-12-26', '2020-12-27', '2020-12-28',
               '2020-12-29', '2020-12-30', '2020-12-31', '2021-01-01',
               '2021-01-02', '2021-01-03', '2021-01-04', '2021-01-05',
               '2021-01-06', '2021-01-07', '2021-01-08', '2021-01-09',
               '2021-01-10', '2021-01-11', '2021-01-12', '2021-01-13'],
              dtype='datetime64[ns]', freq='D')

In [29]:
pd.Series(_df.index)

0    2020-12-25
1    2020-12-26
2    2020-12-27
3    2020-12-28
4    2020-12-29
5    2020-12-30
6    2020-12-31
7    2021-01-01
8    2021-01-02
9    2021-01-03
10   2021-01-04
11   2021-01-05
12   2021-01-06
13   2021-01-07
14   2021-01-08
15   2021-01-09
16   2021-01-10
17   2021-01-11
18   2021-01-12
19   2021-01-13
dtype: datetime64[ns]

In [30]:
_df.iloc[11:15] # 14으로하면 안된다. 마지막 인덱스가 포함되지 않으니까!

                   A         B         C         D
2021-01-05  3.447651 -1.551133  0.445413  0.364367
2021-01-06 -0.264333  1.043092  0.462908  0.515472
2021-01-07 -1.355877 -0.893314  1.269725 -0.521313
2021-01-08  0.605179 -1.459240 -1.232659 -0.774998

#### 자주하는 실수

`-` 나는 아래와 같은 실수를 많이함

In [31]:
_df.loc['A']

KeyError: 'A'

`-` 올바른 방법

In [32]:
_df['A']

2020-12-25    1.272189
2020-12-26   -0.406148
2020-12-27   -1.216721
2020-12-28   -0.205796
2020-12-29   -0.303640
2020-12-30    0.785633
2020-12-31    0.170225
2021-01-01    0.575042
2021-01-02   -0.946147
2021-01-03    0.609258
2021-01-04    0.845029
2021-01-05    3.447651
2021-01-06   -0.264333
2021-01-07   -1.355877
2021-01-08    0.605179
2021-01-09   -0.592312
2021-01-10    0.467987
2021-01-11   -0.729894
2021-01-12    1.035323
2021-01-13   -0.292210
Freq: D, Name: A, dtype: float64

- 이런방식이 사실 좀 이상해보여서 한번쓰기 시작하면 잘쓰는데 금방까먹고 다시 헷갈림

`-` 아래의 사실을 기억하자. 
- 기본적으로 loc, iloc은 `[2], [2:]` 처럼 1차원으로 원소를 인덱싱할수도 있고, `[2,3], [:,2]`와 같이 2차원으로 인덱싱 할수도 있다. 
- 1차원으로 인덱싱하는 경우는 기본적으로 행을 인덱싱한다. $\to$ **loc, iloc은 행과 더 친하고 열과 친하지 않다.**
- 따라서 열을 선택하는 방법에 있어서 loc, iloc이 그렇게 친화적인 방법은 아니다. 
- 그렇지만 달리 열을 선택하는 쉬운 방법이 존재하지 않아서 열을 선택할때에도 loc, iloc이 선호된다.

### 슬라이싱응용

In [33]:
_df=pd.DataFrame(np.random.randn(10,4),columns=list('ABCD'),index=pd.date_range('20210101',periods=10))
_df.iloc[::2]

                   A         B         C         D
2021-01-01  2.090245  0.043350 -1.310656 -1.223288
2021-01-03 -0.840721 -0.204628  0.004967 -0.242400
2021-01-05  0.853350  0.081821  2.487953  1.151741
2021-01-07  1.249576 -1.520192 -1.037832  2.929971
2021-01-09 -0.575585 -0.137101 -0.509573  0.610041

#### 이것은 칼럼에도 적용가능 $\to$ 그런데 잘 쓰지 않음

In [35]:
_df.iloc[:,::2]

                   A         C
2021-01-01  2.090245 -1.310656
2021-01-02  1.374729 -0.511960
2021-01-03 -0.840721  0.004967
2021-01-04  0.780807  1.030464
2021-01-05  0.853350  2.487953
2021-01-06  0.488383 -0.473703
2021-01-07  1.249576 -1.037832
2021-01-08 -0.154814  1.368490
2021-01-09 -0.575585 -0.509573
2021-01-10  1.865369 -0.408416

**잘 쓰지 않는 이유?**
- row를 특정 간격으로 뽑는 일은 빈번함 (예를들어 일별데이터를 주별데이터로 바꾸고 싶을 경우?) 
- col을 특정 간격으로 뽑아야 하는 일은 없음.

### lambda + map

In [36]:
df2 = pd.DataFrame(np.random.normal(size=(10,4)),columns=list('ABCD'))
df2

          A         B         C         D
0  1.711227  1.588095 -0.662286 -2.576030
1 -1.097585  0.649206 -0.803677 -0.284899
2  0.596792  0.594190 -0.758139 -1.320820
3  0.246444  1.239383 -0.428905  0.211941
4 -0.974224 -0.331926  0.608149  0.235054
5  0.302316 -1.253819  0.018625 -1.770304
6  0.834304  0.485799 -0.795757  0.886411
7  0.161218  0.736874  1.234518  0.124764
8  0.534933 -0.158519  0.401991 -0.618369
9 -0.358246 -0.710043  0.622054 -0.405878

#### 컬럼A의 값이 0보다 큰 경우만

`-` 방법1

In [38]:
df2.loc[map(lambda x: x>0, df2['A']),:]

          A         B         C         D
0  1.711227  1.588095 -0.662286 -2.576030
2  0.596792  0.594190 -0.758139 -1.320820
3  0.246444  1.239383 -0.428905  0.211941
5  0.302316 -1.253819  0.018625 -1.770304
6  0.834304  0.485799 -0.795757  0.886411
7  0.161218  0.736874  1.234518  0.124764
8  0.534933 -0.158519  0.401991 -0.618369

`-` 방법2

In [39]:
df2.loc[lambda df: df['A']>0, : ]

          A         B         C         D
0  1.711227  1.588095 -0.662286 -2.576030
2  0.596792  0.594190 -0.758139 -1.320820
3  0.246444  1.239383 -0.428905  0.211941
5  0.302316 -1.253819  0.018625 -1.770304
6  0.834304  0.485799 -0.795757  0.886411
7  0.161218  0.736874  1.234518  0.124764
8  0.534933 -0.158519  0.401991 -0.618369

- ?? 
- map의 기능은 (1) 리스트의 원소별로 (2) 함수를 적용하여 아웃풋을 구하고 (3) 나온 각각의 결과를 다시 하나의 리스트로 묶는 역할 
- 우리는 이중에서 (1), (3)에만 집중했음
- 하지만 생각해보면 일단 (2) 일단함수를 적용하는 기능이 있었음 
- **그런데 위의 코드를 보면 함수를 적용한 결과가 아니라 함수오브젝트 자체를 전달하여도 동작함**

***요약!!***
- True, False 로 이루어진 벡터를 리스트의 형태로 전달하여 인덱싱하면 당연히 가능 (원래 아는거) 
- True, False 로 이루어진 벡터로 포함된 리스트를 리턴할 수 있는 함수자체를 전달하여도 인덱싱 가능

`-` 방법3

In [41]:
df2.iloc[map(lambda x: x>0, df2['A']),:]

          A         B         C         D
0  1.711227  1.588095 -0.662286 -2.576030
2  0.596792  0.594190 -0.758139 -1.320820
3  0.246444  1.239383 -0.428905  0.211941
5  0.302316 -1.253819  0.018625 -1.770304
6  0.834304  0.485799 -0.795757  0.886411
7  0.161218  0.736874  1.234518  0.124764
8  0.534933 -0.158519  0.401991 -0.618369

`-` 방법4: 실패

In [85]:
df2.iloc[lambda df: df['A']>0,:]

NotImplementedError: iLocation based boolean indexing on an integer type is not available

- 위에서.. iloc을 loc으로 바꾸면 되는데.. 
- iloc입장에서 조금 서운하다..

#### 칼럼A>0 이고  칼럼B<0 인 경우

`-` 방법1

In [46]:
df2.loc[map(lambda x,y: x>0 and y<0, df2['A'],df2['B']),:]

          A         B         C         D
5  0.302316 -1.253819  0.018625 -1.770304
8  0.534933 -0.158519  0.401991 -0.618369

`-` 방법2

In [47]:
df2.loc[map(lambda x,y: x>0 & y<0, df2['A'],df2['B']),:]

TypeError: unsupported operand type(s) for &: 'int' and 'float'

- ??? 아래를 관찰

***보충학습***

In [48]:
0<3.2 & 0<2.2

TypeError: unsupported operand type(s) for &: 'float' and 'int'

In [49]:
(0<3.2) & (0<2.2)

True

***보충학습끝***

아래와 같이 수정하면 잘 된다.

In [50]:
df2.loc[map(lambda x,y: (x>0) & (y<0), df2['A'],df2['B']),:]

          A         B         C         D
5  0.302316 -1.253819  0.018625 -1.770304
8  0.534933 -0.158519  0.401991 -0.618369

`-` 방법3: 실패

In [51]:
df2.loc[lambda df: (df2['A']>0) and (df2['B']<0),:]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

- and는 벡터연산지원불가능

***보충학습***

In [52]:
np.array([True,False]) and np.array([True,False])

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [54]:
np.array([True,False]) & np.array([True,False])

array([ True, False])

***보충학습끝***

`-` 방법4

In [55]:
df2.loc[lambda df: (df2['A']>0) & (df2['B']<0),:]

          A         B         C         D
5  0.302316 -1.253819  0.018625 -1.770304
8  0.534933 -0.158519  0.401991 -0.618369

`-` iloc을 이용한 것은 생략

### query

#### 컬럼A>0, 컬럼B<0 인 경우 선택

`-` 방법1

In [56]:
df2.query('A>0 & B<0')

          A         B         C         D
5  0.302316 -1.253819  0.018625 -1.770304
8  0.534933 -0.158519  0.401991 -0.618369

`-` 방법2

In [57]:
df2.query('A>0 and B<0')

          A         B         C         D
5  0.302316 -1.253819  0.018625 -1.770304
8  0.534933 -0.158519  0.401991 -0.618369

#### A<B<C 를 필터

In [58]:
df2

          A         B         C         D
0  1.711227  1.588095 -0.662286 -2.576030
1 -1.097585  0.649206 -0.803677 -0.284899
2  0.596792  0.594190 -0.758139 -1.320820
3  0.246444  1.239383 -0.428905  0.211941
4 -0.974224 -0.331926  0.608149  0.235054
5  0.302316 -1.253819  0.018625 -1.770304
6  0.834304  0.485799 -0.795757  0.886411
7  0.161218  0.736874  1.234518  0.124764
8  0.534933 -0.158519  0.401991 -0.618369
9 -0.358246 -0.710043  0.622054 -0.405878

In [59]:
df2.query('A<B<C')

          A         B         C         D
4 -0.974224 -0.331926  0.608149  0.235054
7  0.161218  0.736874  1.234518  0.124764

#### A>mean(A) 선택: query 외부변수 사용

`-` 방법1

In [60]:
np.mean(df2.A)

0.19571785799422134

In [61]:
df2.query('A>0.5000069099552247')

          A         B         C         D
0  1.711227  1.588095 -0.662286 -2.576030
2  0.596792  0.594190 -0.758139 -1.320820
6  0.834304  0.485799 -0.795757  0.886411
8  0.534933 -0.158519  0.401991 -0.618369

`-` 방법2

In [62]:
mean_of_A=np.mean(df2.A)

In [63]:
df2.query('A > @mean_of_A')

          A         B         C         D
0  1.711227  1.588095 -0.662286 -2.576030
2  0.596792  0.594190 -0.758139 -1.320820
3  0.246444  1.239383 -0.428905  0.211941
5  0.302316 -1.253819  0.018625 -1.770304
6  0.834304  0.485799 -0.795757  0.886411
8  0.534933 -0.158519  0.401991 -0.618369

#### A>mean(A) 이고 A<1.8 인것을 선택

`-` 방법1

In [64]:
df2.query('A >  @mean_of_A and A<1.8')

          A         B         C         D
0  1.711227  1.588095 -0.662286 -2.576030
2  0.596792  0.594190 -0.758139 -1.320820
3  0.246444  1.239383 -0.428905  0.211941
5  0.302316 -1.253819  0.018625 -1.770304
6  0.834304  0.485799 -0.795757  0.886411
8  0.534933 -0.158519  0.401991 -0.618369

`-` 방법2 (가독성)

In [65]:
df2.query(
    " A >  @mean_of_A" 
    " and A<1.8"
)

          A         B         C         D
0  1.711227  1.588095 -0.662286 -2.576030
2  0.596792  0.594190 -0.758139 -1.320820
3  0.246444  1.239383 -0.428905  0.211941
5  0.302316 -1.253819  0.018625 -1.770304
6  0.834304  0.485799 -0.795757  0.886411
8  0.534933 -0.158519  0.401991 -0.618369

`-` 아래는 에러발생 (왜??)

In [67]:
df2.query(
    "A >  @mean_of_A" 
    "and A<1.8"
)

SyntaxError: invalid syntax (<unknown>, line 1)

- 컴퓨터가 이렇게 생각하기 때문

In [71]:
"A >  @mean_of_A""and A<1.8"

'A >  @mean_of_Aand A<1.8'

#### 그냥 단순인덱싱

In [144]:
df2

          A         B         C         D
0  1.711227  1.588095 -0.662286 -2.576030
1 -1.097585  0.649206 -0.803677 -0.284899
2  0.596792  0.594190 -0.758139 -1.320820
3  0.246444  1.239383 -0.428905  0.211941
4 -0.974224 -0.331926  0.608149  0.235054
5  0.302316 -1.253819  0.018625 -1.770304
6  0.834304  0.485799 -0.795757  0.886411
7  0.161218  0.736874  1.234518  0.124764
8  0.534933 -0.158519  0.401991 -0.618369
9 -0.358246 -0.710043  0.622054 -0.405878

`-` 0, 3:5, 9 에 해당하는 row를 뽑고 싶다. $\to$ 칼럼이름을 `index`로 받아서 사용한다.

In [157]:
df2.query('index == 0 or 3<= index <= 5 or index == 8 or index==9 ')

          A         B         C         D
0  1.711227  1.588095 -0.662286 -2.576030
3  0.246444  1.239383 -0.428905  0.211941
4 -0.974224 -0.331926  0.608149  0.235054
5  0.302316 -1.253819  0.018625 -1.770304
8  0.534933 -0.158519  0.401991 -0.618369
9 -0.358246 -0.710043  0.622054 -0.405878

In [167]:
df2.query('index == 0 or 3<= index <= 5 or index == [8,9]')

          A         B         C         D
0  1.711227  1.588095 -0.662286 -2.576030
3  0.246444  1.239383 -0.428905  0.211941
4 -0.974224 -0.331926  0.608149  0.235054
5  0.302316 -1.253819  0.018625 -1.770304
8  0.534933 -0.158519  0.401991 -0.618369
9 -0.358246 -0.710043  0.622054 -0.405878

In [168]:
df2.query('index == 0 or 3<= index <= 5 or index in [8,9]')

          A         B         C         D
0  1.711227  1.588095 -0.662286 -2.576030
3  0.246444  1.239383 -0.428905  0.211941
4 -0.974224 -0.331926  0.608149  0.235054
5  0.302316 -1.253819  0.018625 -1.770304
8  0.534933 -0.158519  0.401991 -0.618369
9 -0.358246 -0.710043  0.622054 -0.405878

`-` 시계열자료에서 유리함

In [158]:
_df=pd.DataFrame(np.random.randn(10,4),columns=list('ABCD'),index=pd.date_range('20210101',periods=10))
_df

                   A         B         C         D
2021-01-01 -0.626833  0.175470 -0.791269  0.545786
2021-01-02 -0.323084  0.449719  0.745854  0.394837
2021-01-03 -0.206106  0.518240  1.000923 -0.033740
2021-01-04  0.264423 -1.165340  1.764333 -0.732321
2021-01-05  0.958450  0.447558  1.714503 -1.028687
2021-01-06  0.493083  0.182832 -0.528332 -0.452710
2021-01-07  0.207865 -0.521950  0.507396  1.418395
2021-01-08 -0.486101  0.299050 -0.452954  0.860672
2021-01-09  0.501478  1.019111 -0.343397  1.107635
2021-01-10  0.087817 -1.604605 -0.336493  0.014645

In [170]:
_df.query(
    "(index < '2021-01-05' or index > '2021-01-07') and A>0" 
)

                   A         B         C         D
2021-01-04  0.264423 -1.165340  1.764333 -0.732321
2021-01-09  0.501478  1.019111 -0.343397  1.107635
2021-01-10  0.087817 -1.604605 -0.336493  0.014645