# (정리) pandas

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- categories: [파이썬]

## import

In [1]:
import pandas as pd
import numpy as np
from dfply import *

## read data

### read data from github

In [86]:
url='https://raw.githubusercontent.com/PacktPublishing/Pandas-Cookbook-Second-Edition/master/data/movie.csv'
df = pd.read_csv(url, index_col=0)
df

,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
color,,,,,,,,,,,,,,,,,,,,,
Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,Eric Mabius,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,Eva Boehnke,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,Alan Ruck,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,John August,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

- NaN: missing, not a number

## select and filter

### convert numpy and indexing

In [87]:
url='https://raw.githubusercontent.com/PacktPublishing/Pandas-Cookbook-Second-Edition/master/data/movie.csv'
df = pd.read_csv(url, index_col=0)
data=df.to_numpy()
data

array([['James Cameron', 723.0, 178.0, ..., 7.9, 1.78, 33000],
       ['Gore Verbinski', 302.0, 169.0, ..., 7.1, 2.35, 0],
       ['Sam Mendes', 602.0, 148.0, ..., 6.8, 2.35, 85000],
       ...,
       ['Benjamin Roberds', 13.0, 76.0, ..., 6.3, nan, 16],
       ['Daniel Hsia', 14.0, 100.0, ..., 6.3, 2.35, 660],
       ['Jon Gunn', 43.0, 90.0, ..., 6.6, 1.85, 456]], dtype=object)

In [88]:
data[0] ## first observation

array(['James Cameron', 723.0, 178.0, 0.0, 855.0, 'Joel David Moore',
       1000.0, 760505847.0, 'Action|Adventure|Fantasy|Sci-Fi',
       'CCH Pounder', 'Avatar', 886204, 4834, 'Wes Studi', 0.0,
       'avatar|future|marine|native|paraplegic',
       'http://www.imdb.com/title/tt0499549/?ref_=fn_tt_tt_1', 3054.0,
       'English', 'USA', 'PG-13', 237000000.0, 2009.0, 936.0, 7.9, 1.78,
       33000], dtype=object)

In [89]:
data[0,:] ## first observation

array(['James Cameron', 723.0, 178.0, 0.0, 855.0, 'Joel David Moore',
       1000.0, 760505847.0, 'Action|Adventure|Fantasy|Sci-Fi',
       'CCH Pounder', 'Avatar', 886204, 4834, 'Wes Studi', 0.0,
       'avatar|future|marine|native|paraplegic',
       'http://www.imdb.com/title/tt0499549/?ref_=fn_tt_tt_1', 3054.0,
       'English', 'USA', 'PG-13', 237000000.0, 2009.0, 936.0, 7.9, 1.78,
       33000], dtype=object)

In [90]:
data.T[0] # first variable

array(['James Cameron', 'Gore Verbinski', 'Sam Mendes', ...,
       'Benjamin Roberds', 'Daniel Hsia', 'Jon Gunn'], dtype=object)

In [91]:
data[:,0] # first variable

array(['James Cameron', 'Gore Verbinski', 'Sam Mendes', ...,
       'Benjamin Roberds', 'Daniel Hsia', 'Jon Gunn'], dtype=object)

In [92]:
data[0][0] # (first observation, first variable)

'James Cameron'

### select column

#### 예제: 하나의 열을 선택

In [93]:
dic={'X1':np.random.normal(0,1,5), 
     'X2':np.random.normal(0,1,5),
     'X3':np.random.normal(0,1,5)}
df=pd.DataFrame(dic)
df

         X1        X2        X3
0  0.408043 -1.657086 -0.280268
1 -0.273310  0.338183 -0.001384
2 -0.494917 -1.749676  0.810421
3  0.923180 -0.239616  0.936527
4 -0.776375  0.638403 -0.692063

`-` 방법1

In [94]:
df.X1

0    0.408043
1   -0.273310
2   -0.494917
3    0.923180
4   -0.776375
Name: X1, dtype: float64

`-` 방법2

In [95]:
df['X1']

0    0.408043
1   -0.273310
2   -0.494917
3    0.923180
4   -0.776375
Name: X1, dtype: float64

`-` 방법3

In [96]:
df[['X1']]

         X1
0  0.408043
1 -0.273310
2 -0.494917
3  0.923180
4 -0.776375

- `df['X1']`는 series를 리턴하고 `df[['X1']]`는 dataframe을 리턴한다.

`-` 방법4

In [97]:
df.loc[:,'X1']

0    0.408043
1   -0.273310
2   -0.494917
3    0.923180
4   -0.776375
Name: X1, dtype: float64

`-` 방법5

In [98]:
df.loc[:,['X1']]

         X1
0  0.408043
1 -0.273310
2 -0.494917
3  0.923180
4 -0.776375

- `df.loc[:,'X1']`는 series를 리턴하고 `df[['X1']]`는 dataframe을 리턴한다.

`-` 방법6

In [111]:
df.loc[:,[True,False,False]]

         X1
0  0.408043
1 -0.273310
2 -0.494917
3  0.923180
4 -0.776375

- 불인덱싱가능

`-` 방법7

In [99]:
df.iloc[:,0]

0    0.408043
1   -0.273310
2   -0.494917
3    0.923180
4   -0.776375
Name: X1, dtype: float64

`-` 방법8

In [100]:
df.iloc[:,[0]]

         X1
0  0.408043
1 -0.273310
2 -0.494917
3  0.923180
4 -0.776375

`-` 방법9

In [112]:
df.iloc[:,[True,False,False]]

         X1
0  0.408043
1 -0.273310
2 -0.494917
3  0.923180
4 -0.776375

**참고: 열이름이 integer일 경우**

In [113]:
_df = pd.DataFrame(np.array([[1,2,3],[3,4,5],[5,6,7]]))
_df

   0  1  2
0  1  2  3
1  3  4  5
2  5  6  7

`-` 아래가 모두 가능

In [114]:
_df[0]

0    1
1    3
2    5
Name: 0, dtype: int64

In [115]:
_df[[0]]

   0
0  1
1  3
2  5

In [116]:
_df.loc[:,[0]]

   0
0  1
1  3
2  5

In [117]:
_df.iloc[:,[0]]

   0
0  1
1  3
2  5

**방법 1~9의 요약**

- `df.X1` 이 가장 간단하고 편리함. 그런데 변수이름을 알고 있어야 한다는 단점이 있음. 
- `df.X1` 은 변수이름에 `.`이 포함된 경우는 사용불가. 그밖에도 변수이름에 공백이 있는등 이상한 형태의 변수이름에는 사용불가능.

#### 예제: `df`에서 1,2,3열을 선택

In [119]:
dic={'X1':np.random.normal(0,1,5), 
     'X2':np.random.normal(0,1,5),
     'X3':np.random.normal(0,1,5),
     'X4':np.random.normal(0,1,5)
    }
df=pd.DataFrame(dic)
df

         X1        X2        X3        X4
0  0.826018 -1.348298 -0.381687 -1.085877
1 -0.507153 -2.316037 -0.418960 -0.512126
2 -1.084464  1.237822  0.378427  1.241917
3  0.725161 -0.177202 -1.172536  0.321283
4  0.534595 -0.742990  0.375397  0.010922

`-` 방법1

In [120]:
df[['X1','X2','X3']]

         X1        X2        X3
0  0.826018 -1.348298 -0.381687
1 -0.507153 -2.316037 -0.418960
2 -1.084464  1.237822  0.378427
3  0.725161 -0.177202 -1.172536
4  0.534595 -0.742990  0.375397

위와 동일한 문법을 응용하면

In [121]:
varlist=['X'+i for i in '123']
varlist

['X1', 'X2', 'X3']

In [122]:
df[varlist]

         X1        X2        X3
0  0.826018 -1.348298 -0.381687
1 -0.507153 -2.316037 -0.418960
2 -1.084464  1.237822  0.378427
3  0.725161 -0.177202 -1.172536
4  0.534595 -0.742990  0.375397

`-` 방법2

In [123]:
df.loc[:,['X1','X2','X3']]

         X1        X2        X3
0  0.826018 -1.348298 -0.381687
1 -0.507153 -2.316037 -0.418960
2 -1.084464  1.237822  0.378427
3  0.725161 -0.177202 -1.172536
4  0.534595 -0.742990  0.375397

`-` 방법3

In [124]:
df.loc[:,'X1':'X3']

         X1        X2        X3
0  0.826018 -1.348298 -0.381687
1 -0.507153 -2.316037 -0.418960
2 -1.084464  1.237822  0.378427
3  0.725161 -0.177202 -1.172536
4  0.534595 -0.742990  0.375397

`-` 방법4

In [125]:
df.loc[:,[True,True,True,False]]

         X1        X2        X3
0  0.826018 -1.348298 -0.381687
1 -0.507153 -2.316037 -0.418960
2 -1.084464  1.237822  0.378427
3  0.725161 -0.177202 -1.172536
4  0.534595 -0.742990  0.375397

응용하면 아래도 가능하다

In [126]:
_cols=df.columns.to_list()
_cols

['X1', 'X2', 'X3', 'X4']

In [127]:
import re

In [128]:
re.match('X',_cols[0])

`-` 방법5

In [129]:
df.iloc[:,[0,1,2]]

         X1        X2        X3
0  0.826018 -1.348298 -0.381687
1 -0.507153 -2.316037 -0.418960
2 -1.084464  1.237822  0.378427
3  0.725161 -0.177202 -1.172536
4  0.534595 -0.742990  0.375397

이 방법을 응용하면

In [130]:
idx = range(3)
idx

range(0, 3)

In [131]:
df.iloc[:,idx]

         X1        X2        X3
0  0.826018 -1.348298 -0.381687
1 -0.507153 -2.316037 -0.418960
2 -1.084464  1.237822  0.378427
3  0.725161 -0.177202 -1.172536
4  0.534595 -0.742990  0.375397

In [132]:
idx = np.arange(3)
idx

array([0, 1, 2])

In [133]:
df.iloc[:,idx]

         X1        X2        X3
0  0.826018 -1.348298 -0.381687
1 -0.507153 -2.316037 -0.418960
2 -1.084464  1.237822  0.378427
3  0.725161 -0.177202 -1.172536
4  0.534595 -0.742990  0.375397

In [134]:
idx = np.arange(3.)
idx

array([0., 1., 2.])

In [135]:
df.iloc[:,idx]

         X1        X2        X3
0  0.826018 -1.348298 -0.381687
1 -0.507153 -2.316037 -0.418960
2 -1.084464  1.237822  0.378427
3  0.725161 -0.177202 -1.172536
4  0.534595 -0.742990  0.375397

- idx의 값이 float형으로 저장되어 있어도 에러나지 않음

`-` 방법6

In [136]:
df.iloc[:,[True,True,True,False]]

         X1        X2        X3
0  0.826018 -1.348298 -0.381687
1 -0.507153 -2.316037 -0.418960
2 -1.084464  1.237822  0.378427
3  0.725161 -0.177202 -1.172536
4  0.534595 -0.742990  0.375397

**(주의) loc에서의 슬라이싱은 마지막변수를 포함하지만 iloc에서는 포함하지 않음.**

`-` 아래를 비교하라.

In [39]:
df.iloc[:,0:3] ## 3은 포함되지 않는다.

         X1        X2        X3
0  0.484295  1.465122  0.433659
1 -0.499525  1.115541 -0.023644
2 -1.068005  1.352107  0.972758
3 -1.416998  0.145222 -0.694749
4 -0.010197 -0.085394 -0.149580

In [40]:
df.loc[:,'X1':'X3'] ## 'X3'이 포함된다.

         X1        X2        X3
0  0.484295  1.465122  0.433659
1 -0.499525  1.115541 -0.023644
2 -1.068005  1.352107  0.972758
3 -1.416998  0.145222 -0.694749
4 -0.010197 -0.085394 -0.149580

`-` 그래서 column의 이름이 integer일 경우는 종종 매우 헷갈리는 결과가 나옴

In [41]:
_df = pd.DataFrame(np.array([[1,2,3,4],[3,4,5,6],[5,6,7,8]]))
_df

   0  1  2  3
0  1  2  3  4
1  3  4  5  6
2  5  6  7  8

In [42]:
_df.loc[:,0:2]

   0  1  2
0  1  2  3
1  3  4  5
2  5  6  7

In [43]:
_df.iloc[:,0:2]

   0  1
0  1  2
1  3  4
2  5  6

> note: 사실 이것은 일부러 헷갈리게 예제를 구성한것이다. 실제로는 헷갈리는 상황이 많이 발생하지 않는다. 왜냐하면 보통 위의 예제와 같은 경우에는 ndarray로 처리하고 colname이 있는 경우만 데이터프레임으로 처리하기 때문

**방법 1~6의 요약**

`-` 내가 생각할때 가장 독특한 방법은 아래이다. (그런데 컬럼이름 양옆에 따옴표를 붙이는 것이 불편함)

In [47]:
df.loc[:,'X1':'X3']

         X1        X2        X3
0  0.484295  1.465122  0.433659
1 -0.499525  1.115541 -0.023644
2 -1.068005  1.352107  0.972758
3 -1.416998  0.145222 -0.694749
4 -0.010197 -0.085394 -0.149580

- 이방법은 오로지 판다스에서만 가능하다.

`-` 변수이름이 순서대로 정리되어 있지 않아도 사용할 수 있다.

In [110]:
_dic={'Y1':np.random.normal(0,1,5), 
      'Y2':np.random.normal(0,1,5),
      'X1':np.random.normal(0,1,5),
      'X2':np.random.normal(0,1,5)}
_df=pd.DataFrame(_dic)
_df

         Y1        Y2        X1        X2
0  1.311357 -0.702901 -0.345682  0.213560
1 -0.338540 -0.257803  0.066981 -0.655379
2 -1.071441 -0.214624 -0.860739 -1.150242
3  0.326756 -0.577812 -0.250539 -0.906488
4  0.415005 -0.235499  0.559192  0.010276

In [52]:
_df.loc[:,'Y1':'X1']

         Y1        Y2        X1
0 -1.526823 -0.757679  0.618500
1 -0.749511 -2.077823  0.077994
2  1.297920 -0.601280  0.359501
3  0.453082 -0.478913 -1.812059
4  1.201057  0.524883  0.965684

#### movie data

In [137]:
url='https://raw.githubusercontent.com/PacktPublishing/Pandas-Cookbook-Second-Edition/master/data/movie.csv'
df = pd.read_csv(url, index_col=0)
df

,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
color,,,,,,,,,,,,,,,,,,,,,
Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,Eric Mabius,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,Eva Boehnke,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,Alan Ruck,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,John August,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

`-` 열의 이름을 출력해보자.

In [144]:
cols=df.columns.to_list()
cols

['director_name',
 'num_critic_for_reviews',
 'duration',
 'director_facebook_likes',
 'actor_3_facebook_likes',
 'actor_2_name',
 'actor_1_facebook_likes',
 'gross',
 'genres',
 'actor_1_name',
 'movie_title',
 'num_voted_users',
 'cast_total_facebook_likes',
 'actor_3_name',
 'facenumber_in_poster',
 'plot_keywords',
 'movie_imdb_link',
 'num_user_for_reviews',
 'language',
 'country',
 'content_rating',
 'budget',
 'title_year',
 'actor_2_facebook_likes',
 'imdb_score',
 'aspect_ratio',
 'movie_facebook_likes']

`-` 팁: 열의 이름을 인덱스와 함께 출력하기 위해서는 아래와 같이 하면 쉽다.

In [145]:
pd.Series(cols)

0                 director_name
1        num_critic_for_reviews
2                      duration
3       director_facebook_likes
4        actor_3_facebook_likes
5                  actor_2_name
6        actor_1_facebook_likes
7                         gross
8                        genres
9                  actor_1_name
10                  movie_title
11              num_voted_users
12    cast_total_facebook_likes
13                 actor_3_name
14         facenumber_in_poster
15                plot_keywords
16              movie_imdb_link
17         num_user_for_reviews
18                     language
19                      country
20               content_rating
21                       budget
22                   title_year
23       actor_2_facebook_likes
24                   imdb_score
25                 aspect_ratio
26         movie_facebook_likes
dtype: object

`-` actor로 시작하는 변수명을 뽑아보자.

In [171]:
flist(filter(lambda x: 'actor' in x[0:5] , cols))

['actor_3_facebook_likes',
 'actor_2_name',
 'actor_1_facebook_likes',
 'actor_1_name',
 'actor_3_name',
 'actor_2_facebook_likes']

In [173]:
df.loc[:,filter(lambda x: 'actor' in x[0:5] , cols)]

,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,actor_1_name,actor_3_name,actor_2_facebook_likes
color,,,,,,
Color,855.0,Joel David Moore,1000.0,CCH Pounder,Wes Studi,936.0
Color,1000.0,Orlando Bloom,40000.0,Johnny Depp,Jack Davenport,5000.0
Color,161.0,Rory Kinnear,11000.0,Christoph Waltz,Stephanie Sigman,393.0
Color,23000.0,Christian Bale,27000.0,Tom Hardy,Joseph Gordon-Levitt,23000.0
NaN,NaN,Rob Walker,131.0,Doug Walker,NaN,12.0
...,...,...,...,...,...,...
Color,318.0,Daphne Zuniga,637.0,Eric Mabius,Crystal Lowe,470.0
Color,319.0,Valorie Curry,841.0,Natalie Zea,Sam Underwood,593.0
Color,0.0,Maxwell Moody,0.0,Eva Boehnke,David Chandler,0.0
Color,489.0,Daniel Henney,946.0,Alan Ruck,Eliza Coupe,719.0
Color,16.0,Brian Herzlinger,86.0,John August,Jon Gunn,23.0