# (노트) 판다스 concat, join 

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- categories: [파이썬]

### import

In [57]:
import pandas as pd

### data

In [58]:
_df2016 =pd.read_csv('https://raw.githubusercontent.com/PacktPublishing/Pandas-Cookbook/master/data/stocks_2016.csv')
_df2017 =pd.read_csv('https://raw.githubusercontent.com/PacktPublishing/Pandas-Cookbook/master/data/stocks_2017.csv')
_df2018 =pd.read_csv('https://raw.githubusercontent.com/PacktPublishing/Pandas-Cookbook/master/data/stocks_2018.csv')

### pd.concat([...])

#### 예제1

In [59]:
_df2016

  Symbol  Shares  Low  High
0   AAPL      80   95   110
1   TSLA      50   80   130
2    WMT      40   55    70

In [60]:
_df2017

  Symbol  Shares  Low  High
0   AAPL      50  120   140
1     GE     100   30    40
2    IBM      87   75    95
3    SLB      20   55    85
4    TXN     500   15    23
5   TSLA     100  100   300

In [61]:
_df2018

  Symbol  Shares  Low  High
0   AAPL      40  135   170
1   AMZN       8  900  1125
2   TSLA      50  220   400

In [62]:
pd.concat([_df2016,_df2017,_df2018])

  Symbol  Shares  Low  High
0   AAPL      80   95   110
1   TSLA      50   80   130
2    WMT      40   55    70
0   AAPL      50  120   140
1     GE     100   30    40
2    IBM      87   75    95
3    SLB      20   55    85
4    TXN     500   15    23
5   TSLA     100  100   300
0   AAPL      40  135   170
1   AMZN       8  900  1125
2   TSLA      50  220   400

In [63]:
pd.concat([_df2016,_df2017,_df2018]).reset_index()

    index Symbol  Shares  Low  High
0       0   AAPL      80   95   110
1       1   TSLA      50   80   130
2       2    WMT      40   55    70
3       0   AAPL      50  120   140
4       1     GE     100   30    40
5       2    IBM      87   75    95
6       3    SLB      20   55    85
7       4    TXN     500   15    23
8       5   TSLA     100  100   300
9       0   AAPL      40  135   170
10      1   AMZN       8  900  1125
11      2   TSLA      50  220   400

In [64]:
pd.concat([_df2016,_df2017,_df2018]).reset_index(drop=True)

   Symbol  Shares  Low  High
0    AAPL      80   95   110
1    TSLA      50   80   130
2     WMT      40   55    70
3    AAPL      50  120   140
4      GE     100   30    40
5     IBM      87   75    95
6     SLB      20   55    85
7     TXN     500   15    23
8    TSLA     100  100   300
9    AAPL      40  135   170
10   AMZN       8  900  1125
11   TSLA      50  220   400

`-` R에서 rbind와 유사하다.

#### 예제2

`-` rbind와의 차이점: 합치려는 데이터프레임의 column이 꼭 동일할 필요는 없다.

In [65]:
_df2016

  Symbol  Shares  Low  High
0   AAPL      80   95   110
1   TSLA      50   80   130
2    WMT      40   55    70

In [66]:
_df2017.iloc[:,1:]

   Shares  Low  High
0      50  120   140
1     100   30    40
2      87   75    95
3      20   55    85
4     500   15    23
5     100  100   300

In [67]:
pd.concat([_df2016, _df2017.iloc[:,1:]])

  Symbol  Shares  Low  High
0   AAPL      80   95   110
1   TSLA      50   80   130
2    WMT      40   55    70
0    NaN      50  120   140
1    NaN     100   30    40
2    NaN      87   75    95
3    NaN      20   55    85
4    NaN     500   15    23
5    NaN     100  100   300

### pd.concat([...],axis='columns')

`-` cbind 와 비슷한 느낌이다. (그런데 row의 숫자가 서로 달라도 괜찮음)

#### 예제3

In [54]:
_df2016

  Symbol  Shares  Low  High
0   AAPL      80   95   110
1   TSLA      50   80   130
2    WMT      40   55    70

In [55]:
_df2017

  Symbol  Shares  Low  High
0   AAPL      50  120   140
1     GE     100   30    40
2    IBM      87   75    95
3    SLB      20   55    85
4    TXN     500   15    23
5   TSLA     100  100   300

In [56]:
_df2018

  Symbol  Shares  Low  High
0   AAPL      40  135   170
1   AMZN       8  900  1125
2   TSLA      50  220   400

In [53]:
pd.concat([_df2016,_df2017,_df2018],axis='columns')

,Symbol,Shares,Low,High,Symbol,Shares,Low,High,Symbol,Shares,Low,High
0,AAPL,80.0,95.0,110.0,AAPL,50,120,140,AAPL,40.0,135.0,170.0
1,TSLA,50.0,80.0,130.0,GE,100,30,40,AMZN,8.0,900.0,1125.0
2,WMT,40.0,55.0,70.0,IBM,87,75,95,TSLA,50.0,220.0,400.0
3,NaN,NaN,NaN,NaN,SLB,20,55,85,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,TXN,500,15,23,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,TSLA,100,100,300,NaN,NaN,NaN,NaN

In [71]:
pd.concat([_df2016,_df2017,_df2018],axis=1)

,Symbol,Shares,Low,High,Symbol,Shares,Low,High,Symbol,Shares,Low,High
0,AAPL,80.0,95.0,110.0,AAPL,50,120,140,AAPL,40.0,135.0,170.0
1,TSLA,50.0,80.0,130.0,GE,100,30,40,AMZN,8.0,900.0,1125.0
2,WMT,40.0,55.0,70.0,IBM,87,75,95,TSLA,50.0,220.0,400.0
3,NaN,NaN,NaN,NaN,SLB,20,55,85,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,TXN,500,15,23,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,TSLA,100,100,300,NaN,NaN,NaN,NaN

- 컬럼이 길잖아요.. 그래서 1이에요..

### pd.concat([...],keys=[...])

#### 예제4

In [54]:
_df2016

  Symbol  Shares  Low  High
0   AAPL      80   95   110
1   TSLA      50   80   130
2    WMT      40   55    70

In [55]:
_df2017

  Symbol  Shares  Low  High
0   AAPL      50  120   140
1     GE     100   30    40
2    IBM      87   75    95
3    SLB      20   55    85
4    TXN     500   15    23
5   TSLA     100  100   300

In [56]:
_df2018

  Symbol  Shares  Low  High
0   AAPL      40  135   170
1   AMZN       8  900  1125
2   TSLA      50  220   400

In [77]:
pd.concat([_df2016,_df2017,_df2018],keys=[2016,2017,2018])

       Symbol  Shares  Low  High
2016 0   AAPL      80   95   110
     1   TSLA      50   80   130
     2    WMT      40   55    70
2017 0   AAPL      50  120   140
     1     GE     100   30    40
     2    IBM      87   75    95
     3    SLB      20   55    85
     4    TXN     500   15    23
     5   TSLA     100  100   300
2018 0   AAPL      40  135   170
     1   AMZN       8  900  1125
     2   TSLA      50  220   400

In [103]:
pd.concat(dict(zip([2016,2017,2018],[_df2016,_df2017,_df2018])))

       Symbol  Shares  Low  High
2016 0   AAPL      80   95   110
     1   TSLA      50   80   130
     2    WMT      40   55    70
2017 0   AAPL      50  120   140
     1     GE     100   30    40
     2    IBM      87   75    95
     3    SLB      20   55    85
     4    TXN     500   15    23
     5   TSLA     100  100   300
2018 0   AAPL      40  135   170
     1   AMZN       8  900  1125
     2   TSLA      50  220   400

In [80]:
pd.concat([_df2016,_df2017,_df2018],keys=[2016,2017]) ## 의도하지 않는 코드 1

       Symbol  Shares  Low  High
2016 0   AAPL      80   95   110
     1   TSLA      50   80   130
     2    WMT      40   55    70
2017 0   AAPL      50  120   140
     1     GE     100   30    40
     2    IBM      87   75    95
     3    SLB      20   55    85
     4    TXN     500   15    23
     5   TSLA     100  100   300

In [81]:
pd.concat([_df2016,_df2017,_df2018],keys=[2016,2018]) ## 의도하지 않은 코드 2

       Symbol  Shares  Low  High
2016 0   AAPL      80   95   110
     1   TSLA      50   80   130
     2    WMT      40   55    70
2018 0   AAPL      50  120   140
     1     GE     100   30    40
     2    IBM      87   75    95
     3    SLB      20   55    85
     4    TXN     500   15    23
     5   TSLA     100  100   300

In [83]:
pd.concat([_df2016,_df2017,_df2018],keys=[2016,2017,2018,2019]) #의도하지 않은 코드3

       Symbol  Shares  Low  High
2016 0   AAPL      80   95   110
     1   TSLA      50   80   130
     2    WMT      40   55    70
2017 0   AAPL      50  120   140
     1     GE     100   30    40
     2    IBM      87   75    95
     3    SLB      20   55    85
     4    TXN     500   15    23
     5   TSLA     100  100   300
2018 0   AAPL      40  135   170
     1   AMZN       8  900  1125
     2   TSLA      50  220   400

### pd.concat([...],keys=[...],axis='columns')

#### 예제5

In [54]:
_df2016

  Symbol  Shares  Low  High
0   AAPL      80   95   110
1   TSLA      50   80   130
2    WMT      40   55    70

In [55]:
_df2017

  Symbol  Shares  Low  High
0   AAPL      50  120   140
1     GE     100   30    40
2    IBM      87   75    95
3    SLB      20   55    85
4    TXN     500   15    23
5   TSLA     100  100   300

In [56]:
_df2018

  Symbol  Shares  Low  High
0   AAPL      40  135   170
1   AMZN       8  900  1125
2   TSLA      50  220   400

In [86]:
pd.concat([_df2016,_df2017,_df2018],keys=[2016,2017,2018],axis=1)

    2016                       2017                    2018                \
  Symbol Shares   Low   High Symbol Shares  Low High Symbol Shares    Low
0   AAPL   80.0  95.0  110.0   AAPL     50  120  140   AAPL   40.0  135.0
1   TSLA   50.0  80.0  130.0     GE    100   30   40   AMZN    8.0  900.0
2    WMT   40.0  55.0   70.0    IBM     87   75   95   TSLA   50.0  220.0
3    NaN    NaN   NaN    NaN    SLB     20   55   85    NaN    NaN    NaN
4    NaN    NaN   NaN    NaN    TXN    500   15   23    NaN    NaN    NaN
5    NaN    NaN   NaN    NaN   TSLA    100  100  300    NaN    NaN    NaN


     High
0   170.0
1  1125.0
2   400.0
3     NaN
4     NaN
5     NaN

In [101]:
pd.concat(dict(zip([2016,2017,2018],[_df2016,_df2017,_df2018])),axis=1)

    2016                       2017                    2018                \
  Symbol Shares   Low   High Symbol Shares  Low High Symbol Shares    Low
0   AAPL   80.0  95.0  110.0   AAPL     50  120  140   AAPL   40.0  135.0
1   TSLA   50.0  80.0  130.0     GE    100   30   40   AMZN    8.0  900.0
2    WMT   40.0  55.0   70.0    IBM     87   75   95   TSLA   50.0  220.0
3    NaN    NaN   NaN    NaN    SLB     20   55   85    NaN    NaN    NaN
4    NaN    NaN   NaN    NaN    TXN    500   15   23    NaN    NaN    NaN
5    NaN    NaN   NaN    NaN   TSLA    100  100  300    NaN    NaN    NaN


     High
0   170.0
1  1125.0
2   400.0
3     NaN
4     NaN
5     NaN

### df.join([...],how='outer')

#### 예제6

In [105]:
_df2016

  Symbol  Shares  Low  High
0   AAPL      80   95   110
1   TSLA      50   80   130
2    WMT      40   55    70

In [106]:
_df2017

  Symbol  Shares  Low  High
0   AAPL      50  120   140
1     GE     100   30    40
2    IBM      87   75    95
3    SLB      20   55    85
4    TXN     500   15    23
5   TSLA     100  100   300

In [107]:
_df2018

  Symbol  Shares  Low  High
0   AAPL      40  135   170
1   AMZN       8  900  1125
2   TSLA      50  220   400

In [ ]:
_df2016.merge?

Signature:
_df2016.merge(
    right: 'FrameOrSeriesUnion',
    how: 'str' = 'inner',
    on: 'IndexLabel | None' = None,
    left_on: 'IndexLabel | None' = None,
    right_on: 'IndexLabel | None' = None,
    left_index: 'bool' = False,
    right_index: 'bool' = False,
    sort: 'bool' = False,
    suffixes: 'Suffixes' = ('_x', '_y'),
    copy: 'bool' = True,
    indicator: 'bool' = False,
    validate: 'str | None' = None,
) -> 'DataFrame'
Docstring:
Merge DataFrame or named Series objects with a database-style join.

A named Series object is treated as a DataFrame with a single named column.

The join is done on columns or indexes. If joining columns on
columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
on indexes or indexes on a column or columns, the index will be passed on.
When performing a cross merge, no column specifications to merge on are
allowed.

Parameters
----------
right : DataFrame or named Series
    Object to merge with.
how : {'left', 'right', 'outer', 'inner', 'cross'}, default 'inner'
    Type of merge to be performed.

    * left: use only keys from left frame, similar to a SQL left outer join;
      preserve key order.
    * right: use only keys from right frame, similar to a SQL right outer join;
      preserve key order.
    * outer: use union of keys from both frames, similar to a SQL full outer
      join; sort keys lexicographically.
    * inner: use intersection of keys from both frames, similar to a SQL inner
      join; preserve the order of the left keys.
    * cross: creates the cartesian product from both frames, preserves the order
      of the left keys.

      .. versionadded:: 1.2.0

on : label or list
    Column or index level names to join on. These must be found in both
    DataFrames. If `on` is None and not merging on indexes then this defaults
    to the intersection of the columns in both DataFrames.
left_on : label or list, or array-like
    Column or index level names to join on in the left DataFrame. Can also
    be an array or list of arrays of the length of the left DataFrame.
    These arrays are treated as if they are columns.
right_on : label or list, or array-like
    Column or index level names to join on in the right DataFrame. Can also
    be an array or list of arrays of the length of the right DataFrame.
    These arrays are treated as if they are columns.
left_index : bool, default False
    Use the index from the left DataFrame as the join key(s). If it is a
    MultiIndex, the number of keys in the other DataFrame (either the index
    or a number of columns) must match the number of levels.
right_index : bool, default False
    Use the index from the right DataFrame as the join key. Same caveats as
    left_index.
sort : bool, default False
    Sort the join keys lexicographically in the result DataFrame. If False,
    the order of the join keys depends on the join type (how keyword).
suffixes : list-like, default is ("_x", "_y")
    A length-2 sequence where each element is optionally a string
    indicating the suffix to add to overlapping column names in
    `left` and `right` respectively. Pass a value of `None` instead
    of a string to indicate that the column name from `left` or
    `right` should be left as-is, with no suffix. At least one of the
    values must not be None.
copy : bool, default True
    If False, avoid copy if possible.
indicator : bool or str, default False
    If True, adds a column to the output DataFrame called "_merge" with
    information on the source of each row. The column can be given a different
    name by providing a string argument. The column will have a Categorical
    type with the value of "left_only" for observations whose merge key only
    appears in the left DataFrame, "right_only" for observations
    whose merge key only appears in the right DataFrame, and "both"
    if the observation's merge key is found in both DataFrames.

validate : str, optional
    If specified, checks if merge is of specified type.

    * "one_to_one" or "1:1": check if merge keys are unique in both
      left and right datasets.
    * "one_to_many" or "1:m": check if merge keys are unique in left
      dataset.
    * "many_to_one" or "m:1": check if merge keys are unique in right
      dataset.
    * "many_to_many" or "m:m": allowed, but does not result in checks.

Returns
-------
DataFrame
    A DataFrame of the two merged objects.

See Also
--------
merge_ordered : Merge with optional filling/interpolation.
merge_asof : Merge on nearest keys.
DataFrame.join : Similar method using indices.

Notes
-----
Support for specifying index levels as the `on`, `left_on`, and
`right_on` parameters was added in version 0.23.0
Support for merging named Series objects was added in version 0.24.0

Examples
--------
>>> df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
...                     'value': [1, 2, 3, 5]})
>>> df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
...                     'value': [5, 6, 7, 8]})
>>> df1
    lkey value
0   foo      1
1   bar      2
2   baz      3
3   foo      5
>>> df2
    rkey value
0   foo      5
1   bar      6
2   baz      7
3   foo      8

Merge df1 and df2 on the lkey and rkey columns. The value columns have
the default suffixes, _x and _y, appended.

>>> df1.merge(df2, left_on='lkey', right_on='rkey')
  lkey  value_x rkey  value_y
0  foo        1  foo        5
1  foo        1  foo        8
2  foo        5  foo        5
3  foo        5  foo        8
4  bar        2  bar        6
5  baz        3  baz        7

Merge DataFrames df1 and df2 with specified left and right suffixes
appended to any overlapping columns.

>>> df1.merge(df2, left_on='lkey', right_on='rkey',
...           suffixes=('_left', '_right'))
  lkey  value_left rkey  value_right
0  foo           1  foo            5
1  foo           1  foo            8
2  foo           5  foo            5
3  foo           5  foo            8
4  bar           2  bar            6
5  baz           3  baz            7

Merge DataFrames df1 and df2, but raise an exception if the DataFrames have
any overlapping columns.

>>> df1.merge(df2, left_on='lkey', right_on='rkey', suffixes=(False, False))
Traceback (most recent call last):
...
ValueError: columns overlap but no suffix specified:
    Index(['value'], dtype='object')

>>> df1 = pd.DataFrame({'a': ['foo', 'bar'], 'b': [1, 2]})
>>> df2 = pd.DataFrame({'a': ['foo', 'baz'], 'c': [3, 4]})
>>> df1
      a  b
0   foo  1
1   bar  2
>>> df2
      a  c
0   foo  3
1   baz  4

>>> df1.merge(df2, how='inner', on='a')
      a  b  c
0   foo  1  3

>>> df1.merge(df2, how='left', on='a')
      a  b  c
0   foo  1  3.0
1   bar  2  NaN

>>> df1 = pd.DataFrame({'left': ['foo', 'bar']})
>>> df2 = pd.DataFrame({'right': [7, 8]})
>>> df1
    left
0   foo
1   bar
>>> df2
    right
0   7
1   8

>>> df1.merge(df2, how='cross')
   left  right
0   foo      7
1   foo      8
2   bar      7
3   bar      8
File:      ~/anaconda3/envs/py38r40/lib/python3.8/site-packages/pandas/core/frame.py
Type:      method

In [116]:
_df2017

  Symbol  Shares  Low  High
0   AAPL      50  120   140
1     GE     100   30    40
2    IBM      87   75    95
3    SLB      20   55    85
4    TXN     500   15    23
5   TSLA     100  100   300

### 예제3

`-` df1 데이터선언; 각 observation은 영화이름의 알파벳순서로 나열.

In [14]:
import pandas as pd 
df1=pd.DataFrame({'nodename':['Ant-man','Hulk','Iron-man'],'open':[2020,2012,2010]})
df1

   nodename  open
0   Ant-man  2020
1      Hulk  2012
2  Iron-man  2010

`-` df2 데이터선언; observation은 영화개봉순으로 나열.

In [15]:
df2=pd.DataFrame({'nodename':['Iron-man','Hulk','Ant-man'],'box-office':[100,300,50]})
df2

   nodename  box-office
0  Iron-man         100
1      Hulk         300
2   Ant-man          50

`-` df1,df2는 nodename이라는 공통된 열이 존재함 $\to$ inner join 으로 두 데이터를 합칠 수 있다.

df1에서 나열된 obsevation 순으로 합치자.

In [9]:
pd.merge(df1,df2)

   nodename  open  box-office
0   Ant-man  2020          50
1      Hulk  2012         300
2  Iron-man  2010         100

df2에서 나열된 observation 순으로 합치자.

In [10]:
pd.merge(df2,df1)

   nodename  box-office  open
0  Iron-man         100  2010
1      Hulk         300  2012
2   Ant-man          50  2020

### 예제2: observation 수가 달라도 가능함