In [24]:
#hide
options(jupyter.plot_scale=3)
options(jupyter.display_mimetypes=c("text/html"))
options(jupyter.rich_display=FALSE)
options(repr.plot.width=6,repr.plot.height=6,repr.plot.res=300)
options(max.print=1000)

### 볼링공 문제

### 풀이

(풀이1)

In [1]:
a=c(1,3,2,3,2)

In [2]:
count=0
for (i in 1:5){
    for (j in 1:5){
        if (a[i]!=a[j]) count=count+1
    }
}
count

[1] 16

- ? 중복이 계산되어서 이상한 값이 나왔다..

`-` 아래와 같이 수정하면 된다.

In [3]:
count=0
for (i in 1:5){
    for (j in 1:5){
        if ((a[i]!=a[j])&(i>j)) count=count+1
    }
}
count

[1] 8

`-` 아예 아래처럼 해도 괜찮다.

In [4]:
count=0
for (i in 1:5){
    for (j in i:5){
        if (a[i]!=a[j]) count=count+1
    }
}
count

[1] 8

(풀이2)

In [5]:
a=c(1,3,2,3,2)
A=rep(0,(length(a)**2)*2)
dim(A)=c(length(a)**2,2)
A

      [,1] [,2]
 [1,] 0    0
 [2,] 0    0
 [3,] 0    0
 [4,] 0    0
 [5,] 0    0
 [6,] 0    0
 [7,] 0    0
 [8,] 0    0
 [9,] 0    0
[10,] 0    0
[11,] 0    0
[12,] 0    0
[13,] 0    0
[14,] 0    0
[15,] 0    0
[16,] 0    0
[17,] 0    0
[18,] 0    0
[19,] 0    0
[20,] 0    0
[21,] 0    0
[22,] 0    0
[23,] 0    0
[24,] 0    0
[25,] 0    0

In [6]:
count=0
k=1
for (i in 1:5){
    for (j in 1:5){
        A[k,]=c(a[i],a[j])
        k=k+1
    }
}
A

      [,1] [,2]
 [1,] 1    1
 [2,] 1    3
 [3,] 1    2
 [4,] 1    3
 [5,] 1    2
 [6,] 3    1
 [7,] 3    3
 [8,] 3    2
 [9,] 3    3
[10,] 3    2
[11,] 2    1
[12,] 2    3
[13,] 2    2
[14,] 2    3
[15,] 2    2
[16,] 3    1
[17,] 3    3
[18,] 3    2
[19,] 3    3
[20,] 3    2
[21,] 2    1
[22,] 2    3
[23,] 2    2
[24,] 2    3
[25,] 2    2

In [7]:
vec1<-c()
vec2<-c()
for(i in 1:25){
    vec1[i]<- A[i,1]-A[i,2]
    vec2[i]<- A[i,1]>A[i,2]
}

In [8]:
vec1

 [1]  0 -2 -1 -2 -1  2  0  1  0  1  1 -1  0 -1  0  2  0  1  0  1  1 -1  0 -1  0

In [9]:
vec2

 [1] FALSE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE
[13] FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE FALSE FALSE
[25] FALSE

In [10]:
(vec1!=0) & (vec2==TRUE)

 [1] FALSE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE
[13] FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE FALSE FALSE
[25] FALSE

In [11]:
sum((vec1!=0) & (vec2==TRUE))

[1] 8

`-` 그래도 위의 코드보다 디버깅하기에는 좋음

`-` 빠르고 간단하고 효율적인 코드도 중요한데 틀리지 않는것이 가장 중요함

`-` 특히 삼성문제의 경우 예외사항을 잘 처리해야하는 문제가 주로 출제된다.

`-` 시간이 많다면 2개 이상으로 구현하고 결과를 맞춰보는것도 좋음.

(풀이3)

In [12]:
A=expand.grid(a,a)
A

   Var1 Var2
1  1    1
2  3    1
3  2    1
4  3    1
5  2    1
6  1    3
7  3    3
8  2    3
9  3    3
10 2    3
11 1    2
12 3    2
13 2    2
14 3    2
15 2    2
16 1    3
17 3    3
18 2    3
19 3    3
20 2    3
21 1    2
22 3    2
23 2    2
24 3    2
25 2    2

In [13]:
A %>% mutate(C=Var1-Var2)

ERROR: Error in A %>% mutate(C = Var1 - Var2): could not find function "%>%"

In [14]:
A %>% mutate(C=Var1-Var2) %>% filter(C>0)

ERROR: Error in A %>% mutate(C = Var1 - Var2) %>% filter(C > 0): could not find function "%>%"

In [15]:
A %>% mutate(C=Var1-Var2) %>% filter(C>0) %>% count

ERROR: Error in A %>% mutate(C = Var1 - Var2) %>% filter(C > 0) %>% count: could not find function "%>%"

In [16]:
A %>% mutate(C=Var1-Var2) %>% filter(C>0) %>% count %>% as.numeric

ERROR: Error in A %>% mutate(C = Var1 - Var2) %>% filter(C > 0) %>% count %>% : could not find function "%>%"

(풀이4)

In [17]:
A=outer(a,a)

In [18]:
A

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    3    2    3    2
[2,] 3    9    6    9    6
[3,] 2    6    4    6    4
[4,] 3    9    6    9    6
[5,] 2    6    4    6    4

In [19]:
sum(!(A[upper.tri(A)] %in% c(1,4,9)))

[1] 8