# (노트) 판다스 - 행선택 

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- hide: false
- categories: [파이썬]

### import

In [2]:
import numpy as np
import pandas as pd

### 첫번째 행을 선택하는 방법

In [33]:
dic={'X1':np.random.normal(0,1,5), 
     'X2':np.random.normal(0,1,5),
     'X3':np.random.normal(0,1,5),
     'X4':np.random.normal(0,1,5),
     'X5':np.random.normal(0,1,5),  
     'X6':np.random.normal(0,1,5)
    }
df=pd.DataFrame(dic)
df

         X1        X2        X3        X4        X5        X6
0 -0.658169  0.091914 -0.814490 -1.704484 -0.004162  1.660867
1  0.261344  0.551248 -0.475189  0.384688 -2.066834  1.061705
2 -0.082601 -0.087567  2.343085  0.317481  0.172978 -0.479281
3  0.109501 -1.843824  0.452506  0.128517 -1.066825  1.696262
4  0.951128  0.304696  0.964313 -0.055517  0.929195  0.326962

`-` 방법1

In [34]:
df.iloc[0] # 이상해

X1   -0.658169
X2    0.091914
X3   -0.814490
X4   -1.704484
X5   -0.004162
X6    1.660867
Name: 0, dtype: float64

`-` 방법2

In [38]:
df.iloc[0,:]

X1   -0.658169
X2    0.091914
X3   -0.814490
X4   -1.704484
X5   -0.004162
X6    1.660867
Name: 0, dtype: float64

`-` 방법3

In [39]:
df.iloc[[0]]

         X1        X2       X3        X4        X5        X6
0 -0.658169  0.091914 -0.81449 -1.704484 -0.004162  1.660867

`-` 방법4

In [40]:
df.iloc[[0],:]

         X1        X2       X3        X4        X5        X6
0 -0.658169  0.091914 -0.81449 -1.704484 -0.004162  1.660867

`-` 방법5

In [36]:
df.loc[0]

X1   -0.658169
X2    0.091914
X3   -0.814490
X4   -1.704484
X5   -0.004162
X6    1.660867
Name: 0, dtype: float64

`-` 방법6

In [41]:
df.loc[0,:]

X1   -0.658169
X2    0.091914
X3   -0.814490
X4   -1.704484
X5   -0.004162
X6    1.660867
Name: 0, dtype: float64

`-` 방법7

In [37]:
df.loc[[0]]

         X1        X2       X3        X4        X5        X6
0 -0.658169  0.091914 -0.81449 -1.704484 -0.004162  1.660867

`-` 방법8

In [42]:
df.loc[[0],:]

         X1        X2       X3        X4        X5        X6
0 -0.658169  0.091914 -0.81449 -1.704484 -0.004162  1.660867

### 여러개의 row를 선택하는 방법

### query

### loc이 좋지 않아 보이지만 특정한 경우에는 좋다.

In [49]:
df=pd.DataFrame(np.random.randn(10,4),columns=list('ABCD'),index=pd.date_range('20210101',periods=10))
df

                   A         B         C         D
2021-01-01  1.308201  0.745112 -1.722438  0.408553
2021-01-02 -0.255603 -0.300327 -0.850281 -1.101110
2021-01-03 -1.340047 -1.304547 -0.842687 -1.041202
2021-01-04  0.882868  1.094897  1.021916 -0.716331
2021-01-05 -0.927655  1.136554 -1.035625 -0.398212
2021-01-06 -0.147858  0.307507  0.215350  1.583215
2021-01-07  0.853676 -1.613966  0.509605 -1.047522
2021-01-08 -2.393192  0.155917  1.425639  0.873068
2021-01-09  1.176703  0.417824 -0.999917 -0.726004
2021-01-10 -0.656988  1.025332 -0.925161  0.651822

In [50]:
df.iloc[0:2]

                   A         B         C         D
2021-01-01  1.308201  0.745112 -1.722438  0.408553
2021-01-02 -0.255603 -0.300327 -0.850281 -1.101110

In [51]:
df.loc['20210103':'20210105']

                   A         B         C         D
2021-01-03 -1.340047 -1.304547 -0.842687 -1.041202
2021-01-04  0.882868  1.094897  1.021916 -0.716331
2021-01-05 -0.927655  1.136554 -1.035625 -0.398212

#### 자주하는 실수

`-` 나는 아래와 같은 실수를 많이함

In [55]:
df.loc['A']

KeyError: 'A'

`-` 올바른 방법

In [56]:
df['A']

2021-01-01    1.308201
2021-01-02   -0.255603
2021-01-03   -1.340047
2021-01-04    0.882868
2021-01-05   -0.927655
2021-01-06   -0.147858
2021-01-07    0.853676
2021-01-08   -2.393192
2021-01-09    1.176703
2021-01-10   -0.656988
Freq: D, Name: A, dtype: float64

- 이런방식이 사실 좀 이상해보여서 한번쓰기 시작하면 잘쓰는데 금방까먹고 다시 헷갈림

`-` 아래의 사실을 기억하자. 
- 기본적으로 loc, iloc은 `[2], [2:]` 처럼 1차원으로 원소를 인덱싱할수도 있고, `[2,3], [:,2]`와 같이 2차원으로 인덱싱 할수도 있다. 
- 1차원으로 인덱싱하는 경우는 기본적으로 행을 인덱싱한다. $\to$ **loc, iloc은 행과 더 친하고 열과 친하지 않다.**
- 따라서 열을 선택하는 방법에 있어서 loc, iloc이 그렇게 친화적인 방법은 아니다. 
- 그렇지만 달리 열을 선택하는 쉬운 방법이 존재하지 않아서 열을 선택할때에도 loc, iloc이 선호된다.

### 슬라이싱 응용

In [47]:
df=pd.DataFrame(np.random.randn(10,4),columns=list('ABCD'),index=pd.date_range('20210101',periods=10))
df.iloc[::2,]

                   A         B         C         D
2021-01-01 -0.399492 -1.465394 -1.161074 -0.940827
2021-01-03 -1.855837 -0.584542  1.845818 -1.142946
2021-01-05  0.351611  1.485227 -0.623116 -0.334575
2021-01-07 -0.608715  1.296258  0.523356  0.153775
2021-01-09  2.500330 -1.327873  0.167305 -0.815922