# (시험) R 입문 중간고사 
- toc:true
- branch: master
- badges: true
- comments: true
- author: 최규빈
- hide: true
- categories: [R]

### 100라커 

복도에 100개의 라커가 있다. 어떤 남자가 100개의 라커 문을 전부 연다. 그리고 나서 짝수 번호의 라커를 전부 닫는다. 그 다음에는 번호가 3의 배수인 라커를 순서대로 찾아다니며 열려 있으면 닫고, 닫혀 있으면 연다. 이런식으로 복도를 100번 지나가면 열린 라커의 문은 몇개가 되겠는가?

In [10]:
library(tidyverse)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.3     ✔ dplyr   1.0.7
✔ tidyr   1.1.3     ✔ stringr 1.4.0
✔ readr   1.4.0     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [53]:
x=rep(FALSE,100)

In [54]:
x

  [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [25] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [37] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [49] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [61] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [73] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [85] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [97] FALSE FALSE FALSE FALSE

In [55]:
f<-function(x) !x

In [56]:
x %>% f

  [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [16] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [31] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [46] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [61] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [76] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [91] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE

In [57]:
g<-function(x,a){
    x[(1:100) %% a == 0]=f(x[(1:100) %% a == 0])
    x
}

In [58]:
x %>% f %>% g(2)

  [1]  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE
 [13]  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE
 [25]  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE
 [37]  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE
 [49]  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE
 [61]  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE
 [73]  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE
 [85]  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE
 [97]  TRUE FALSE  TRUE FALSE

In [59]:
x # 
x=f(x) # 1회 복도를 지나감
for(i in 2:100){
    x= g(x,i) 
}

  [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [25] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [37] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [49] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [61] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [73] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [85] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [97] FALSE FALSE FALSE FALSE

In [60]:
sum(x)

[1] 10

### 무궁화 꽃이 피었습니다.

> youtube: https://www.youtube.com/watch?v=jypCdAI-Y7I

총 456명의 참가자가 '무궁화 꽃이 피었습니다' 게임에 참가한다. 기본적인 게임의 규칙은 아래와 같다. 

- 참가자는 제한시간내에 술래가 있는 곳 까지 이동해야 살 수 있다. 

- 술래는 벽을 보고 $x$초간 '무궁화 꽃이 피었습니다'를 외치다가 구호가 끝남과 동시에 뒤를 돌아본다. 이때 움직이는 사람은 **죽는다**

따라서 참가자는 술래가 벽을 보고 '무궁화 꽃이 피었습니다'를 외치는 동안만 이동할 수 있다. 욕심을 부려 더 이동하고자 하면 죽을 수 있다. 반대로 죽는 것을 지나치게 두려워한 나머지 매턴마다 조금씩만 이동한다면 제한시간 내에 술래에게 도달하지 못하여 죽는다. 
게임환경과 관련된 세부적인 설정은 아래와 같다. 

- 술래와 참가자의 거리는 25이다. 

- 모든 참가자는 1초에 거리1이상 움직일 수 없다고 가정한다. (예를들어 2.4초 동안은 최대 2.4의 거리를 이동할 수 있다. 반면 이동을 원치않으면 0의 거리만큼 움직이므로 0~2.4사이의 거리를 움직일 수 있다) 

- 시간제한은 100초이다. 

- 술래는 처음 벽을 보고 $x$초간 무궁화 꽃이 피었습니다를 외친다. 

- 시간은 술래가 벽을 보고 외치는 시간동안만 줄어든다. 

술래와 참가자에 대한 설정값은 아래와 같다. 

***술래에 대한 설정값***

- 처음에는 술래가 10초간 무궁화 꽃이 피었습니다를 외친다. 

- 그 다음에는 술래가 9.5초간 무궁화 꽃이 피었습니다를 외친다. 

- 그 다음에도 0.5초씩 구호를 외치는 시간을 줄인다. 이를 2.5초까지 반복한다. 

> Note: $2.5+3+3.5+ \dots + 10 = 100$ 이다. 

***참가자에 대한 설정값*** 

- 처음에는 참가자가 "본인의번호/100"을 계산하여 나온 숫자만큼 움직인다. 즉 10번 참가자는 0.1의 거리를 움직이고 456번 참가자는 4.56의 거리를 움직인다. 

- 그 다음은 처음에 본인이 이동했던 거리에 1씩 더하여 움직인다. 즉 10번 참가자는 1.1의 거리를 움직이고 456번 참가자는 5.56의 거리를 움직인다.

`-` 예시1

10번 참가자의 경우 아래와 같이 이동하므로 

| |1회 |2회 |3회 | 4회 | 5회 | 6회 | 7회 | 8회 |
|:-:|:-:|:-:|:-:| :-:|:-:|:-:| :-:|:-: |
술래의 외침시간  | 10  | 9.5 | 9.0 | 8.5 | 8.0 | 7.5 | 7.0 | 6.5 | 
참가자의 이동폭  | 0.1 | 1.1 | 2.1 | 3.1 | 4.1 | 5.1 | 6.1 | 7.1 |
참가자의 이동거리 | 0.1 | 1.2 | 3.3 | 6.4 | 10.5 | 15.6 | 21.7 | 28.8 |

생존 할 수 있다.

In [244]:
num = 10
stride_temp = 0:15+num/100 
stride_temp2= ifelse(stride_temp<x,stride_temp,0)
stride_temp
stride_temp2

 [1]  0.1  1.1  2.1  3.1  4.1  5.1  6.1  7.1  8.1  9.1 10.1 11.1 12.1 13.1 14.1
[16] 15.1

 [1] 0.1 1.1 2.1 3.1 4.1 5.1 6.1 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0

In [245]:
sum(stride_temp2)

[1] 21.7

`-` 예시2

In [192]:
x=seq(10,2.5,by=-0.5)

In [193]:
x

 [1] 10.0  9.5  9.0  8.5  8.0  7.5  7.0  6.5  6.0  5.5  5.0  4.5  4.0  3.5  3.0
[16]  2.5

In [194]:
length(x)

[1] 16

-

In [195]:
x

 [1] 10.0  9.5  9.0  8.5  8.0  7.5  7.0  6.5  6.0  5.5  5.0  4.5  4.0  3.5  3.0
[16]  2.5

In [223]:
25-21.7

[1] 3.3

In [222]:
stride

 [1] 0.1 1.1 2.1 3.1 4.1 5.1 6.1 6.5 6.0 5.5 5.0 4.5 4.0 3.5 3.0 2.5

In [212]:
cumsum(0:15+10/100)

 [1]   0.1   1.2   3.3   6.4  10.5  15.6  21.7  28.8  36.9  46.0  56.1  67.2
[13]  79.3  92.4 106.5 121.6

In [197]:
sum((1:16+200/100)[x>1:16+200/100])

[1] 25

In [198]:
1:16+1/100

 [1]  1.01  2.01  3.01  4.01  5.01  6.01  7.01  8.01  9.01 10.01 11.01 12.01
[13] 13.01 14.01 15.01 16.01

In [199]:
x>1:16+1/100

 [1]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE
[13] FALSE FALSE FALSE FALSE

In [200]:
A<-rep(0:15,456)
dim(A)<-c(16,456)
A

      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,]  0    0    0    0    0    0    0    0    0    0    ⋯      0     0
 [2,]  1    1    1    1    1    1    1    1    1    1    ⋯      1     1
 [3,]  2    2    2    2    2    2    2    2    2    2    ⋯      2     2
 [4,]  3    3    3    3    3    3    3    3    3    3    ⋯      3     3
 [5,]  4    4    4    4    4    4    4    4    4    4    ⋯      4     4
 [6,]  5    5    5    5    5    5    5    5    5    5    ⋯      5     5
 [7,]  6    6    6    6    6    6    6    6    6    6    ⋯      6     6
 [8,]  7    7    7    7    7    7    7    7    7    7    ⋯      7     7
 [9,]  8    8    8    8    8    8    8    8    8    8    ⋯      8     8
[10,]  9    9    9    9    9    9    9    9    9    9    ⋯      9     9
[11,] 10   10   10   10   10   10   10   10   10   10    ⋯     10    10
[12,] 11   11   11   11   11   11   11   11   11   11    ⋯     11    11
[13,] 12   12   12   12   12   12   12   12   12   12    ⋯     12    12
[14,] 13   13   13   13   13   13   13   13   13   13    ⋯     13    13
[15,] 14   14   14   14   14   14   14   14   14   14    ⋯     14    14
[16,] 15   15   15   15   15   15   15   15   15   15    ⋯     15    15
      [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21]
 [1,]  0     0     0     0     0     0     0     0
 [2,]  1     1     1     1     1     1     1     1
 [3,]  2     2     2     2     2     2     2     2
 [4,]  3     3     3     3     3     3     3     3
 [5,]  4     4     4     4     4     4     4     4
 [6,]  5     5     5     5     5     5     5     5
 [7,]  6     6     6     6     6     6     6     6
 [8,]  7     7     7     7     7     7     7     7
 [9,]  8     8     8     8     8     8     8     8
[10,]  9     9     9     9     9     9     9     9
[11,] 10    10    10    10    10    10    10    10
[12,] 11    11    11    11    11    11    11    11
[13,] 12    12    12    12    12    12    12    12
[14,] 13    13    13    13    13    13    13    13
[15,] 14    14    14    14    14    14    14    14
[16,] 15    15    15    15    15    15    15    15

In [201]:
B=rep((1:456)/100,16)
dim(B)<-c(456,16)
B=t(B)
B

      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1   ⋯     4.47  4.48
 [2,] 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1   ⋯     4.47  4.48
 [3,] 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1   ⋯     4.47  4.48
 [4,] 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1   ⋯     4.47  4.48
 [5,] 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1   ⋯     4.47  4.48
 [6,] 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1   ⋯     4.47  4.48
 [7,] 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1   ⋯     4.47  4.48
 [8,] 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1   ⋯     4.47  4.48
 [9,] 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1   ⋯     4.47  4.48
[10,] 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1   ⋯     4.47  4.48
[11,] 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1   ⋯     4.47  4.48
[12,] 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1   ⋯     4.47  4.48
[13,] 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1   ⋯     4.47  4.48
[14,] 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1   ⋯     4.47  4.48
[15,] 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1   ⋯     4.47  4.48
[16,] 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1   ⋯     4.47  4.48
      [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21]
 [1,] 4.49  4.5   4.51  4.52  4.53  4.54  4.55  4.56
 [2,] 4.49  4.5   4.51  4.52  4.53  4.54  4.55  4.56
 [3,] 4.49  4.5   4.51  4.52  4.53  4.54  4.55  4.56
 [4,] 4.49  4.5   4.51  4.52  4.53  4.54  4.55  4.56
 [5,] 4.49  4.5   4.51  4.52  4.53  4.54  4.55  4.56
 [6,] 4.49  4.5   4.51  4.52  4.53  4.54  4.55  4.56
 [7,] 4.49  4.5   4.51  4.52  4.53  4.54  4.55  4.56
 [8,] 4.49  4.5   4.51  4.52  4.53  4.54  4.55  4.56
 [9,] 4.49  4.5   4.51  4.52  4.53  4.54  4.55  4.56
[10,] 4.49  4.5   4.51  4.52  4.53  4.54  4.55  4.56
[11,] 4.49  4.5   4.51  4.52  4.53  4.54  4.55  4.56
[12,] 4.49  4.5   4.51  4.52  4.53  4.54  4.55  4.56
[13,] 4.49  4.5   4.51  4.52  4.53  4.54  4.55  4.56
[14,] 4.49  4.5   4.51  4.52  4.53  4.54  4.55  4.56
[15,] 4.49  4.5   4.51  4.52  4.53  4.54  4.55  4.56
[16,] 4.49  4.5   4.51  4.52  4.53  4.54  4.55  4.56

In [202]:
C=A+B
C

      [,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8]  [,9]  [,10] [,11] [,12]
 [1,]  0.01  0.02  0.03  0.04  0.05  0.06  0.07  0.08  0.09  0.1  ⋯      4.47
 [2,]  1.01  1.02  1.03  1.04  1.05  1.06  1.07  1.08  1.09  1.1  ⋯      5.47
 [3,]  2.01  2.02  2.03  2.04  2.05  2.06  2.07  2.08  2.09  2.1  ⋯      6.47
 [4,]  3.01  3.02  3.03  3.04  3.05  3.06  3.07  3.08  3.09  3.1  ⋯      7.47
 [5,]  4.01  4.02  4.03  4.04  4.05  4.06  4.07  4.08  4.09  4.1  ⋯      8.47
 [6,]  5.01  5.02  5.03  5.04  5.05  5.06  5.07  5.08  5.09  5.1  ⋯      9.47
 [7,]  6.01  6.02  6.03  6.04  6.05  6.06  6.07  6.08  6.09  6.1  ⋯     10.47
 [8,]  7.01  7.02  7.03  7.04  7.05  7.06  7.07  7.08  7.09  7.1  ⋯     11.47
 [9,]  8.01  8.02  8.03  8.04  8.05  8.06  8.07  8.08  8.09  8.1  ⋯     12.47
[10,]  9.01  9.02  9.03  9.04  9.05  9.06  9.07  9.08  9.09  9.1  ⋯     13.47
[11,] 10.01 10.02 10.03 10.04 10.05 10.06 10.07 10.08 10.09 10.1  ⋯     14.47
[12,] 11.01 11.02 11.03 11.04 11.05 11.06 11.07 11.08 11.09 11.1  ⋯     15.47
[13,] 12.01 12.02 12.03 12.04 12.05 12.06 12.07 12.08 12.09 12.1  ⋯     16.47
[14,] 13.01 13.02 13.03 13.04 13.05 13.06 13.07 13.08 13.09 13.1  ⋯     17.47
[15,] 14.01 14.02 14.03 14.04 14.05 14.06 14.07 14.08 14.09 14.1  ⋯     18.47
[16,] 15.01 15.02 15.03 15.04 15.05 15.06 15.07 15.08 15.09 15.1  ⋯     19.47
      [,13] [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21]
 [1,]  4.48  4.49  4.5   4.51  4.52  4.53  4.54  4.55  4.56
 [2,]  5.48  5.49  5.5   5.51  5.52  5.53  5.54  5.55  5.56
 [3,]  6.48  6.49  6.5   6.51  6.52  6.53  6.54  6.55  6.56
 [4,]  7.48  7.49  7.5   7.51  7.52  7.53  7.54  7.55  7.56
 [5,]  8.48  8.49  8.5   8.51  8.52  8.53  8.54  8.55  8.56
 [6,]  9.48  9.49  9.5   9.51  9.52  9.53  9.54  9.55  9.56
 [7,] 10.48 10.49 10.5  10.51 10.52 10.53 10.54 10.55 10.56
 [8,] 11.48 11.49 11.5  11.51 11.52 11.53 11.54 11.55 11.56
 [9,] 12.48 12.49 12.5  12.51 12.52 12.53 12.54 12.55 12.56
[10,] 13.48 13.49 13.5  13.51 13.52 13.53 13.54 13.55 13.56
[11,] 14.48 14.49 14.5  14.51 14.52 14.53 14.54 14.55 14.56
[12,] 15.48 15.49 15.5  15.51 15.52 15.53 15.54 15.55 15.56
[13,] 16.48 16.49 16.5  16.51 16.52 16.53 16.54 16.55 16.56
[14,] 17.48 17.49 17.5  17.51 17.52 17.53 17.54 17.55 17.56
[15,] 18.48 18.49 18.5  18.51 18.52 18.53 18.54 18.55 18.56
[16,] 19.48 19.49 19.5  19.51 19.52 19.53 19.54 19.55 19.56

In [204]:
dist<-c()
for(i in 1:456) dist[i]<-sum(C[,i][C[,i]<x])

In [208]:
sum(dist>25)

[1] 224