# (노트) 판다스 할당

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- categories: [시각화2022]

In [95]:
import pandas as pd
import numpy as np

### 새로운 열 직접입력

`-` 방법1: concat 이용

In [78]:
df= pd.DataFrame({'a':[1,2,3],'b':[2,3,4]})
df2 = pd.DataFrame({'c':[3,4,5]})

In [79]:
pd.concat([df,df2],axis=1)

   a  b  c
0  1  2  3
1  2  3  4
2  3  4  5

`-` 방법2: `[]` 이용

In [80]:
dct = {'a':[1,2,3],'b':[2,3,4]}
df= pd.DataFrame({'a':[1,2,3],'b':[2,3,4]})
df

   a  b
0  1  2
1  2  3
2  3  4

In [81]:
dct['c']=[4,5,6]
dct

{'a': [1, 2, 3], 'b': [2, 3, 4], 'c': [4, 5, 6]}

In [82]:
df['c']=[4,5,6] 
df

   a  b  c
0  1  2  4
1  2  3  5
2  3  4  6

(응용)

In [83]:
df= pd.DataFrame({'a':[1,2,3],'b':[2,3,4]})

In [84]:
df['c'],df['d']=[4,5,6],[7,8,9] 
df

   a  b  c  d
0  1  2  4  7
1  2  3  5  8
2  3  4  6  9

`-` 방법3: `.loc`이용

In [85]:
df= pd.DataFrame({'a':[1,2,3],'b':[2,3,4]})
df

   a  b
0  1  2
1  2  3
2  3  4

In [21]:
df.loc[:,'c'] = [3,4,5] 
df

   a  b  c
0  1  2  3
1  2  3  4
2  3  4  5

`-` 방법4: `.assign` 이용

In [87]:
df= pd.DataFrame({'a':[1,2,3],'b':[2,3,4]})
df

   a  b
0  1  2
1  2  3
2  3  4

In [88]:
df.assign(c=[3,4,5])

   a  b  c
0  1  2  3
1  2  3  4
2  3  4  5

`-` 방법5: `.eval`이용

In [89]:
df.eval('c=[3,4,5]')

   a  b  c
0  1  2  3
1  2  3  4
2  3  4  5

### 기존열을 변환하여 추가

In [91]:
df = pd.DataFrame({'x':[1,2,3],'y':[-1,-3,-5]})
df

   x  y
0  1 -1
1  2 -3
2  3 -5

`-` 방법2,3:

In [110]:
df['r']=np.sqrt(df.x**2 + df.y**2)
df.loc[:,'r']= np.sqrt(df.x**2 + df.y**2)

`-` 방법4

In [111]:
df.assign(r=np.sqrt(df.x**2 + df.y**2))

   x  y         r
0  1 -1  1.414214
1  2 -3  3.605551
2  3 -5  5.830952

`-` 방법5

In [112]:
df.eval('r=sqrt(x**2 + y**2)') # 왜 가능하지?

   x  y         r
0  1 -1  1.414214
1  2 -3  3.605551
2  3 -5  5.830952

### apply + lambda

In [276]:
df.assign(sss = df.att.apply(lambda x: x+1))

     att  rep  mid  fin  sss
0     65   45    0   10   66
1     95   30   60   10   96
2     65   85   15   20   66
3     55   35   35    5   56
4     80   60   55   70   81
..   ...  ...  ...  ...  ...
195   55   70   40   95   56
196   65   85   25   85   66
197   85   85  100   10   86
198   80   65   35   60   81
199   50   95   45   85   51

[200 rows x 5 columns]

***연속할당***

In [281]:
df.eval('sss=att+1').eval('ddd=sss+1')

     att  rep  mid  fin  sss  ddd
0     65   45    0   10   66   67
1     95   30   60   10   96   97
2     65   85   15   20   66   67
3     55   35   35    5   56   57
4     80   60   55   70   81   82
..   ...  ...  ...  ...  ...  ...
195   55   70   40   95   56   57
196   65   85   25   85   66   67
197   85   85  100   10   86   87
198   80   65   35   60   81   82
199   50   95   45   85   51   52

[200 rows x 6 columns]

In [542]:
df.assign(fin2=df.fin*2).assign(fin3= lambda df: df.fin2*2)

     att  rep  mid  fin  fin2  fin3
0     65   45    0   10    20    40
1     95   30   60   10    20    40
2     65   85   15   20    40    80
3     55   35   35    5    10    20
4     80   60   55   70   140   280
..   ...  ...  ...  ...   ...   ...
195   55   70   40   95   190   380
196   65   85   25   85   170   340
197   85   85  100   10    20    40
198   80   65   35   60   120   240
199   50   95   45   85   170   340

[200 rows x 6 columns]