# (노트) 클래스2022(3)

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- categories: [파이썬]

In [2]:
import numpy as np

## 클래스공부 4단계

### motivating example

`-` 가위바위보

In [11]:
class RPC: 
    def __init__(self,candidate=['가위','바위','보']): 
        self.candidate = candidate
    def throw(self):
        print(np.random.choice(self.candidate))

In [12]:
a=RPC()

In [13]:
a.throw()

보

`-` 생각해보니까 throw는 choose+show의 결합인것 같다.

In [21]:
class RPC: 
    def __init__(self,candidate=['가위','바위','보']): 
        self.candidate = candidate
    def choose(self): 
        self.actions=np.random.choice(self.candidate)
    def show(self):
        print(self.actions)

In [22]:
a=RPC()

In [23]:
a.actions

AttributeError: 'RPC' object has no attribute 'actions'

In [24]:
a.choose()

In [25]:
a.actions

'보'

In [26]:
a.show()

보

`-` 또 다른 인스턴스 b를 만들자 b는 가위만 낼 수 있다.

In [28]:
b=RPC(['가위'])

In [40]:
b.choose()
b.show() 
# 계속 가위만 나온다

가위

`-` a,b의 선택들을 모아서 기록하고 싶다.

In [69]:
class RPC: 
    def __init__(self,candidate=['가위','바위','보']): 
        self.candidate = candidate
        self.actions= list()
    def choose(self): 
        self.actions.append(np.random.choice(self.candidate))
    def show(self):
        print(self.actions[-1])

In [70]:
a=RPC()
b=RPC(['가위'])

In [71]:
for i in range(5):
    a.choose()
    a.show()

가위
가위
보
바위
보

In [72]:
a.actions

['가위', '가위', '보', '바위', '보']

In [73]:
for i in range(5):
    b.choose()
    b.show()

가위
가위
가위
가위
가위

In [74]:
b.actions

['가위', '가위', '가위', '가위', '가위']

`-` info라는 함수를 만들어서 a의 오브젝트가 가지고 있는 정보를 모두 보도록 하자.

(예비학습) 문자열에 `\n`이 포함된다면?

In [249]:
'asdf\n1234'

'asdf\n1234'

In [250]:
print('asdf\n1234')

asdf
1234

예비학습 끝

In [157]:
class RPC: 
    def __init__(self,candidate=['가위','바위','보']): 
        self.candidate = candidate
        self.actions= list()
    def choose(self): 
        self.actions.append(np.random.choice(self.candidate))
    def show(self):
        print(self.actions[-1])
    def info(self):
        print('낼 수 있는 패: {}\n기록: {}'.format(self.candidate,self.actions))

In [158]:
a=RPC()
b=RPC(['가위'])

In [159]:
for i in range(5):
    a.choose()
    a.show()

보
바위
보
가위
바위

In [160]:
a.actions

['보', '바위', '보', '가위', '바위']

In [161]:
for i in range(5):
    b.choose()
    b.show()

가위
가위
가위
가위
가위

In [162]:
a.info()

낼 수 있는 패: ['가위', '바위', '보']
기록: ['보', '바위', '보', '가위', '바위']

In [163]:
b.info()

낼 수 있는 패: ['가위']
기록: ['가위', '가위', '가위', '가위', '가위']

`-` 만들고보니까 print의 기능과 거의 비슷함 $\to$ print(a) 하면 a.info()와 동일한 효과를 하도록 만들 수 없을까?

`-` 말도 안되는 소리다. 왜?
- print는 파이썬 내장기능임, 내장기능을 우리가 맘대로 커스터마이징해서 바꿀수는 없을 것 같음. 
- 바꿀 수 있다고 쳐도 문제이다. 그럼 지금까지 우리가 사용했던 수많은 print()의 결과는 어떻게 되는가?

`-` 그런데 a의 자료형(RPC자료형)에 한정해서만 print를 수정하는 것이 가능하다면? (그럼 다른 object들에는 아무런 영향이 없다)

### `__str__`

`-` 관찰1: 현재 print(a)의 결과는 아래와 같다.

In [170]:
print(a)

<__main__.RPC object at 0x7f51d7c50490>

- a는 RPC 클래스에서 만들어진 오브젝트이며, a가 저장된 메모리의 주소는 0x7f51d7c50490라는 의미

`-` 관찰2: a라는 오브젝트에는 `__str__()`이라는 숨겨진 메소드가 있다.

In [174]:
set(dir(a)) & {'__str__'}

{'__str__'}

이걸 실행하면 아래와 같이 된다.

In [175]:
a.__str__()

'<__main__.RPC object at 0x7f51d7c50490>'

?? print(a)해서 나오게 되는 문자열이 리턴된다

In [192]:
print(a.__str__()) # 이거 print(a)와 결과가 같다..?

guebin hahaha

`-` 생각: 만약에 내가 `a.__str__()` 라는 함수를 재정의하여 리턴값을 'guebin hahaha'로 바꾸게 되면 print(a)해서 나오는 결과는 어떻게 될까? (약간 해커같죠)

(예비학습) 함수덮어씌우기

In [176]:
def f():
    print('asdf')

In [177]:
f()

asdf

In [178]:
def f():
    print('guebin hahaha')

In [179]:
f()

guebin hahaha

이런식으로 함수가 이미 정외되어 있더라도, 내가 나중에 덮어씌우면 그 함수의 기능을 다시정의한다.

(해킹시작)

In [185]:
class RPC: 
    def __init__(self,candidate=['가위','바위','보']): 
        self.candidate = candidate
        self.actions= list()
    def choose(self): 
        self.actions.append(np.random.choice(self.candidate))
    def show(self):
        print(self.actions[-1])
    def __str__(self):
        return 'guebin hahaha'
    def info(self):
        print('낼 수 있는 패: {}\n기록: {}'.format(self.candidate,self.actions))

In [186]:
a=RPC()

In [187]:
print(a)

guebin hahaha

In [188]:
print(a.__str__())

guebin hahaha

- 헐..

`-` `__str__`의 리턴값을 info에서 타이핑했던 문자열로 재정의한다면?

In [196]:
class RPC: 
    def __init__(self,candidate=['가위','바위','보']): 
        self.candidate = candidate
        self.actions= list()
    def choose(self): 
        self.actions.append(np.random.choice(self.candidate))
    def show(self):
        print(self.actions[-1])
    def __str__(self):
        return '낼 수 있는 패: {}\n기록: {}'.format(self.candidate,self.actions)

In [197]:
a=RPC()

In [198]:
print(a)

낼 수 있는 패: ['가위', '바위', '보']
기록: []

### 파이썬의 비밀2

`-` 아래는 같은 문법이다. 
- `print(a)`, `print(a.__str__())`

`-` 참고로 `a.__str__()`와 `str(a)`도 같은 문법이다!

In [202]:
str(a)

"낼 수 있는 패: ['가위', '바위', '보']\n기록: []"

In [203]:
a.__str__()

"낼 수 있는 패: ['가위', '바위', '보']\n기록: []"

`-` 지금까지 우리가 썼던 기능들 확인!

(에제1)

In [211]:
a=[1,2,3]

In [212]:
print(a)

[1, 2, 3]

In [213]:
a.__str__()

'[1, 2, 3]'

In [214]:
str(a)

'[1, 2, 3]'

(예제2)

In [231]:
a={1,2,3}
print(a)

{1, 2, 3}

In [232]:
str(a)

'{1, 2, 3}'

In [233]:
a.__str__()

'{1, 2, 3}'

(예제3)

In [217]:
a=np.array(1)
a.shape

()

In [221]:
print(a.shape)

()

In [227]:
a.shape # 이거 자체가 이미 오브젝트임 (튜플)

()

In [225]:
a.shape.__str__()

'()'

In [226]:
str(a.shape)

'()'

(예제4)

In [237]:
a=range(10)
print(a)

range(0, 10)

In [238]:
str(a)

'range(0, 10)'

In [240]:
a.__str__()

'range(0, 10)'

(예제5)

In [328]:
a = np.arange(100).reshape(10,10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

In [329]:
a.__str__()

'[[ 0  1  2  3  4  5  6  7  8  9]\n [10 11 12 13 14 15 16 17 18 19]\n [20 21 22 23 24 25 26 27 28 29]\n [30 31 32 33 34 35 36 37 38 39]\n [40 41 42 43 44 45 46 47 48 49]\n [50 51 52 53 54 55 56 57 58 59]\n [60 61 62 63 64 65 66 67 68 69]\n [70 71 72 73 74 75 76 77 78 79]\n [80 81 82 83 84 85 86 87 88 89]\n [90 91 92 93 94 95 96 97 98 99]]'

In [330]:
str(a)

'[[ 0  1  2  3  4  5  6  7  8  9]\n [10 11 12 13 14 15 16 17 18 19]\n [20 21 22 23 24 25 26 27 28 29]\n [30 31 32 33 34 35 36 37 38 39]\n [40 41 42 43 44 45 46 47 48 49]\n [50 51 52 53 54 55 56 57 58 59]\n [60 61 62 63 64 65 66 67 68 69]\n [70 71 72 73 74 75 76 77 78 79]\n [80 81 82 83 84 85 86 87 88 89]\n [90 91 92 93 94 95 96 97 98 99]]'

### `__repr__`

`-` 생각해보니까.. print를 해서 우리가 원하는 정보를 확인한건 아니었음.

In [251]:
a=[1,2,3]

In [252]:
a

[1, 2, 3]

In [253]:
print(a)

[1, 2, 3]

`-` print(a)의 결과가 저렇게 나오는것은 이해함. 그렇다면 주피터셀에 a만 치면 자동으로 print(a)가 실행되도록 약속된건가?

(반례)

In [258]:
a=np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [259]:
print(a)

[[1 2]
 [3 4]]

`-` print(a)를 쳐서 나오는 결과와 주피터셀에 a만 쳐서 나오는 결과가 다르다? $\to$ 서로 다른 숨겨진 기능이 있다! $\to$ 결론: 그 기능은 `__repr__`에 저장됨

In [265]:
class RPC: 
    def __init__(self,candidate=['가위','바위','보']): 
        self.candidate = candidate
        self.actions= list()
    def choose(self): 
        self.actions.append(np.random.choice(self.candidate))
    def show(self):
        print(self.actions[-1])
    def __repr__(self):
        return '낼 수 있는 패: {}\n기록: {}'.format(self.candidate,self.actions)

In [266]:
a=RPC()

In [267]:
a

낼 수 있는 패: ['가위', '바위', '보']
기록: []

`-` 그럼 우리가 지금까지 했던것은?

In [270]:
a = np.array([1,2,3])

In [271]:
a

array([1, 2, 3])

In [272]:
print(a)

[1 2 3]

In [273]:
a.__repr__()

'array([1, 2, 3])'

In [282]:
a.__str__()

'[1 2 3]'

### 파이썬의 비밀3

`-` 대화형 콘솔에서 오브젝트를 칠때 나오는출력은 `__repr__`의 결과와 연관있다.

In [331]:
a=np.array(range(10000)).reshape(100,100)
a

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [332]:
a.__repr__()

'array([[   0,    1,    2, ...,   97,   98,   99],\n       [ 100,  101,  102, ...,  197,  198,  199],\n       [ 200,  201,  202, ...,  297,  298,  299],\n       ...,\n       [9700, 9701, 9702, ..., 9797, 9798, 9799],\n       [9800, 9801, 9802, ..., 9897, 9898, 9899],\n       [9900, 9901, 9902, ..., 9997, 9998, 9999]])'

`-` 참고로 `a.__repr__()`은 `repr(a)`와 같다.

In [283]:
repr(a)

'array([1, 2, 3])'

### 주피터노트북의 비밀

`-` 요즘은 IDE의 발전에 따라서 오브젝트 이름을 칠때 나온는 출력도 다양해 지고 있다. -> 다양한 `__repr__`이 존재

In [344]:
import pandas as pd

In [345]:
df= pd.DataFrame({'a':[1,2,3],'b':[2,3,4]})

In [346]:
df

   a  b
0  1  2
1  2  3
2  3  4

- 예쁘게 나온다

`-` 그런데? `df.__repr__()`은 조금 다르게 나온다?

In [347]:
df.__repr__()

'   a  b\n0  1  2\n1  2  3\n2  3  4'

In [348]:
print(df.__repr__())

   a  b
0  1  2
1  2  3
2  3  4

`-` 위의 출력 `print(df.__repr__())`은 검은화면에서나 나오는 출력임.
```
Python 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:37) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> pd.DataFrame({'a':[1,2,3],'b':[2,3,4]})
   a  b
0  1  2
1  2  3
2  3  4
>>> 
```

`-` 주피터에서는 아래가 출력된다.

In [349]:
df._repr_html_()

'<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>a</th>\n      <th>b</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>3</td>\n      <td>4</td>\n    </tr>\n  </tbody>\n</table>\n</div>'

- html코드!

In [350]:
from IPython.core.display import HTML

In [351]:
HTML(df._repr_html_())

`-` 해석: `_repr_html_()`을 숨겨진 메소드로 가지고 있고 그것을 html출력이 지원되는 IDE라면 `_repr_html_()`이 출력된다. html출력이 지원되지 않으면 `__repr__()`이 출력된다.

### `__repr__` 와 `__str__` 의 우선적용 순위

(예제1)

`-` 아래의 예제를 관찰하자.

In [352]:
class RPC: 
    def __init__(self,candidate=['가위','바위','보']): 
        self.candidate = candidate
        self.actions= list()
    def choose(self): 
        self.actions.append(np.random.choice(self.candidate))
    def show(self):
        print(self.actions[-1])
    def __repr__(self):
        return '낼 수 있는 패: {}\n기록: {}'.format(self.candidate,self.actions)

In [354]:
a=RPC()
a

낼 수 있는 패: ['가위', '바위', '보']
기록: []

In [356]:
a.__repr__()

"낼 수 있는 패: ['가위', '바위', '보']\n기록: []"

In [357]:
repr(a)

"낼 수 있는 패: ['가위', '바위', '보']\n기록: []"

`-` 여기까지는 상식수준의 결과임. 이번엔 아래를 관찰하라!

In [358]:
print(a)

낼 수 있는 패: ['가위', '바위', '보']
기록: []

In [359]:
a.__str__()

"낼 수 있는 패: ['가위', '바위', '보']\n기록: []"

In [360]:
str(a)

"낼 수 있는 패: ['가위', '바위', '보']\n기록: []"

- `__str__()`은 건드린적이 없을텐데?

`-` 확인

In [362]:
a.__repr__??

Signature: a.__repr__()
Docstring: Return repr(self).
Source:
    def __repr__(self):
        return '낼 수 있는 패: {}\n기록: {}'.format(self.candidate,self.actions)
File:      /tmp/ipykernel_2763278/506176316.py
Type:      method

In [363]:
a.__str__??

Signature:      a.__str__()
Call signature: a.__str__(*args, **kwargs)
Type:           method-wrapper
String form:    <method-wrapper '__str__' of RPC object at 0x7f51d51feee0>
Docstring:      Return str(self).

- 건든적이 없는데 기능은 바껴있다.

(예제2)

`-` 아래의 예제를 관찰하자.

In [364]:
class RPC: 
    def __init__(self,candidate=['가위','바위','보']): 
        self.candidate = candidate
        self.actions= list()
    def choose(self): 
        self.actions.append(np.random.choice(self.candidate))
    def show(self):
        print(self.actions[-1])
    def __str__(self):
        return '낼 수 있는 패: {}\n기록: {}'.format(self.candidate,self.actions)

In [365]:
a=RPC()

In [366]:
a

In [367]:
print(a)

낼 수 있는 패: ['가위', '바위', '보']
기록: []

In [368]:
a.__str__??

Signature: a.__str__()
Docstring: Return str(self).
Source:
    def __str__(self):
        return '낼 수 있는 패: {}\n기록: {}'.format(self.candidate,self.actions)
File:      /tmp/ipykernel_2763278/2534088838.py
Type:      method

In [369]:
a.__repr__??

Signature:      a.__repr__()
Call signature: a.__repr__(*args, **kwargs)
Type:           method-wrapper
String form:    <method-wrapper '__repr__' of RPC object at 0x7f51d4c7d760>
Docstring:      Return repr(self).

`-` 요약: `__str__()`을 수정하여도 `__repr__()`의 기능은 바뀌지 않는다. 그런데 `__repr__()`을 수정하면 `__str__()`의 기능도 자동으로 수정된다.

`-` 따로따로 되는거 봤는데?

In [459]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [460]:
print(a)

[[1 2]
 [3 4]]

`-` 둘다 선언하면된다.

In [524]:
class RPC: 
    def __init__(self,candidate=['가위','바위','보']): 
        self.candidate = candidate
        self.actions= list()
    def choose(self): 
        self.actions.append(np.random.choice(self.candidate))
    def show(self):
        print(self.actions[-1])
    def __str__(self):
        return 'guebin hahaha'
    def __repr__(self):
        return '낼 수 있는 패: {}\n기록: {}'.format(self.candidate,self.actions)

In [525]:
a=RPC()

In [526]:
print(a)

guebin hahaha

In [527]:
a

낼 수 있는 패: ['가위', '바위', '보']
기록: []

`-` `__str__`, `__repr__` 을 건드리지 않고 싶다면?

In [561]:
class RPC: 
    def __init__(self,candidate=['가위','바위','보']): 
        self.candidate = candidate
        self.actions= list()
    def choose(self): 
        self.actions.append(np.random.choice(self.candidate))
    def show(self):
        print(self.actions[-1])
    def _repr_html_(self):
        html_str = """
        낼 수 있는 패: {} <br/>
        기록: {}
        """
        return html_str.format(self.candidate,self.actions)

In [562]:
a=RPC()

In [563]:
str(a)

'<__main__.RPC object at 0x7f51d1602b20>'

In [564]:
repr(a)

'<__main__.RPC object at 0x7f51d1602b20>'

In [565]:
a

In [566]:
for i in range(5):
    a.choose()
    a.show()

보
보
바위
가위
바위

In [567]:
a

## 클래스공부 5단계