# (노트) 분류분석 (3)

- toc:true
- branch: master
- badges: true
- comments: true
- author: 최규빈
- hide: false
- categories: [ADsP]

### 토익, 학점 --> 합격

In [97]:
토익=c(300,350,400,450,
     500,500,500,500,
     650,700,750,700)
학점=c(2,2,3,3,
     2,3,2,3,
     3,4,3,4)
합격=c(0,0,1,0,
     1,1,0,0,
     1,1,1,0)

In [98]:
X = cbind(토익,학점)
y = 합격

In [99]:
데이터 = cbind(X,y)
데이터

      토익 학점 y
 [1,] 300  2    0
 [2,] 350  2    0
 [3,] 400  3    1
 [4,] 450  3    0
 [5,] 500  2    1
 [6,] 500  3    1
 [7,] 500  2    0
 [8,] 500  3    0
 [9,] 650  3    1
[10,] 700  4    1
[11,] 750  3    1
[12,] 700  4    0

### 로지스틱

`-` `합격 = b0 + 토익*b1 + 학점*b2` 를 만족하는 적절한 b0, b1, b2를 구하고 싶음 --> 회귀모형이네

In [100]:
lm(합격 ~ 토익+학점)

Call:
lm(formula = 합격 ~ 토익 + 학점)

Coefficients:
(Intercept)         토익         학점
  -0.218327     0.001747    -0.070111

In [102]:
b0=  -0.218327
b1= 0.001747 
b2= -0.070111

- 모형: `합격 = b0 + 토익*b1 + 학점*b2`

확인해보자.

In [103]:
X

      토익 학점
 [1,] 300  2
 [2,] 350  2
 [3,] 400  3
 [4,] 450  3
 [5,] 500  2
 [6,] 500  3
 [7,] 500  2
 [8,] 500  3
 [9,] 650  3
[10,] 700  4
[11,] 750  3
[12,] 700  4

In [105]:
b0 + 300*b1 + 2*b2 # 1번관측치가 합격할 확률

[1] 0.165551

In [106]:
b0 + 700*b1 + 4*b2 # 마지막관측치가 합격할 확률

[1] 0.724129

`-` 관찰: 학생들의 학점,토익점수를 넣기만 하면 확률이 예측되는군?

`-` 학점 4.5, 토익 995를 대입해보자. --> 합격확률은 거의 1

In [107]:
b0 + 995*b1 + 4.5*b2

[1] 1.204439

`-` 1이 넘는다? $\to$ 안넘었으면 좋겠는데?

`-` 로지스틱이라는걸 만들자.