# 연습장

In [9]:
import pandas as pd
import numpy as np

In [10]:
sa= pd.Series([1,2,3],index=list('abc'))

In [11]:
sa.b

2

In [12]:
dfa=df.copy()

NameError: name 'df' is not defined

In [15]:
dates=pd.date_range('1/1/2000', periods=8)

In [16]:
df=pd.DataFrame(np.random.randn(8,4),index=dates, columns=['A','B','C','D'])

In [17]:
df

                   A         B         C         D
2000-01-01  0.599195 -0.156579 -0.737755  0.771692
2000-01-02  0.554362  1.550815  0.228813  1.341562
2000-01-03  2.432237 -1.677383 -0.424558  1.574645
2000-01-04 -0.187302  1.292429 -1.291211 -1.476967
2000-01-05  0.450574  1.081492 -0.494514 -1.073831
2000-01-06  0.691768  1.260473  0.806306 -0.097995
2000-01-07 -0.643412  1.168977  0.595487  0.802224
2000-01-08 -1.247871  0.663575  0.941541 -0.944152

In [20]:
df.iloc[:,::-1]

                   D         C         B         A
2000-01-01  0.771692 -0.737755 -0.156579  0.599195
2000-01-02  1.341562  0.228813  1.550815  0.554362
2000-01-03  1.574645 -0.424558 -1.677383  2.432237
2000-01-04 -1.476967 -1.291211  1.292429 -0.187302
2000-01-05 -1.073831 -0.494514  1.081492  0.450574
2000-01-06 -0.097995  0.806306  1.260473  0.691768
2000-01-07  0.802224  0.595487  1.168977 -0.643412
2000-01-08 -0.944152  0.941541  0.663575 -1.247871

In [21]:
df=pd.read_csv('https://raw.githubusercontent.com/PacktPublishing/Pandas-Cookbook/master/data/movie.csv')
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [24]:
df.loc[:,lambda x : 'actor' in x, df.columns]

IndexingError: Too many indexers