# 할당

In [276]:
df.assign(sss = df.att.apply(lambda x: x+1))

     att  rep  mid  fin  sss
0     65   45    0   10   66
1     95   30   60   10   96
2     65   85   15   20   66
3     55   35   35    5   56
4     80   60   55   70   81
..   ...  ...  ...  ...  ...
195   55   70   40   95   56
196   65   85   25   85   66
197   85   85  100   10   86
198   80   65   35   60   81
199   50   95   45   85   51

[200 rows x 5 columns]

In [281]:
df.eval('sss=att+1').eval('ddd=sss+1')

     att  rep  mid  fin  sss  ddd
0     65   45    0   10   66   67
1     95   30   60   10   96   97
2     65   85   15   20   66   67
3     55   35   35    5   56   57
4     80   60   55   70   81   82
..   ...  ...  ...  ...  ...  ...
195   55   70   40   95   56   57
196   65   85   25   85   66   67
197   85   85  100   10   86   87
198   80   65   35   60   81   82
199   50   95   45   85   51   52

[200 rows x 6 columns]

***연속할당***

In [542]:
df.assign(fin2=df.fin*2).assign(fin3= lambda df: df.fin2*2)

     att  rep  mid  fin  fin2  fin3
0     65   45    0   10    20    40
1     95   30   60   10    20    40
2     65   85   15   20    40    80
3     55   35   35    5    10    20
4     80   60   55   70   140   280
..   ...  ...  ...  ...   ...   ...
195   55   70   40   95   190   380
196   65   85   25   85   170   340
197   85   85  100   10    20    40
198   80   65   35   60   120   240
199   50   95   45   85   170   340

[200 rows x 6 columns]