# 기후자료

#### Step1: Pandas

In [35]:
fnames=['202101.csv','202102.csv','202103.csv','202104.csv','202105.csv','202106.csv','202107.csv','202108.csv','202109.csv','202110.csv']
dfs=[pd.read_csv('https://raw.githubusercontent.com/guebin/2021DV/master/_notebooks/'+fnames[i]) for i in range(len(fnames))]

In [36]:
ks=['2021-'+str(i) for i in range(1,11)] 
ks

['2021-1',
 '2021-2',
 '2021-3',
 '2021-4',
 '2021-5',
 '2021-6',
 '2021-7',
 '2021-8',
 '2021-9',
 '2021-10']

In [37]:
df=pd.concat(dfs,keys=ks).reset_index().rename(columns={'level_0':'month','level_1':'dindex'}).dropna()
df

,month,dindex,지점정보,경도,위도,평균기온(°C),최저기온(°C),최고기온(°C)
0,2021-1,0,속초(90),128.56473,38.25085,-1.2,-5.5,2.9
1,2021-1,1,북춘천(93),127.75443,37.94738,-5.7,-11.8,0.7
2,2021-1,2,철원(95),127.30420,38.14787,-5.9,-12.6,0.7
3,2021-1,3,동두천(98),127.06070,37.90188,-4.2,-9.9,2.1
4,2021-1,4,파주(99),126.76648,37.88589,-5.1,-11.4,1.5
...,...,...,...,...,...,...,...,...
945,2021-10,90,합천(285),128.16994,35.56505,15.4,10.3,22.6
946,2021-10,91,밀양(288),128.74412,35.49147,16.5,11.2,23.4
947,2021-10,92,산청(289),127.87910,35.41300,14.9,9.4,22.3
948,2021-10,93,거제(294),128.60459,34.88818,17.4,13.5,22.4
949,2021-10,94,남해(295),127.92641,34.81662,17.2,13.5,22.3

In [38]:
df.assign(color=list(map(lambda x: 'red' if x > 0 else 'blue',df.iloc[:,5])))

,month,dindex,지점정보,경도,위도,평균기온(°C),최저기온(°C),최고기온(°C),color
0,2021-1,0,속초(90),128.56473,38.25085,-1.2,-5.5,2.9,blue
1,2021-1,1,북춘천(93),127.75443,37.94738,-5.7,-11.8,0.7,blue
2,2021-1,2,철원(95),127.30420,38.14787,-5.9,-12.6,0.7,blue
3,2021-1,3,동두천(98),127.06070,37.90188,-4.2,-9.9,2.1,blue
4,2021-1,4,파주(99),126.76648,37.88589,-5.1,-11.4,1.5,blue
...,...,...,...,...,...,...,...,...,...
945,2021-10,90,합천(285),128.16994,35.56505,15.4,10.3,22.6,red
946,2021-10,91,밀양(288),128.74412,35.49147,16.5,11.2,23.4,red
947,2021-10,92,산청(289),127.87910,35.41300,14.9,9.4,22.3,red
948,2021-10,93,거제(294),128.60459,34.88818,17.4,13.5,22.4,red
949,2021-10,94,남해(295),127.92641,34.81662,17.2,13.5,22.3,red

In [39]:
df.\
assign(color=list(map(lambda x: 'red' if x > 0 else 'blue',df.iloc[:,5]))).\
groupby('month').\
pipe(list)

[('2021-1',
       month  dindex     지점정보         경도        위도  평균기온(°C)  최저기온(°C)  \
  0   2021-1       0   속초(90)  128.56473  38.25085      -1.2      -5.5
  1   2021-1       1  북춘천(93)  127.75443  37.94738      -5.7     -11.8
  2   2021-1       2   철원(95)  127.30420  38.14787      -5.9     -12.6
  3   2021-1       3  동두천(98)  127.06070  37.90188      -4.2      -9.9
  4   2021-1       4   파주(99)  126.76648  37.88589      -5.1     -11.4
  ..     ...     ...      ...        ...       ...       ...       ...
  90  2021-1      90  합천(285)  128.16994  35.56505       0.1      -5.8
  91  2021-1      91  밀양(288)  128.74412  35.49147       0.4      -5.3
  92  2021-1      92  산청(289)  127.87910  35.41300      -0.2      -5.5
  93  2021-1      93  거제(294)  128.60459  34.88818       2.9      -1.3
  94  2021-1      94  남해(295)  127.92641  34.81662       2.3      -2.2

      최고기온(°C) color
  0        2.9  blue
  1        0.7  blue
  2        0.7  blue
  3        2.1  blue
  4        1.5  blue
  ..       ...   ...
  90       7.1   red
  91       7.0   red
  92       6.1  blue
  93       7.2   red
  94       7.1   red

  [95 rows x 9 columns]),
 ('2021-10',
         month  dindex     지점정보         경도        위도  평균기온(°C)  최저기온(°C)  \
  855  2021-10       0   속초(90)  128.56473  38.25085      15.5      11.6
  856  2021-10       1  북춘천(93)  127.75443  37.94738      13.1       7.9
  857  2021-10       2   철원(95)  127.30420  38.14787      12.7       7.3
  858  2021-10       3  동두천(98)  127.06070  37.90188      13.7       8.5
  859  2021-10       4   파주(99)  126.76648  37.88589      13.0       7.6
  ..       ...     ...      ...        ...       ...       ...       ...
  945  2021-10      90  합천(285)  128.16994  35.56505      15.4      10.3
  946  2021-10      91  밀양(288)  128.74412  35.49147      16.5      11.2
  947  2021-10      92  산청(289)  127.87910  35.41300      14.9       9.4
  948  2021-10      93  거제(294)  128.60459  34.88818      17.4      13.5
  949  2021-10      94  남해(295)  127.92641  34.81662      17.2      13.5

       최고기온(°C) color
  855      20.0   red
  856      19.6   red
  857      19.2   red
  858      19.9   red
  859      19.8   red
  ..        ...   ...
  945      22.6   red
  946      23.4   red
  947      22.3   red
  948      22.4   red
  949      22.3   red

  [95 rows x 9 columns]),
 ('2021-2',
        month  dindex     지점정보         경도        위도  평균기온(°C)  최저기온(°C)  \
  95   2021-2       0   속초(90)  128.56473  38.25085       3.1      -1.5
  96   2021-2       1  북춘천(93)  127.75443  37.94738       0.4      -6.3
  97   2021-2       2   철원(95)  127.30420  38.14787       0.1      -6.7
  98   2021-2       3  동두천(98)  127.06070  37.90188       1.3      -5.0
  99   2021-2       4   파주(99)  126.76648  37.88589       0.5      -6.1
  ..      ...     ...      ...        ...       ...       ...       ...
  185  2021-2      90  합천(285)  128.16994  35.56505       4.3      -2.4
  186  2021-2      91  밀양(288)  128.74412  35.49147       4.3      -2.4
  187  2021-2      92  산청(289)  127.87910  35.41300       3.7      -2.3
  188  2021-2      93  거제(294)  128.60459  34.88818       6.6       2.2
  189  2021-2      94  남해(295)  127.92641  34.81662       6.1       1.1

       최고기온(°C) color
  95        7.7   red
  96        7.6   red
  97        6.8   red
  98        8.4   red
  99        7.2   red
  ..        ...   ...
  185      12.1   red
  186      11.7   red
  187      11.0   red
  188      11.3   red
  189      11.3   red

  [95 rows x 9 columns]),
 ('2021-3',
        month  dindex     지점정보         경도        위도  평균기온(°C)  최저기온(°C)  \
  190  2021-3       0   속초(90)  128.56473  38.25085       8.0       3.7
  191  2021-3       1  북춘천(93)  127.75443  37.94738       7.1       0.5
  192  2021-3       2   철원(95)  127.30420  38.14787       6.2      -0.3
  193  2021-3       3  동두천(98)  127.06070  37.90188       7.7       1.6
  194  2021-3       4   파주(99)  126.76648  37.88589       6.7       0.4
  ..      ...     ...      ...        ...       ...       ...       ...
  280  2021-3      90  합천(285)  128.16994  35.56505       9.7       3.4
  281  2021-3      91  밀양(288)  128.74412  35.49147      10.1       3.9
  282  2021-3      92  산청(289)  127.87910  35.41300       9.5       3.1
  283  2021-3      93  거제(294)  128.60459  34.88818      10.8       6.4
  284  2021-3      94  남해(295)  127.92641  34.81662      10.6       6.0

       최고기온(°C) color
  190      12.6   red
  191      14.3   red
  192      13.4   red
  193      15.5   red
  194      14.0   red
  ..        ...   ...
  280      16.4   red
  281      16.9   red
  282      16.2   red
  283      15.6   red
  284      15.8   red

  [95 rows x 9 columns]),
 ('2021-4',
        month  dindex     지점정보         경도        위도  평균기온(°C)  최저기온(°C)  \
  285  2021-4       0   속초(90)  128.56473  38.25085      12.3       7.8
  286  2021-4       1  북춘천(93)  127.75443  37.94738      12.4       5.5
  287  2021-4       2   철원(95)  127.30420  38.14787      12.0       5.2
  288  2021-4       3  동두천(98)  127.06070  37.90188      13.0       6.7
  289  2021-4       4   파주(99)  126.76648  37.88589      12.2       5.8
  ..      ...     ...      ...        ...       ...       ...       ...
  375  2021-4      90  합천(285)  128.16994  35.56505      14.0       6.8
  376  2021-4      91  밀양(288)  128.74412  35.49147      14.0       7.1
  377  2021-4      92  산청(289)  127.87910  35.41300      13.8       7.0
  378  2021-4      93  거제(294)  128.60459  34.88818      14.3       9.4
  379  2021-4      94  남해(295)  127.92641  34.81662      14.3       9.3

       최고기온(°C) color
  285      16.6   red
  286      19.5   red
  287      18.7   red
  288      20.3   red
  289      19.0   red
  ..        ...   ...
  375      21.2   red
  376      21.2   red
  377      20.5   red
  378      19.7   red
  379      20.0   red

  [95 rows x 9 columns]),
 ('2021-5',
        month  dindex     지점정보         경도        위도  평균기온(°C)  최저기온(°C)  \
  380  2021-5       0   속초(90)  128.56473  38.25085      16.7      12.1
  381  2021-5       1  북춘천(93)  127.75443  37.94738      15.6       9.8
  382  2021-5       2   철원(95)  127.30420  38.14787      15.5       9.7
  383  2021-5       3  동두천(98)  127.06070  37.90188      15.8      10.2
  384  2021-5       4   파주(99)  126.76648  37.88589      15.5      10.1
  ..      ...     ...      ...        ...       ...       ...       ...
  470  2021-5      90  합천(285)  128.16994  35.56505      17.7      11.7
  471  2021-5      91  밀양(288)  128.74412  35.49147      18.2      12.3
  472  2021-5      92  산청(289)  127.87910  35.41300      17.2      11.2
  473  2021-5      93  거제(294)  128.60459  34.88818      17.8      13.7
  474  2021-5      94  남해(295)  127.92641  34.81662      18.3      13.7

       최고기온(°C) color
  380      21.5   red
  381      22.1   red
  382      21.8   red
  383      22.2   red
  384      21.9   red
  ..        ...   ...
  470      24.1   red
  471      24.5   red
  472      23.7   red
  473      22.2   red
  474      23.1   red

  [95 rows x 9 columns]),
 ('2021-6',
        month  dindex     지점정보         경도        위도  평균기온(°C)  최저기온(°C)  \
  475  2021-6       0   속초(90)  128.56473  38.25085      20.3      17.1
  476  2021-6       1  북춘천(93)  127.75443  37.94738      21.6      16.7
  477  2021-6       2   철원(95)  127.30420  38.14787      21.2      16.4
  478  2021-6       3  동두천(98)  127.06070  37.90188      21.3      16.8
  479  2021-6       4   파주(99)  126.76648  37.88589      21.1      16.7
  ..      ...     ...      ...        ...       ...       ...       ...
  565  2021-6      90  합천(285)  128.16994  35.56505      22.5      17.7
  566  2021-6      91  밀양(288)  128.74412  35.49147      23.2      18.6
  567  2021-6      92  산청(289)  127.87910  35.41300      22.1      17.4
  568  2021-6      93  거제(294)  128.60459  34.88818      21.7      18.3
  569  2021-6      94  남해(295)  127.92641  34.81662      22.1      18.4

       최고기온(°C) color
  475      23.8   red
  476      27.5   red
  477      26.8   red
  478      27.0   red
  479      26.7   red
  ..        ...   ...
  565      28.0   red
  566      28.7   red
  567      27.7   red
  568      25.8   red
  569      26.6   red

  [94 rows x 9 columns]),
 ('2021-7',
        month  dindex     지점정보         경도        위도  평균기온(°C)  최저기온(°C)  \
  570  2021-7       0   속초(90)  128.56473  38.25085      25.5      22.3
  571  2021-7       1  북춘천(93)  127.75443  37.94738      26.7      22.0
  572  2021-7       2   철원(95)  127.30420  38.14787      26.1      21.2
  573  2021-7       3  동두천(98)  127.06070  37.90188      26.4      22.1
  574  2021-7       4   파주(99)  126.76648  37.88589      26.1      22.0
  ..      ...     ...      ...        ...       ...       ...       ...
  660  2021-7      90  합천(285)  128.16994  35.56505      25.9      21.7
  661  2021-7      91  밀양(288)  128.74412  35.49147      26.7      22.5
  662  2021-7      92  산청(289)  127.87910  35.41300      25.8      21.9
  663  2021-7      93  거제(294)  128.60459  34.88818      26.1      23.4
  664  2021-7      94  남해(295)  127.92641  34.81662      26.1      22.9

       최고기온(°C) color
  570      29.3   red
  571      32.7   red
  572      31.7   red
  573      31.7   red
  574      31.4   red
  ..        ...   ...
  660      31.5   red
  661      32.5   red
  662      30.9   red
  663      29.5   red
  664      30.3   red

  [95 rows x 9 columns]),
 ('2021-8',
        month  dindex     지점정보         경도        위도  평균기온(°C)  최저기온(°C)  \
  665  2021-8       0   속초(90)  128.56473  38.25085      24.4      21.5
  666  2021-8       1  북춘천(93)  127.75443  37.94738      24.3      20.5
  667  2021-8       2   철원(95)  127.30420  38.14787      23.6      19.7
  668  2021-8       3  동두천(98)  127.06070  37.90188      24.3      20.6
  669  2021-8       4   파주(99)  126.76648  37.88589      24.1      20.1
  ..      ...     ...      ...        ...       ...       ...       ...
  755  2021-8      90  합천(285)  128.16994  35.56505      25.0      21.4
  756  2021-8      91  밀양(288)  128.74412  35.49147      26.2      22.7
  757  2021-8      92  산청(289)  127.87910  35.41300      25.1      21.6
  758  2021-8      93  거제(294)  128.60459  34.88818      25.8      23.0
  759  2021-8      94  남해(295)  127.92641  34.81662      26.1      23.0

       최고기온(°C) color
  665      28.0   red
  666      29.3   red
  667      28.7   red
  668      29.2   red
  669      29.3   red
  ..        ...   ...
  755      30.3   red
  756      31.3   red
  757      30.4   red
  758      29.2   red
  759      30.3   red

  [95 rows x 9 columns]),
 ('2021-9',
        month  dindex     지점정보         경도        위도  평균기온(°C)  최저기온(°C)  \
  760  2021-9       0   속초(90)  128.56473  38.25085      20.9      17.6
  761  2021-9       1  북춘천(93)  127.75443  37.94738      20.7      15.7
  762  2021-9       2   철원(95)  127.30420  38.14787      20.3      15.1
  763  2021-9       3  동두천(98)  127.06070  37.90188      20.8      16.2
  764  2021-9       4   파주(99)  126.76648  37.88589      20.6      16.0
  ..      ...     ...      ...        ...       ...       ...       ...
  850  2021-9      90  합천(285)  128.16994  35.56505      21.3      17.7
  851  2021-9      91  밀양(288)  128.74412  35.49147      22.7      18.9
  852  2021-9      92  산청(289)  127.87910  35.41300      21.0      17.4
  853  2021-9      93  거제(294)  128.60459  34.88818      22.3      19.6
  854  2021-9      94  남해(295)  127.92641  34.81662      22.2      19.5

       최고기온(°C) color
  760      24.7   red
  761      26.4   red
  762      26.0   red
  763      26.3   red
  764      26.5   red
  ..        ...   ...
  850      26.1   red
  851      27.4   red
  852      25.9   red
  853      25.6   red
  854      25.7   red

  [95 rows x 9 columns])]

In [40]:
df.\
assign(color=list(map(lambda x: 'red' if x > 0 else 'blue',df.iloc[:,5]))).\
groupby('month').\
pipe(list)[0]

('2021-1',
      month  dindex     지점정보         경도        위도  평균기온(°C)  최저기온(°C)  \
 0   2021-1       0   속초(90)  128.56473  38.25085      -1.2      -5.5
 1   2021-1       1  북춘천(93)  127.75443  37.94738      -5.7     -11.8
 2   2021-1       2   철원(95)  127.30420  38.14787      -5.9     -12.6
 3   2021-1       3  동두천(98)  127.06070  37.90188      -4.2      -9.9
 4   2021-1       4   파주(99)  126.76648  37.88589      -5.1     -11.4
 ..     ...     ...      ...        ...       ...       ...       ...
 90  2021-1      90  합천(285)  128.16994  35.56505       0.1      -5.8
 91  2021-1      91  밀양(288)  128.74412  35.49147       0.4      -5.3
 92  2021-1      92  산청(289)  127.87910  35.41300      -0.2      -5.5
 93  2021-1      93  거제(294)  128.60459  34.88818       2.9      -1.3
 94  2021-1      94  남해(295)  127.92641  34.81662       2.3      -2.2

     최고기온(°C) color
 0        2.9  blue
 1        0.7  blue
 2        0.7  blue
 3        2.1  blue
 4        1.5  blue
 ..       ...   ...
 90       7.1   red
 91       7.0   red
 92       6.1  blue
 93       7.2   red
 94       7.1   red

 [95 rows x 9 columns])

In [41]:
df.\
assign(color=list(map(lambda x: 'red' if x > 0 else 'blue',df.iloc[:,5]))).\
groupby('month').\
pipe(list)[0][1]

,month,dindex,지점정보,경도,위도,평균기온(°C),최저기온(°C),최고기온(°C),color
0,2021-1,0,속초(90),128.56473,38.25085,-1.2,-5.5,2.9,blue
1,2021-1,1,북춘천(93),127.75443,37.94738,-5.7,-11.8,0.7,blue
2,2021-1,2,철원(95),127.30420,38.14787,-5.9,-12.6,0.7,blue
3,2021-1,3,동두천(98),127.06070,37.90188,-4.2,-9.9,2.1,blue
4,2021-1,4,파주(99),126.76648,37.88589,-5.1,-11.4,1.5,blue
...,...,...,...,...,...,...,...,...,...
90,2021-1,90,합천(285),128.16994,35.56505,0.1,-5.8,7.1,red
91,2021-1,91,밀양(288),128.74412,35.49147,0.4,-5.3,7.0,red
92,2021-1,92,산청(289),127.87910,35.41300,-0.2,-5.5,6.1,blue
93,2021-1,93,거제(294),128.60459,34.88818,2.9,-1.3,7.2,red
94,2021-1,94,남해(295),127.92641,34.81662,2.3,-2.2,7.1,red

In [42]:
df.\
assign(color=list(map(lambda x: 'red' if x > 0 else 'blue',df.iloc[:,5]))).\
groupby('month').\
pipe(list)[0][1].iloc[:,[4,3,5,8]].to_numpy().tolist()

[[38.25085, 128.56473, -1.2, 'blue'],
 [37.94738, 127.75443, -5.7, 'blue'],
 [38.14787, 127.3042, -5.9, 'blue'],
 [37.90188, 127.0607, -4.2, 'blue'],
 [37.88589, 126.76648, -5.1, 'blue'],
 [37.67713, 128.71834, -7.3, 'blue'],
 [37.90262, 127.7357, -4.7, 'blue'],
 [37.97396, 124.71237, -1.0, 'blue'],
 [37.80456, 128.85535, -0.6, 'blue'],
 [37.75147, 128.89099, 0.6, 'red'],
 [37.50709, 129.12433, 0.6, 'red'],
 [37.57142, 126.9658, -2.4, 'blue'],
 [37.47772, 126.6249, -2.0, 'blue'],
 [37.33749, 127.94659, -2.9, 'blue'],
 [37.48129, 130.89863, 1.3, 'red'],
 [37.25746, 126.983, -2.4, 'blue'],
 [37.18126, 128.45743, -3.0, 'blue'],
 [36.97045, 127.9525, -3.6, 'blue'],
 [36.77658, 126.4939, -1.8, 'blue'],
 [36.99176, 129.41278, 0.6, 'red'],
 [36.63924, 127.44066, -1.4, 'blue'],
 [36.37198, 127.37211, -1.0, 'blue'],
 [36.22025, 127.99458, -2.3, 'blue'],
 [36.57293, 128.70733, -2.2, 'blue'],
 [36.40837, 128.15741, -1.8, 'blue'],
 [36.03201, 129.38002, 1.8, 'red'],
 [36.0053, 126.76135, 0.0, 'blue'],
 [35.87797, 128.65296, 0.5, 'red'],
 [35.84092, 127.11718, 0.5, 'red'],
 [35.58237, 129.33469, 2.1, 'red'],
 [35.17019, 128.57282, 1.4, 'red'],
 [35.17294, 126.89156, 1.4, 'red'],
 [35.10468, 129.03203, 3.3, 'red'],
 [34.84541, 128.43561, 3.2, 'red'],
 [34.81732, 126.38151, 2.0, 'red'],
 [34.73929, 127.74063, 2.9, 'red'],
 [34.68719, 125.45105, 4.5, 'red'],
 [34.3959, 126.70182, 3.3, 'red'],
 [35.34824, 126.599, 0.0, 'blue'],
 [35.0204, 127.3694, 0.0, 'blue'],
 [36.65759, 126.68772, -1.9, 'blue'],
 [33.51411, 126.52969, 6.8, 'red'],
 [33.29382, 126.16283, 6.9, 'red'],
 [33.38677, 126.8802, 5.9, 'red'],
 [33.24616, 126.5653, 7.2, 'red'],
 [35.16378, 128.04004, 0.6, 'red'],
 [37.70739, 126.44634, -3.3, 'blue'],
 [37.48863, 127.49446, -3.3, 'blue'],
 [37.26399, 127.48421, -3.4, 'blue'],
 [38.05986, 128.16714, -4.5, 'blue'],
 [37.6836, 127.88043, -4.8, 'blue'],
 [37.17038, 128.98929, -4.4, 'blue'],
 [37.38149, 128.6459, -4.3, 'blue'],
 [37.15928, 128.19433, -4.6, 'blue'],
 [36.48761, 127.73415, -3.1, 'blue'],
 [36.76217, 127.29282, -2.8, 'blue'],
 [36.32724, 126.55744, -0.2, 'blue'],
 [36.27242, 126.92079, -1.9, 'blue'],
 [36.10563, 127.48175, -2.0, 'blue'],
 [36.48522, 127.24438, -1.7, 'blue'],
 [35.72961, 126.71657, 0.0, 'blue'],
 [35.61203, 127.28556, -2.0, 'blue'],
 [35.56337, 126.83904, -0.4, 'blue'],
 [35.4213, 127.39652, -0.8, 'blue'],
 [35.65696, 127.52031, -2.8, 'blue'],
 [35.42661, 126.697, 0.0, 'blue'],
 [35.28366, 126.47784, 0.2, 'red'],
 [35.22981, 128.89075, 1.8, 'red'],
 [35.37131, 127.1286, -0.9, 'blue'],
 [35.22655, 128.6726, 2.8, 'red'],
 [35.30737, 129.02009, 2.3, 'red'],
 [34.76335, 127.21226, 2.0, 'red'],
 [34.6289, 126.76715, 1.4, 'red'],
 [34.68886, 126.91951, 1.0, 'red'],
 [34.55375, 126.56907, 0.9, 'red'],
 [34.61826, 127.27572, 1.4, 'red'],
 [35.32258, 128.28812, 0.6, 'red'],
 [35.51138, 127.74538, -0.5, 'blue'],
 [34.9434, 127.6914, 2.5, 'red'],
 [34.47296, 126.25846, 2.7, 'red'],
 [36.94361, 128.91449, -4.5, 'blue'],
 [36.87183, 128.51687, -3.0, 'blue'],
 [36.62727, 128.14879, -2.2, 'blue'],
 [36.4351, 129.04005, -3.1, 'blue'],
 [36.53337, 129.40926, 0.6, 'red'],
 [36.3561, 128.68864, -2.9, 'blue'],
 [36.13055, 128.32055, -0.4, 'blue'],
 [35.97742, 128.9514, -0.5, 'blue'],
 [35.8174, 129.2009, 0.0, 'blue'],
 [35.66739, 127.9099, -1.0, 'blue'],
 [35.56505, 128.16994, 0.1, 'red'],
 [35.49147, 128.74412, 0.4, 'red'],
 [35.413, 127.8791, -0.2, 'blue'],
 [34.88818, 128.60459, 2.9, 'red'],
 [34.81662, 127.92641, 2.3, 'red']]

In [43]:
lst=[df.\
     assign(color=list(map(lambda x: 'red' if x > 0 else 'blue',df.iloc[:,5]))).\
     groupby('month').\
     pipe(list)[i][1].iloc[:,[4,3,5,8]].\
     to_numpy().tolist()
     for i in range(10)]