# (노트) plotly - 3d scatter

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- categories: [시각화]

### ref

- https://plotly.com/python/

### imports

In [9]:
from IPython.display import HTML
import plotly.express as px
import numpy as np
import pandas as pd

In [10]:
def show(fig): 
    return HTML(fig.to_html(include_plotlyjs='cdn',include_mathjax=False, config=dict({'scrollZoom':False})))

### 기본사용

`-` 방법1: 벡터에서 바로 플랏

In [113]:
x=np.linspace(0,1,50)
y=np.sin(10*x)
z=2*x

In [114]:
fig=px.scatter_3d(x=x,y=y,z=z)
show(fig)

참고로 아래는 동작하지 않음. 

```python
x=np.linspace(0,1,50)
y=np.sin(10*x)
z=2*x
fig=px.scatter_3d(x,y,z)
show(fig)
```

왜냐하면 첫 args가 df임 

```python
px.scatter_3d(
    data_frame=None,
    x=None,
    y=None,
    z=None,
    color=None,
    symbol=None,
    size=None,
    text=None,
    ... 
    title=None,
    template=None,
    width=None,
    height=None,    
)
```

`-` 방법2: df이용

In [115]:
df = pd.DataFrame({'x':x,'y':y,'z':z})
df

           x         y         z
0   0.000000  0.000000  0.000000
1   0.020408  0.202668  0.040816
2   0.040816  0.396924  0.081633
3   0.061224  0.574706  0.122449
4   0.081633  0.728635  0.163265
5   0.102041  0.852322  0.204082
6   0.122449  0.940633  0.244898
7   0.142857  0.989903  0.285714
8   0.163265  0.998087  0.326531
9   0.183673  0.964846  0.367347
10  0.204082  0.891559  0.408163
11  0.224490  0.781268  0.448980
12  0.244898  0.638550  0.489796
13  0.265306  0.469330  0.530612
14  0.285714  0.280629  0.571429
15  0.306122  0.080282  0.612245
16  0.326531 -0.123398  0.653061
17  0.346939 -0.321956  0.693878
18  0.367347 -0.507152  0.734694
19  0.387755 -0.671298  0.775510
20  0.408163 -0.807582  0.816327
21  0.428571 -0.910347  0.857143
22  0.448980 -0.975328  0.897959
23  0.469388 -0.999829  0.938776
24  0.489796 -0.982831  0.979592
25  0.510204 -0.925041  1.020408
26  0.530612 -0.828858  1.061224
27  0.551020 -0.698272  1.102041
28  0.571429 -0.538705  1.142857
29  0.591837 -0.356779  1.183673
30  0.612245 -0.160045  1.224490
31  0.632653  0.043332  1.265306
32  0.653061  0.244910  1.306122
33  0.673469  0.436323  1.346939
34  0.693878  0.609627  1.387755
35  0.714286  0.757628  1.428571
36  0.734694  0.874184  1.469388
37  0.755102  0.954457  1.510204
38  0.775510  0.995115  1.551020
39  0.795918  0.994471  1.591837
40  0.816327  0.952552  1.632653
41  0.836735  0.871097  1.673469
42  0.857143  0.753487  1.714286
43  0.877551  0.604603  1.755102
44  0.897959  0.430626  1.795918
45  0.918367  0.238775  1.836735
46  0.938776  0.037014  1.877551
47  0.959184 -0.166283  1.918367
48  0.979592 -0.362678  1.959184
49  1.000000 -0.544021  2.000000

In [116]:
fig = px.scatter_3d(df,x,y,z)
show(fig)

### 여러가지 옵션

`-` 기본옵션들: color, symbol, size, text

In [117]:
col = ['A']*20 + ['B']*30 
sym = ['A']*30 + ['B']*20 
size = np.random.rand(50) 
text = ['a']*30 + ['b']*20

In [118]:
df2=df.assign(col=col,sym=sym,size=size,text=text)
df2

           x         y         z col sym      size text
0   0.000000  0.000000  0.000000   A   A  0.468773    a
1   0.020408  0.202668  0.040816   A   A  0.934411    a
2   0.040816  0.396924  0.081633   A   A  0.311991    a
3   0.061224  0.574706  0.122449   A   A  0.010404    a
4   0.081633  0.728635  0.163265   A   A  0.346915    a
5   0.102041  0.852322  0.204082   A   A  0.885235    a
6   0.122449  0.940633  0.244898   A   A  0.369324    a
7   0.142857  0.989903  0.285714   A   A  0.301607    a
8   0.163265  0.998087  0.326531   A   A  0.766323    a
9   0.183673  0.964846  0.367347   A   A  0.907545    a
10  0.204082  0.891559  0.408163   A   A  0.562417    a
11  0.224490  0.781268  0.448980   A   A  0.259881    a
12  0.244898  0.638550  0.489796   A   A  0.328810    a
13  0.265306  0.469330  0.530612   A   A  0.460122    a
14  0.285714  0.280629  0.571429   A   A  0.286673    a
15  0.306122  0.080282  0.612245   A   A  0.453286    a
16  0.326531 -0.123398  0.653061   A   A  0.909796    a
17  0.346939 -0.321956  0.693878   A   A  0.288798    a
18  0.367347 -0.507152  0.734694   A   A  0.469791    a
19  0.387755 -0.671298  0.775510   A   A  0.448423    a
20  0.408163 -0.807582  0.816327   B   A  0.643585    a
21  0.428571 -0.910347  0.857143   B   A  0.547529    a
22  0.448980 -0.975328  0.897959   B   A  0.023432    a
23  0.469388 -0.999829  0.938776   B   A  0.537372    a
24  0.489796 -0.982831  0.979592   B   A  0.818153    a
25  0.510204 -0.925041  1.020408   B   A  0.612145    a
26  0.530612 -0.828858  1.061224   B   A  0.443320    a
27  0.551020 -0.698272  1.102041   B   A  0.719508    a
28  0.571429 -0.538705  1.142857   B   A  0.235216    a
29  0.591837 -0.356779  1.183673   B   A  0.678044    a
30  0.612245 -0.160045  1.224490   B   B  0.138567    b
31  0.632653  0.043332  1.265306   B   B  0.790132    b
32  0.653061  0.244910  1.306122   B   B  0.753502    b
33  0.673469  0.436323  1.346939   B   B  0.752988    b
34  0.693878  0.609627  1.387755   B   B  0.729469    b
35  0.714286  0.757628  1.428571   B   B  0.944653    b
36  0.734694  0.874184  1.469388   B   B  0.550544    b
37  0.755102  0.954457  1.510204   B   B  0.985363    b
38  0.775510  0.995115  1.551020   B   B  0.600462    b
39  0.795918  0.994471  1.591837   B   B  0.482341    b
40  0.816327  0.952552  1.632653   B   B  0.450666    b
41  0.836735  0.871097  1.673469   B   B  0.266718    b
42  0.857143  0.753487  1.714286   B   B  0.163359    b
43  0.877551  0.604603  1.755102   B   B  0.257391    b
44  0.897959  0.430626  1.795918   B   B  0.501833    b
45  0.918367  0.238775  1.836735   B   B  0.643460    b
46  0.938776  0.037014  1.877551   B   B  0.347584    b
47  0.959184 -0.166283  1.918367   B   B  0.645859    b
48  0.979592 -0.362678  1.959184   B   B  0.788728    b
49  1.000000 -0.544021  2.000000   B   B  0.304564    b

In [121]:
fig = px.scatter_3d(df2,x,y,z,col,sym,size,text)
show(fig)

`-` 몇개의 문자만 표현하고 싶다면?

In [122]:
text2 = [None]*30 + ['31'] + [None]*18 + ['50']
df3=df2.assign(text2=text2)

In [123]:
fig = px.scatter_3d(df2,x,y,z,col,sym,size,text2)
show(fig)

`-` sizemax의 이용!

In [124]:
fig = px.scatter_3d(df2,x,y,z,col,sym,size,text2,size_max=10)
show(fig)

In [125]:
fig = px.scatter_3d(df2,x,y,z,col,sym,size,text2,size_max=50)
show(fig)

`-` 투명도: 여기에서 투명도는 하나의 값으로만 설정가능하다. array로 줄 수 없다.

In [126]:
fig = px.scatter_3d(df2,x,y,z,col,sym,size,text2,opacity=0.2)
show(fig)

In [127]:
fig = px.scatter_3d(df2,x,y,z,col,sym,size,text2,opacity=size)
show(fig)

ValueError:
    Invalid value of type 'numpy.ndarray' received for the 'opacity' property of scatter3d.marker
        Received value: array([0.46877331, 0.93441062, 0.31199054, 0.01040361, 0.34691498,
       0.885235  , 0.36932382, 0.30160651, 0.7663228 , 0.90754536,
       0.56241742, 0.25988126, 0.32881044, 0.46012187, 0.28667269,
       0.45328601, 0.9097957 , 0.28879814, 0.46979131, 0.44842304,
       0.64358485, 0.54752899, 0.02343174, 0.53737236, 0.81815272,
       0.61214481, 0.44331983, 0.71950753, 0.23521551, 0.6780437 ,
       0.13856657, 0.79013233, 0.75350221, 0.75298832, 0.72946926,
       0.94465321, 0.55054387, 0.98536266, 0.6004618 , 0.48234079,
       0.45066579, 0.26671827, 0.163359  , 0.25739145, 0.50183282,
       0.64346012, 0.34758377, 0.64585909, 0.78872781, 0.30456375])

    The 'opacity' property is a number and may be specified as:
      - An int or float in the interval [0, 1]

### 연산가능

In [138]:
fig = px.scatter_3d(df2,x,y,np.tan(z),col,sym,size,text2)
show(fig)

In [139]:
fig = px.scatter_3d(df2,x,y,z,col,sym,size,text2)
show(fig)

In [140]:
fig = px.scatter_3d(df2,x,y,z,col,sym,size**5,text2)
show(fig)

### sdf