# (노트) 토픽모델
> 미완성

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- categories: [통계계산]

### about this doc

`-` 전북대학교 통계계산 강의노트

### data

`-` 아래와 같은 자료가 있다고 가정하자.

In [4]:
library(tidyverse)

In [70]:
doc1<-c('손흥민','박지성','골','어시스트','패스')
doc2<-c('손흥민','박지성','16강','반칙','패널트킥')
doc3<-c('손흥민','박지성','16강','확률','도박사')
doc4<-c('손흥민','예측','16강','확률','도박사')
doc5<-c('통계','예측','16강','확률','도박사')

doc6<-c('통계','예측','데이터과학','확률','도박사')
doc7<-c('통계','예측','데이터과학','확률','빅데이터')
doc8<-c('통계','4차산업혁명','데이터과학','마코프','빅데이터')
doc9<-c('통계','4차산업혁명','AI','빅데이터','데이터과학')
doc10<-c('컴퓨터','4차산업혁명','AI','빅데이터','데이터과학')

In [64]:
corpus<-tibble(doc1=doc1,doc2=doc2,doc3=doc3,doc4=doc4,doc5=doc5,doc6=doc6,doc7=doc7,doc8=doc8,doc9=doc9,doc10=doc10)
corpus

  doc1     doc2     doc3   doc4   doc5   doc6       doc7       doc8
1 손흥민   손흥민   손흥민 손흥민 통계   통계       통계       통계
2 박지성   박지성   박지성 배팅   가능성 가능성     가능성     4차산업혁명
3 골       16강     16강   16강   16강   데이터과학 데이터과학 데이터과학
4 어시스트 반칙     확률   확률   확률   확률       확률       마코프
5 패스     패널트킥 도박사 도박사 도박사 도박사     빅데이터   빅데이터
  doc9        doc10
1 통계        컴퓨터
2 4차산업혁명 4차산업혁명
3 AI          AI
4 빅데이터    빅데이터
5 데이터과학  데이터과학

#### topic

`-` 두개의 토픽이 있어보인다. (스포츠, 통계)

`-` 두개의 토픽이 적절하게 믹스된것 처럼 보이는 doc도 보인다.

#### 사전

In [71]:
dict <- corpus %>% as.matrix %>% as.vector %>% table %>% as_tibble

In [72]:
dict

   .           n
1  16강        4
2  4차산업혁명 3
3  AI          2
4  가능성      3
5  골          1
6  데이터과학  5
7  도박사      4
8  마코프      1
9  박지성      3
10 반칙        1
11 배팅        1
12 빅데이터    4
13 손흥민      4
14 어시스트    1
15 컴퓨터      1
16 통계        5
17 패널트킥    1
18 패스        1
19 확률        5

In [73]:
print(dim(dict))

[1] 19  2

사전에는 19개의 단어가 있다.

### 노테이션

- $corpus=\{doc1,doc2,\dots,doc10\} \Longleftrightarrow {\bf W}=\{{\bf w}_1,\dots,{\bf w}_{10}\}$

### 목표

`-` (스포츠,통계) = (0.3,0.7) $\to$ 그에 맞는 단어들이 생성

### 한계

`-` 우리는 (스포츠,통계)=(0.3,0.7)일 경우에 해당하는 문서가 무엇인지 모르고, 당연히 그 문서에 무슨 단어가 어떠한 비율로 있는지 잘 모르겠다.

`-` 그런데 (스포츠,통계)=(1,0)일 경우와 (스포츠,통계)=(0,1)일 경우는 어떤 문서가 해당하는지 알 것 같다. 그리고 그 문서에 무슨 단어가 어떠한 비율로 있는지도 알 것 같다.

`-` joint distribution은 모르지만, conditional distribution은 알겠다.

### 풀이1

`-` 내가 스스로 판단하여 각 단어가 스포츠에 속하는지, 통계에 속하는지 분류한다.

`-` 아래와 과정을 따라 생성한다.

### 모델링

`-` 한 문서안에 스포츠 주제가 차지하는 비율을 $p$ 라고 하자.

### 시뮬레이션

In [74]:
dict

   .           n
1  16강        4
2  4차산업혁명 3
3  AI          2
4  가능성      3
5  골          1
6  데이터과학  5
7  도박사      4
8  마코프      1
9  박지성      3
10 반칙        1
11 배팅        1
12 빅데이터    4
13 손흥민      4
14 어시스트    1
15 컴퓨터      1
16 통계        5
17 패널트킥    1
18 패스        1
19 확률        5

In [83]:
init_topic=c(0.1,)
cbind(dict, init_topic)

   .           n init_topic
1  16강        4 1
2  4차산업혁명 3 1
3  AI          2 1
4  가능성      3 0
5  골          1 1
6  데이터과학  5 0
7  도박사      4 1
8  마코프      1 1
9  박지성      3 0
10 반칙        1 1
11 배팅        1 0
12 빅데이터    4 0
13 손흥민      4 0
14 어시스트    1 1
15 컴퓨터      1 1
16 통계        5 1
17 패널트킥    1 1
18 패스        1 0
19 확률        5 0

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10

In [62]:
beta[,-2] %>% table %>% as_tibble

   .           topic  n
1  16강        스포츠 1
2  4차산업혁명 스포츠 0
3  AI          스포츠 0
4  골          스포츠 1
5  데이터과학  스포츠 0
6  도박사      스포츠 0
7  마코프      스포츠 0
8  박지성      스포츠 1
9  반칙        스포츠 1
10 배팅        스포츠 0
11 빅데이터    스포츠 0
12 손흥민      스포츠 1
13 어시스트    스포츠 1
14 컴퓨터      스포츠 0
15 통계        스포츠 0
16 패널트킥    스포츠 1
17 패스        스포츠 1
18 확률        스포츠 0
19 16강        통계   0
20 4차산업혁명 통계   1
21 AI          통계   1
22 골          통계   0
23 데이터과학  통계   1
24 도박사      통계   1
25 마코프      통계   1
26 박지성      통계   0
27 반칙        통계   0
28 배팅        통계   1
29 빅데이터    통계   1
30 손흥민      통계   0
31 어시스트    통계   0
32 컴퓨터      통계   1
33 통계        통계   1
34 패널트킥    통계   0
35 패스        통계   0
36 확률        통계   1