# tidydata

### weapons

#### tidying (wide $\to$ long)

`-` stack()

#### untidying (long $\to$ wide)

### Examples

#### 예제: state_fruit

(문제)

https://github.com/PacktPublishing/Pandas-Cookbook-Second-Edition/blob/master/data/state_fruit.csv

`-` 문제의 깃헙주소로 들어가서 데이터를 관찰 $\to$ 좌측상단이 'State'로 채워져있음 $\to$ 데이터를 읽을때 `index_col=0` 옵션을 사용함.

In [479]:
url = 'https://raw.githubusercontent.com/PacktPublishing/Pandas-Cookbook-Second-Edition/master/data/state_fruit.csv'
state_fruit = pd.read_csv(url,index_col=0) 
state_fruit

         Apple  Orange  Banana
Texas       12      10      40
Arizona      9       7      12
Florida      0      14     190

(풀이1)

In [493]:
state_fruit.stack()

Texas    Apple      12
         Orange     10
         Banana     40
Arizona  Apple       9
         Orange      7
         Banana     12
Florida  Apple       0
         Orange     14
         Banana    190
dtype: int64

In [494]:
state_fruit.stack().reset_index()

   level_0 level_1    0
0    Texas   Apple   12
1    Texas  Orange   10
2    Texas  Banana   40
3  Arizona   Apple    9
4  Arizona  Orange    7
5  Arizona  Banana   12
6  Florida   Apple    0
7  Florida  Orange   14
8  Florida  Banana  190

In [495]:
_tidy=state_fruit.stack().reset_index()
_tidy

   level_0 level_1    0
0    Texas   Apple   12
1    Texas  Orange   10
2    Texas  Banana   40
3  Arizona   Apple    9
4  Arizona  Orange    7
5  Arizona  Banana   12
6  Florida   Apple    0
7  Florida  Orange   14
8  Florida  Banana  190

In [496]:
_tidy=_tidy.rename(columns={'level_0':'G1','level_1':'G2'})
_tidy

        G1      G2    0
0    Texas   Apple   12
1    Texas  Orange   10
2    Texas  Banana   40
3  Arizona   Apple    9
4  Arizona  Orange    7
5  Arizona  Banana   12
6  Florida   Apple    0
7  Florida  Orange   14
8  Florida  Banana  190

In [497]:
_tidy=_tidy.rename(columns={0:'X1'})
_tidy

        G1      G2   X1
0    Texas   Apple   12
1    Texas  Orange   10
2    Texas  Banana   40
3  Arizona   Apple    9
4  Arizona  Orange    7
5  Arizona  Banana   12
6  Florida   Apple    0
7  Florida  Orange   14
8  Florida  Banana  190

(풀이2)

In [498]:
_tidy= state_fruit.stack().reset_index()
_tidy

   level_0 level_1    0
0    Texas   Apple   12
1    Texas  Orange   10
2    Texas  Banana   40
3  Arizona   Apple    9
4  Arizona  Orange    7
5  Arizona  Banana   12
6  Florida   Apple    0
7  Florida  Orange   14
8  Florida  Banana  190

In [499]:
_tidy.columns

Index(['level_0', 'level_1', 0], dtype='object')

In [500]:
pd.Index(['G1','G2','X1'])

Index(['G1', 'G2', 'X1'], dtype='object')

In [501]:
_tidy.columns=pd.Index(['G1','G2','X1'])

In [502]:
_tidy

        G1      G2   X1
0    Texas   Apple   12
1    Texas  Orange   10
2    Texas  Banana   40
3  Arizona   Apple    9
4  Arizona  Orange    7
5  Arizona  Banana   12
6  Florida   Apple    0
7  Florida  Orange   14
8  Florida  Banana  190

- 풀이1은 하나씩 생각나는대로 이름을 바꿔주면 되는 반면 풀이2는 한번에 모든 이름을 바꿔야한다.

(틀린풀이) 열이름을 변경할때 df.columns.values를 이용하여 억지로 바꾸면 문제가 생긴다.

In [513]:
_tidy= state_fruit.stack().reset_index()
_tidy

   level_0 level_1    0
0    Texas   Apple   12
1    Texas  Orange   10
2    Texas  Banana   40
3  Arizona   Apple    9
4  Arizona  Orange    7
5  Arizona  Banana   12
6  Florida   Apple    0
7  Florida  Orange   14
8  Florida  Banana  190

In [514]:
_tidy.columns

Index(['level_0', 'level_1', 0], dtype='object')

In [515]:
_tidy.columns.values

array(['level_0', 'level_1', 0], dtype=object)

In [516]:
_tidy.columns.values[0]

'level_0'

In [517]:
_tidy.columns.values[0]='G1'
_tidy.columns.values[1]='G2'
_tidy.columns.values[2]='G3'

In [518]:
_tidy.columns

Index(['G1', 'G2', 'G3'], dtype='object')

In [519]:
_tidy

        G1      G2   G3
0    Texas   Apple   12
1    Texas  Orange   10
2    Texas  Banana   40
3  Arizona   Apple    9
4  Arizona  Orange    7
5  Arizona  Banana   12
6  Florida   Apple    0
7  Florida  Orange   14
8  Florida  Banana  190

- 얼핏보면 맞아보이는데 key로 인덱싱이 안된다. (한마디로 위의 데이터프레임은 깨져있다.)

`-` KeyError를 확인하자.

In [530]:
_tidy['G1']

KeyError: 'G1'

(풀이3)

In [417]:
_tidy= state_fruit.stack()
_tidy

Texas    Apple      12
         Orange     10
         Banana     40
Arizona  Apple       9
         Orange      7
         Banana     12
Florida  Apple       0
         Orange     14
         Banana    190
dtype: int64

In [418]:
_tidy=_tidy.rename_axis(['G1','G2'])
_tidy

G1       G2
Texas    Apple      12
         Orange     10
         Banana     40
Arizona  Apple       9
         Orange      7
         Banana     12
Florida  Apple       0
         Orange     14
         Banana    190
dtype: int64

In [419]:
_tidy.reset_index()

        G1      G2    0
0    Texas   Apple   12
1    Texas  Orange   10
2    Texas  Banana   40
3  Arizona   Apple    9
4  Arizona  Orange    7
5  Arizona  Banana   12
6  Florida   Apple    0
7  Florida  Orange   14
8  Florida  Banana  190

In [420]:
_tidy.reset_index().rename(columns={0:'X1'})

        G1      G2   X1
0    Texas   Apple   12
1    Texas  Orange   10
2    Texas  Banana   40
3  Arizona   Apple    9
4  Arizona  Orange    7
5  Arizona  Banana   12
6  Florida   Apple    0
7  Florida  Orange   14
8  Florida  Banana  190

(풀이4)

In [421]:
state_fruit.stack()

Texas    Apple      12
         Orange     10
         Banana     40
Arizona  Apple       9
         Orange      7
         Banana     12
Florida  Apple       0
         Orange     14
         Banana    190
dtype: int64

In [422]:
state_fruit.stack().rename_axis(['G1','G2'])

G1       G2
Texas    Apple      12
         Orange     10
         Banana     40
Arizona  Apple       9
         Orange      7
         Banana     12
Florida  Apple       0
         Orange     14
         Banana    190
dtype: int64

In [423]:
state_fruit.stack().rename_axis(['G1','G2']).reset_index(name='X1')

        G1      G2   X1
0    Texas   Apple   12
1    Texas  Orange   10
2    Texas  Banana   40
3  Arizona   Apple    9
4  Arizona  Orange    7
5  Arizona  Banana   12
6  Florida   Apple    0
7  Florida  Orange   14
8  Florida  Banana  190

(풀이5) 데이터를 불러올때 아예 좌측상단이 채워졌다고 생각하고 불러오자. 즉 `index=0`을 사용하지 말자.

In [464]:
url = 'https://raw.githubusercontent.com/PacktPublishing/Pandas-Cookbook-Second-Edition/master/data/state_fruit.csv'
state_fruit = pd.read_csv(url)  #state_fruit = pd.read_csv(url,index_col=0) 
state_fruit

  Unnamed: 0  Apple  Orange  Banana
0      Texas     12      10      40
1    Arizona      9       7      12
2    Florida      0      14     190

In [465]:
state_fruit.columns.values

array(['Unnamed: 0', 'Apple', 'Orange', 'Banana'], dtype=object)

In [467]:
state_fruit=state_fruit.rename(columns={'Unnamed: 0':'G1'})
state_fruit

        G1  Apple  Orange  Banana
0    Texas     12      10      40
1  Arizona      9       7      12
2  Florida      0      14     190

In [473]:
state_fruit=state_fruit.melt(id_vars=['G1'])
state_fruit

        G1 variable  value
0    Texas    Apple     12
1  Arizona    Apple      9
2  Florida    Apple      0
3    Texas   Orange     10
4  Arizona   Orange      7
5  Florida   Orange     14
6    Texas   Banana     40
7  Arizona   Banana     12
8  Florida   Banana    190

In [1]:
state_fruit.rename(columns={'variable':'G2','value':'X1'})

NameError: name 'state_fruit' is not defined

#### 예제: state_fruit2

(문제)

https://github.com/PacktPublishing/Pandas-Cookbook-Second-Edition/blob/master/data/state_fruit2.csv

`-` 문제의 깃헙주소로 들어가서 데이터를 관찰 $\to$ 좌측상단이 'State'로 채워져있음 $\to$ 데이터를 읽을때 `index_col=0` 옵션을 사용하지 않음.

In [426]:
url = 'https://raw.githubusercontent.com/PacktPublishing/Pandas-Cookbook-Second-Edition/master/data/state_fruit2.csv'
state_fruit2 = pd.read_csv(url) # 문제의 주소로 들어가서 데이터를 살펴보자 -> 좌측상단이 채워짐 -> index_col=0 으로 불러오지 않음. 
state_fruit2

     State  Apple  Orange  Banana
0    Texas     12      10      40
1  Arizona      9       7      12
2  Florida      0      14     190

- index1: `{State: [Texas, Arizona, Florida]}` = row
- index2: `{??? :[Apple, Orange, Banana]}` = col

(풀이1)

In [433]:
state_fruit2.melt()

   variable    value
0     State    Texas
1     State  Arizona
2     State  Florida
3     Apple       12
4     Apple        9
5     Apple        0
6    Orange       10
7    Orange        7
8    Orange       14
9    Banana       40
10   Banana       12
11   Banana      190

In [434]:
state_fruit2.melt(id_vars=['State'])

     State variable  value
0    Texas    Apple     12
1  Arizona    Apple      9
2  Florida    Apple      0
3    Texas   Orange     10
4  Arizona   Orange      7
5  Florida   Orange     14
6    Texas   Banana     40
7  Arizona   Banana     12
8  Florida   Banana    190

In [ ]:
-

In [435]:
state_fruit2.melt(id_vars=['State'],var_name='Fruit')

     State   Fruit  value
0    Texas   Apple     12
1  Arizona   Apple      9
2  Florida   Apple      0
3    Texas  Orange     10
4  Arizona  Orange      7
5  Florida  Orange     14
6    Texas  Banana     40
7  Arizona  Banana     12
8  Florida  Banana    190

In [437]:
state_fruit2.melt(id_vars=['State'],var_name='Fruit',value_name='Weight')

     State   Fruit  Weight
0    Texas   Apple      12
1  Arizona   Apple       9
2  Florida   Apple       0
3    Texas  Orange      10
4  Arizona  Orange       7
5  Florida  Orange      14
6    Texas  Banana      40
7  Arizona  Banana      12
8  Florida  Banana     190

In [436]:
state_fruit2.melt(id_vars=['State'],value_vars=['Orange','Apple','Banana'])

     State variable  value
0    Texas   Orange     10
1  Arizona   Orange      7
2  Florida   Orange     14
3    Texas    Apple     12
4  Arizona    Apple      9
5  Florida    Apple      0
6    Texas   Banana     40
7  Arizona   Banana     12
8  Florida   Banana    190

***melt를 이용하여 데이터를 깨끗하게 만들기 위한 작전 (변형하고 싶은 데이터의 형태가 직관적으로 떠오르지 않을 경우)***

`*` Step1: [State, Apple, Orange, Banana] 중 하나의 변수를 선택하여 index1로 설정한다. 
- 요령1: [State, Apple, Orange, Banana] 중에서 숫자를 값으로 가지는 변수명은 제외한다. $\to$ 여기에서 Apple, Orange, Banana가 제외됨. 
- 요령2: 여기서 선택되는 변수가 `G1`자리에 들어온다. `G1`자리에 어울릴만한 변수를 선택.

`*` Step2: melt()사용. 필수옵션은 `id_vars`, `var_name`. 
- `id_vars`: Step1에서 선택한 변수이름, 즉 State. `G1`에 해당하는 변수명. 
- `var_name`: Step1에서 선택한 변수를 제외한 나머지 변수명(즉 [Apple, Orange, Banana])을 통합할 만한 변수이름을 '새롭게 정의함'. 이름이 잘 생각안나면 그냥 `G2`로 정하자. 
- `value_name`: 설정안해도 무방. `X1`자리의 이름임. `X1`에 적당한 이름을 주면 된다.