# 연습장

In [9]:
import pandas as pd
import numpy as np

In [10]:
sa= pd.Series([1,2,3],index=list('abc'))

In [11]:
sa.b

2

In [12]:
dfa=df.copy()

NameError: name 'df' is not defined

In [15]:
dates=pd.date_range('1/1/2000', periods=8)

In [16]:
df=pd.DataFrame(np.random.randn(8,4),index=dates, columns=['A','B','C','D'])

In [17]:
df

                   A         B         C         D
2000-01-01  0.599195 -0.156579 -0.737755  0.771692
2000-01-02  0.554362  1.550815  0.228813  1.341562
2000-01-03  2.432237 -1.677383 -0.424558  1.574645
2000-01-04 -0.187302  1.292429 -1.291211 -1.476967
2000-01-05  0.450574  1.081492 -0.494514 -1.073831
2000-01-06  0.691768  1.260473  0.806306 -0.097995
2000-01-07 -0.643412  1.168977  0.595487  0.802224
2000-01-08 -1.247871  0.663575  0.941541 -0.944152

In [20]:
df.iloc[:,::-1]

                   D         C         B         A
2000-01-01  0.771692 -0.737755 -0.156579  0.599195
2000-01-02  1.341562  0.228813  1.550815  0.554362
2000-01-03  1.574645 -0.424558 -1.677383  2.432237
2000-01-04 -1.476967 -1.291211  1.292429 -0.187302
2000-01-05 -1.073831 -0.494514  1.081492  0.450574
2000-01-06 -0.097995  0.806306  1.260473  0.691768
2000-01-07  0.802224  0.595487  1.168977 -0.643412
2000-01-08 -0.944152  0.941541  0.663575 -1.247871